### ISSUE TITLE
Styling discrepancies between dev and build

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1003]
I'm not 100% what causes it, my first guess is that the priority of CSS rules changes in hot reload vs build mode because the CSS classes change name and all rules in them are crossed out in firefox

Preview build:

<img width="997" alt="Screen Shot 2021-04-07 at 3 16 06 pm" src="https://user-images.githubusercontent.com/2975660/113921717-54f23900-97b4-11eb-98b5-3691fb6372ac.png">

Local version with `yarn start`:

<img width="980" alt="Screen Shot 2021-04-07 at 3 16 10 pm" src="https://user-images.githubusercontent.com/2975660/113922133-e95c9b80-97b4-11eb-80a8-6c3ef5859374.png">

Note lack of underline in "Built by the community and always free", and the difference in margin and bolding of the fields

**Comment by lucaslcode** [comment]
Looks like yet another instance of "we fixed it in v5" from MUI which is bloody annoying because it's a huge migration and v5 isn't even stable yet. https://github.com/mui-org/material-ui/issues/16316

**Comment by lucaslcode** [comment]
I believe a workaround might be using the `classes` prop instead of `className`

**Comment by lucaslcode** [comment]
Solved in #1039
