### ISSUE TITLE
[bug][frontend] Message list does not show new messages in preview until refresh

### ISSUE THREAD

**Issue by trevvorko** [Couchers-org/couchers#1004]
When a user sends a message to another user in chats, hosting, or surfing tab, the recipient will see the number badge update in the tab list. The conversation preview does not update by showing the latest message that was received until the user refreshes the page or leaves the tab and goes back. This isn't a big issue, but if a user is actively chatting with another user and wants to see the message preview they are unable to do so.

**Comment by lucaslcode** [comment]
This can be solved in the notifications logic by invalidating the list of chats when a new message comes in

**Comment by mar7yn** [comment]
Hi. I can look into this one
