### ISSUE TITLE
Change style sheet for profile page on medium-sized screens?

### ISSUE THREAD

**Issue by naspitha** [Couchers-org/couchers#1019]
Profile layout looks good on large PC screens and on phone, but the "phone" layout also seems to apply for medium-sized screens (below ~960 px), such that the profile picture now takes up the entire page width and looks humongous. 
![image](https://user-images.githubusercontent.com/23509977/113951550-5e41cc80-97d9-11eb-9e46-82dc116d84bf.png)

I think it would be better if the intermediate-screen-size had a more similar layout to the big-screen size (profile picture + box on the left, and text on the right). If there is a concern with fitting things width-wise that way, maybe the "About Home" section could turn into single-column if needed.

Feel free to close this issue if this type of design is intentional.

**Comment by aapeliv** [comment]
I know it doesn't look ideal but this is pretty low priority

**Comment by lucaslcode** [comment]
I think we need to at least give the profile pic a max width
