### ISSUE TITLE
Autolink weirdness in markdown editor

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1026]
Add an [autolink](https://spec.commonmark.org/0.29/#autolinks):

<img width="526" alt="Screen Shot 2021-04-08 at 8 36 37 am" src="https://user-images.githubusercontent.com/2975660/114027733-b0b8d280-9845-11eb-8be3-6cbcb113ab14.png">

Save it, and you get this:

<img width="381" alt="Screen Shot 2021-04-08 at 8 36 55 am" src="https://user-images.githubusercontent.com/2975660/114027750-b44c5980-9845-11eb-8780-ed5f10cdf12a.png">

Go to edit it again and it appears as this (I think it's changed to a normal link on load of the markdown editor):

<img width="789" alt="Screen Shot 2021-04-08 at 8 37 03 am" src="https://user-images.githubusercontent.com/2975660/114027778-bc0bfe00-9845-11eb-9be4-238a2abfdfe2.png">

After second save, you get a proper link:

<img width="473" alt="Screen Shot 2021-04-08 at 8 37 08 am" src="https://user-images.githubusercontent.com/2975660/114027836-cf1ece00-9845-11eb-8844-098306df2d63.png">

**Comment by aapeliv** [comment]
This is a really tiny thing and doesn't matter much

**Comment by lucaslcode** [comment]
It's because of my crude html stripping, removes everything between <> that
isn't <br>

**Comment by aapeliv** [comment]
Is that just a backup solution/for aesthetics? If so, I'm happy to close this.

The markdown renderer does it's own cleaning too, right?

**Comment by lucaslcode** [comment]
Yes, it filters out xss-relevant stuff itself, but I thought it's better to avoid html altogether.
