### ISSUE TITLE
Investigate/set up Sentry on frontend

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1035]

**Comment by aapeliv** [comment]
This is done in the backend and needs to be done in the frontend.

Sentry basically adds hooks to error handling, then when an error happens, it takes the info, traceback, etc and ships it to Sentry. We can then look at the error logs and see what's going on and actually get some meaningful info. This should really help with the "Ooops... that's an unknown error"s, and give some insight into how often the app is crashing for users.

@darrenvong, @lucaslcode

**Comment by lucaslcode** [comment]
This is easy, just altering our error boundary component to use the one from [`@sentry/react`](https://docs.sentry.io/platforms/javascript/guides/react/)
