### ISSUE TITLE
[Bug][Backend] Can only mark host requests as seen by replying

### ISSUE THREAD

**Issue by ShmuelTreiger** [Couchers-org/couchers#1053]
Only way to mark a host request as "seen" is by replying. This is true for both the host and the guest. Ideally, just opening the request should update its status.

**Comment by aapeliv** [comment]
Does `MarkLastSeenHostRequest` work? If so, this is a frontend issue, I think?

**Comment by ShmuelTreiger** [comment]
It does. Not sure what I was thinking. Must have missed it.
