### ISSUE TITLE
Clarification on location randomization

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1065]
In the weekly social today, people have raised concerns that it's not clear what the circle represents. Some people seem to think we will randomize their location within the circle they place, and so they'll put the center at their house, which is bad.

**Comment by aapeliv** [comment]
@ItsiW.

What about writing something along the lines of "This circle will be visible to other users, we do not randomize it further. Please move the circle so that your location is not in the center of the circle but on the periphery." under both location selectors (signup and profile page).

Or then maybe having a dot for the search result?

**Comment by ItsiW** [comment]
"The circle should include your house. Please **do not** put your house in the center of the circle. This feature is to maintain user privacy when being displayed on the map"

**Comment by jesseallhands** [comment]
"Click and drag the circle below to show people the approximate location of your home. Make sure your home is not at the center of the circle, so people will not know the exact location."

**Comment by JGibbsWork** [comment]
This was just merged!

**Comment by kalvdans** [comment]
> This was just merged!

Great, closing! The PR was https://github.com/Couchers-org/couchers/pull/1456
