### ISSUE TITLE
Error boundary

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1082]
As per last frontend meeting, we should set up an error boundary for react so people don't just see blank white pages. It might be good to set up a separate error boundary for the map component? I'm not 100% sure how this all works though!

**Comment by thdk** [comment]
I can try to set this up, any special requirements?

**Comment by lucaslcode** [comment]
Maybe offer the options of either refreshing the page or going to the homepage.

**Comment by thdk** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/4201102/115160011-41897c80-a096-11eb-913f-a2f60ac6289e.png)

![image](https://user-images.githubusercontent.com/4201102/115159952-08e9a300-a096-11eb-8b67-1832ea6fa6e8.png)

**Comment by lucaslcode** [comment]
Great! I just think it should somehow be clearer to try refreshing first, before trying the homepage. And maybe error opens underneath the buttons?

**Comment by darrenvong** [comment]
Can we not show a stacktrace on the page at all? It's not very user friendly (even though it's hidden by default) and I rather not have it so readily available on the page. If we are concerned about losing information then we should look at setting up proper error reporting instead of this.

**Comment by lucaslcode** [comment]
Good point, and it will be meaningless minified stuff in production anyway

**Comment by justjooshing** [comment]
@thdk @lucaslcode @darrenvong 
Closing this because it looks done
