### ISSUE TITLE
Prettier should cause CI to fail if code contains formatting issues

### ISSUE THREAD

**Issue by thdk** [Couchers-org/couchers#1104]
When I run `yarn format` locally, it fixes files which I didn't touch myself.

Shouldn't CI pipeline fail for these formatting issues so they don't land on develop branch?

**Comment by lucaslcode** [comment]
Yes it's a good idea

**Comment by thdk** [comment]
What about changing the `build` script in `package.json` to:

`"build": "prettier --check src/ && eslint src/ && CI=true react-scripts build",`

**Comment by darrenvong** [comment]
`CI=true react-scripts build` already does the ESLint check as part of React scripts. Personally I'd prefer splitting these up into separate CI steps and run them in parallel so we can see clearly which parts fail, rather than keep chaining commands with `&&` which blocks you from seeing that as soon as one of them fails. It's a bit annoying to have to push multiple times especially they take some time to run...

**Comment by thdk** [comment]
@darrenvong 
You mean to add a job to the `.gitlab-ci.yml` file that checks if frontend is nicely formatted with prettier?
If so, I can try to add this job, but in which stage is this usually done? 

I would say the build stage since linting is currently done during build of frontend.
However, I can disable the linting done by cra react-scripts build so we can separate eslint and prettier from the build job.

Still I would like to ask if you want to add it to the build or test stage. And should I name the job as `build:frontend:prettier` and `build:frontend:lint` or more something like `format:frontend` and `lint:frontend` but still add it to the build stage?

**Comment by lucaslcode** [comment]
Test step seems more appropriate to me. Maybe call it test:frontend-lint and put eslint and tsc in there too instead of their current locations? (Tsc is done separately because of a CRA bug that doesn't check tests)

**Comment by thdk** [comment]
> Test step seems more appropriate to me. 

Its ok for me, but I usually try not to build anything that might contain formatting, or lint issues. But you can argue the opostite as well so... :) 
only disadvantage I see is that linting and formatting theoritically have no dependency on the build stage. Adding lint/format/tsc-tests to the test stage would mean these only start after the build stage has completed. Is that correct? 


> Maybe call it test:frontend-lint and put eslint and tsc in there too instead of their current locations? (Tsc is done separately because of a CRA bug that doesn't check tests)

Ill check tsc as well indeed, maybe change it though that it only runs for spec files.

**Comment by lucaslcode** [comment]
I was thinking that checks overall will still fail, but preview will work (it only depends on build) so reviewing will be easier. It's a bit inconvenient when you can't use the preview just because of incorrect import order, for example.

**Comment by thdk** [comment]
Ive commited an attempt to add a job to gitlab ci to run just the prettier check. 
Any thoughts?

First time working with gitlab, so hopefully it isn't too riduculous :baby:

**Comment by darrenvong** [comment]
> Its ok for me, but I usually try not to build anything that might contain formatting, or lint issues.

I would generally agree with that and so would probably prefer it in the build step. Maybe we should only fail the build on lint errors and not warnings?

Having said that, I think our lint rules are a bit relaxed and most things are warnings (including rules like `react-hooks/exhaustive-deps`, which I think should be an error unless we have a good reason to ignore), so maybe it's easier to go it as part of the test step instead... unless we also review our lint rules and make some of them error

**Comment by darrenvong** [comment]
> Ive commited an attempt to add a job to gitlab ci to run just the prettier check.

I think it's better to use the same image as frontend and the version of Prettier already installed in the dev dependencies, since Prettier are pretty aggressive at changing the formatting rules between even non-major versions, so using `npx` will likely introduce discrepancies from what we got installed locally.
