### ISSUE TITLE
Remove mutual friends from user API call

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1143]
I haven't benchmarked it, but I'm pretty sure the mutual friends join is one of the heaviest things in the API call that gets the user.

I think we should remove it from that RPC, and just have the frontend can grab mutual friends from the dedicated RPC when needed.

What do you think @lucaslcode and @ShmuelTreiger?

**Comment by ShmuelTreiger** [comment]
It depends on how prominently we want to feature mutual friends. For example, on facebook, that's one of the big things they show you with a random person. I'd argue it's much less relevant for couchers. However, I think this is a question for the frontend and design teams and how they want to use and display mutual friends vs the backend team.

**Comment by lucaslcode** [comment]
Definitely a separate call. I don't even think mutual friends is in the current design mockup, although it's a popular feature (but there was some debate about getting rid of friends)

**Comment by ShmuelTreiger** [comment]
So to be clear, what we're talking about is taking it out of the User message in the protbuffs. Several API calls return User, so this is a protobuff change more than an API change.
