### ISSUE TITLE
Return the number of the replies/comments in the discussion object in the API

### ISSUE THREAD

**Issue by darrenvong** [Couchers-org/couchers#1144]
![Screenshot 2021-04-26 at 03 10 49](https://user-images.githubusercontent.com/13669362/116154602-c6047c80-a6e0-11eb-9e19-90f3f50a5651.png)

In the design above, we want to show the number of replies a discussion has. This discussion card/component is used to in the discussions list page/tab.

Currently there is no way to get this information directly without an additional request to get the thread to figure this out, even when we don't need the rest of the thread's data at this stage.

Also, even if the additional request is not an issue, this is requiring the frontend to do more data wrangling than it should to figure this out, when I think it would be cleaner to do this in the backend instead. Apparently @kalvdans [agrees here](https://github.com/Couchers-org/couchers/pull/578#discussion_r573989349) so maybe this isn't a terrible idea 😉

**Comment by darrenvong** [comment]
Thought I should also write here to avoid things getting lost in Slack - after thinking about this a bit more recently, I think it's impossible to do the replies count accurately without this modification. Since `GetThread` is paginated, if there are ever more than one pages of replies (definitely possible for a popular discussion), we don't have a deterministic way to get the number of replies without having to loop through each page on the frontend until we hit the end (with a blank `page_token`).

I guess I'll leave this out on the frontend until this is done 😅

**Comment by kalvdans** [comment]
Backend is ready and reviewed in backend/feature/number-of-replies branch, to be picked up by the frontend team. closing bug!
