### ISSUE TITLE
Add large buttons for log in and sign up under the landing page text

### ISSUE THREAD

**Issue by ItsiW** [Couchers-org/couchers#1147]
On desktop, it's hard to access the log in and sign up buttons all the way on the top right. Before implementing the full design, can we replicate those with large buttons under the landing page text?

**Comment by justjooshing** [comment]
What do you mean it's hard to access? Because it's not immediately obvious?
Do you mean just these two or with About Us as well? I guess it looks a bit odd left up by itself
![image](https://user-images.githubusercontent.com/60824744/116446856-48ab4a00-a84f-11eb-966f-e355e7c3383b.png)

![image](https://user-images.githubusercontent.com/60824744/116447226-a6d82d00-a84f-11eb-82a8-71aae601d358.png)

**Comment by ItsiW** [comment]
It's not immediately obvious and slightly annoying to access. Option 1 is good, but I'd go even larger with the buttons and take up the full text width.

Trustroots duplicates them and that might not be a bad option 
![image](https://user-images.githubusercontent.com/39325627/116491973-7ab7bd00-a8de-11eb-8be5-60263fd46d1e.png)

**Comment by Neilblaze** [comment]
Assign me this please.

**Comment by lucaslcode** [comment]
Done, let me know if you have any questions!

**Comment by Neilblaze** [comment]
Yeah sure! Just wanted to know that since this is a monorepo, & I see two branches with `frontend`, so which branch has the primary frontend files via which I can get started?

**Comment by lucaslcode** [comment]
Create a branch off `develop` - the branch names just say what is being worked on in that branch. [More info here](https://github.com/Couchers-org/couchers/blob/develop/docs/contributing.md)

**Comment by aapeliv** [comment]
Hi @Neilblaze, how're you doing on this? This is relatively high priority

**Comment by Neilblaze** [comment]
> Hi @Neilblaze, how're you doing on this? This is relatively high priority

Apologies for the delay. I'm facing few errors in my local. The backend is running fine, but I'm getting few issues while doing `yarn start`. This is the log that I'm getting,

```
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "win32" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @material-ui/pickers@3.3.10" has unmet peer dependency "@date-io/core@^1.3.6".
warning " > @material-ui/pickers@3.3.10" has unmet peer dependency "prop-types@^15.6.0".
warning "maplibre-gl > @mapbox/mapbox-gl-supported@1.5.0" has unmet peer dependency "mapbox-gl@>=0.32.1 <2.0.0".
warning "@storybook/addon-actions > react-inspector@5.1.0" has incorrect peer dependency "react@^16.8.4".
warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".   
warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/addon-actions > @storybook/api > @reach/router > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > @storybook/addon-essentials@6.1.15" has unmet peer dependency "@babel/core@^7.9.6".
warning " > @storybook/addon-essentials@6.1.15" has unmet peer dependency "babel-loader@^8.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs@6.1.15" has unmet peer dependency "@babel/core@^7.11.5".
warning "@storybook/addon-essentials > @storybook/addon-docs@6.1.15" has unmet peer dependency "babel-loader@^8.0.0".
warning "@storybook/react > @babel/preset-react@7.12.10" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/ui > react-helmet-async@1.0.7" has incorrect peer dependency "react@^16.6.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/ui > react-helmet-async@1.0.7" has incorrect peer dependency "react-dom@^16.6.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/ui > react-sizeme@2.6.12" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0".
Starting the development server...
Failed to compile.
```

Any ideas on how to resolve this?

**Comment by aapeliv** [comment]
Did you do this in the react snap pr @lucaslcode ?

**Comment by lucaslcode** [comment]
It's been since for ages
