### ISSUE TITLE
Replace fake Terms of Service  on signup with actual

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#1156]
@ItsiW has text for ToS. It's long - we should change sign-up to just be a link and checkbox rather than the full ToS inline.

**Comment by aapeliv** [comment]
How're you doing with this @Jesus82?

We're waiting for this at #1170 to make a backend change.

**Comment by Jesus82** [comment]
Hi @aapeliv I had to left it half way and had a few busy days. I will try to push this today or tomorrow, sorry for the delay!

**Comment by aapeliv** [comment]
@Jesus82: thanks. I've discussed with @kalvdans, we will add an API call where you can fetch the Markdown content of the current ToS. If you come to the frontend meeting, I'll explain!

**Comment by Jesus82** [comment]
@aapeliv  I will then place for now a "mock" link and push the commit with the checkbox replacing the button.

**Comment by aapeliv** [comment]
Sure. The frontend should have a page, that when you open it, does an RPC request that grabs the latest ToS markdown and renders it on that page.
