### ISSUE TITLE
gRPC interceptors don't work with gRPC-Web Devtools

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1204]
This means that the unathenticated error handler doesn't run correctly, so for example you won't be kicked out if the backend suddenly jails your or logs you out (e.g. due to ToS version updating).

This works correctly in the prod build though because we disable the dev tools there.

See also https://github.com/grpc/grpc-web/issues/1012 and https://github.com/SafetyCulture/grpc-web-devtools/issues/80

**Comment by darrenvong** [comment]
Not sure what else we can do here since this is code we didn't write and it's not affecting prod at least...

**Comment by aapeliv** [comment]
Yes, just documenting it here...
