### ISSUE TITLE
Investigate: asyncio and real-time notifications

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#127]
Here's something I've been toying with. It's very exploratory and we shouldn't spend time on it just now.

One of the key strengths of gRPC is that it supports bi-directional streaming. With the web it's a lot harder due to constraints with how little you control the network stack. Nonetheless, what we're using; gRPC-Web does support streaming from the server to the client. So the client makes a request, then the connection is kept open and the server can stream small chunks of data as it sees fit.

This would be perfect for sending out real-time notifications to the web app. Otherwise we have to keep hammering the API with calls every few seconds to check if there's something new going on that the frontend should care about.

One issue is that we'd then keep one connection per client, if we stream. And that means that we'll need to keep track of that somehow in the backend, which incurs resource costs. We could first try just what we've got now, but it probably can't support very many clients simultaneously as it requires one thread per client. The new, fancy way of doing that is using `asyncio` which uses coroutines, and so is much lighter on the backend per client. gRPC Python has experimental support for asyncio (in `grpc.aio`, I think). That might be a way to go about it.

We should also investigate asyncio for the whole stack; it seems it's lighter and faster overall. However, support in gRPC is experimental as of now, so we probably don't want to get married to it before we see some numbers, etc, and have a stable API.

**Comment by lucaslcode** [comment]
Closed in favour of #557
