### ISSUE TITLE
Donation page

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1270]

**Comment by BoyanLiuu** [comment]
I would like to work on this page, Am I using this Figma design for the donation page? 
![image](https://user-images.githubusercontent.com/45325025/119917227-21ba6380-bf34-11eb-97c6-76a1dafb571f.png)

**Comment by aapeliv** [comment]
@BoyanLiuu sure! I had a brief chat about it with @darrenvong, but I think he's working on something else, so you're more than welcome to work on this.

Also, the text is not yet finalized, but I'll follow up with @ItsiW to sort that out in the next couple of days!

**Comment by darrenvong** [comment]
Yeah I won't have a lot of time probably until next week, so feel free to go for it! It should be a nice piece of work to get started for learning about the main libraries we use on the frontend

**Comment by aapeliv** [comment]
Closed in #1553
