### ISSUE TITLE
Add some way to ask whether people actually met up

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1305]
E.g. in the reference soliciting email a button that says "I didn't stay with Aapeli", etc or similar. Also needs to be in the UI somewhere in the references view.

**Comment by ShmuelTreiger** [comment]
Let's say the user clicks "I didn't stay with Aapeli". Then what? Do we want a debrief of why not? Are we going to have a "cancelled meetup" references section? Or should it just load a page "Too bad, there's always next time. Click here to search for your next trip."?

**Comment by aapeliv** [comment]
Dupe of #3531
