### ISSUE TITLE
Add more info to traces

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1312]
* IP address
* User agent
* What else?

These are verbose, so I originally didn't want to include them because they just add a lot of extra bytes. But I think we should do it. As we later move to storing the traces in a more appropriate place, we can then also make sure they're compressed properly in which case the extra bytes are not an issue. (I did some testing earlier: dumping the traces as length-prefixed, serialized protobufs in a file and then compressing with zstd gives like a compression ratio of 95%+).

**Comment by faizjamil** [comment]
I'm willing to work on this, however I need a lot more information. How are the traces outputted, to a console or some other place? Where in the code should I be looking for this? And are we talking about the IP address and user agent of a typical user?

**Comment by aapeliv** [comment]
The traces are stored in the database (different schema though). It's in an interceptor somewhere like `couchers/interceptors.py`.

The IP address and user agent need to come from headers.

**Comment by aapeliv** [comment]
Done
