### ISSUE TITLE
Community tab

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#1318]
Until we have the dashboard, a simple community tab with links to your current community and a list of all communities

**Comment by aapeliv** [comment]
I'm modifying `ListCommunities` to return a list of all communities if not given a parent community ID.

**Comment by aapeliv** [comment]
> links to your current community

A user can have multiple communities, so this should be a list as well. Sorry, that's my bad for saying otherwise earlier.

**Comment by thdk** [comment]
This tab would need to be added to the user/profile page?

**Comment by aapeliv** [comment]
No, just as a tab in the navbar, next to "Dashboard", "messages", etc

**Comment by thdk** [comment]
Just one more question to make this clear for new contributors:

So in the nav bar we get something like: (?)

```
Dashboard
Messages
Communities
- my current community
- my other community 1
- my other community b
Profile
```

**Comment by aapeliv** [comment]
I think Communities should just be a "communities landing page", and the page content is those lists so they're not in the navbar.

It's just a quick and dirty way to discover communities for now: we'll definitely change it as we go, but we need some page to just list all the communities so people can discover them and get to their pages.

**Comment by thdk** [comment]
Ok, I can have a look at this one then. I'll not assign myself yet until I effectively start working on this issue.

So if anyone is faster, feel free! :)

**Comment by lucaslcode** [comment]
Sorry I started before I saw your comment and also I didn't do what Aapeli said :P
