### ISSUE TITLE
Text about log in link is not easy to see

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1321]
We've got a user report that the text that pops up when you get emailed a log in link is not easy to see, and that the greyed out "Continue" button causes extra confusion.

Maybe we could move the text to replace the continue button and hide the button: so it would appear right where the user is looking at after they press the button?

**Comment by dommers-ux** [comment]
That's a great recommendation! Once the user selects "Continue", some sort of instructional text follow-up would clarify what to do next.

**Comment by aapeliv** [comment]
This is the current flow, which is not so clear:

Before clickign continue:

<img width="524" alt="Screen Shot 2021-05-29 at 8 41 46 pm" src="https://user-images.githubusercontent.com/2975660/120088420-535f3600-c0be-11eb-88d3-44efd75f7712.png">

After:

<img width="519" alt="Screen Shot 2021-05-29 at 8 41 51 pm" src="https://user-images.githubusercontent.com/2975660/120088421-54906300-c0be-11eb-9877-18ce33e9a6db.png">

**Comment by dommers-ux** [comment]
An alternative would be to have the instructional text below the button to begin with. For example: 

<img width="416" alt="Screen Shot 2021-05-29 at 8 52 13 PM" src="https://user-images.githubusercontent.com/83376913/120088562-e351af80-c0bf-11eb-99bc-c282523de4a1.png">

**Comment by dommers-ux** [comment]
An alternative would be to have the instructional text below the button to begin with. For example:

<img width="412" alt="Screen Shot 2021-05-29 at 8 55 21 PM" src="https://user-images.githubusercontent.com/83376913/120088593-39beee00-c0c0-11eb-8c3a-8e2fc4398bf2.png">

**Comment by aapeliv** [comment]
We don't know yet at that point if the user will get an email. When you click Continue it goes to the backend and checks if the user has a password or not: if no password it'll email, otherwise it shows up a password box!

**Comment by aapeliv** [comment]
I think this was fixed, and we're deprecating passwords anyway
