### ISSUE TITLE
Refactor tasks.py

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1338]
There are all these `send_*_email` functions in `tasks.py` that take a token and expiry text that are generated in another function. The expiry durations should also just be in constants and not be passed in at the call site. I think these should just be merged: and because we don't actually use the expiry text, we should just get rid of it.

**Comment by lennartvanlaake** [comment]
I get that we can remove the unused `expiry_text` param but I am not sure what you would have in mind for the rest of this refactor. For now I am unassiging myself to it, looks like something that has less priority than some of the other issues and probably better if someone with a clearer idea on what should be done does this.

**Comment by ShmuelTreiger** [comment]
I'm similarly confused in the exact same manner as lennartvanlaake
