### ISSUE TITLE
More robust check for unedited "default" profile fields

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#1356]
I noticed some people have the blank defaults in their profile. Not sure why.

**Comment by aapeliv** [comment]
You mean the default headings for "about me", etc?

**Comment by lucaslcode** [comment]
Yes, for example, the user "tomato"

**Comment by aapeliv** [comment]
As I now browse through new users, it seems there's a *lot* of users now with the default headings.

This also stops them from getting the "please complete your profile" email!

**Comment by lucaslcode** [comment]
~~This is difficult to reproduce consistently... ~~
Scratch that, just clear your profile, edit again, and save without changing anything
