### ISSUE TITLE
Add testing for each constraint in the models

### ISSUE THREAD

**Issue by ShmuelTreiger** [Couchers-org/couchers#1393]
Add tests to test_models.py which check that each constraint is being followed.

Important, for example, because I discovered that my restraints weren't being picked up due to two separate \_\_table_args\_\_ in the same model.

**Comment by austinburnett** [comment]
Hey @ShmuelTreiger can I work on this issue? I'm new to open source

**Comment by ShmuelTreiger** [comment]
Double check if @aapeliv has anything to add, but yes! Go for it! 

Welcome! Always looking for new contributors :)

**Comment by aapeliv** [comment]
Hi @austinburnett, yes, you're welcome to work on this issue. I'm not sure if it's the most friendly issue to start off with, but you should be fine.

I'll also email you in a bit.

**Comment by aapeliv** [comment]
This is fine for now
