### ISSUE TITLE
Search Bar Width 

### ISSUE THREAD

**Issue by dommers-ux** [Couchers-org/couchers#1398]
The search bar should be extended to fit the column. 

Before: 
--------
<img width="461" alt="Screen Shot 2021-06-08 at 1 55 35 AM" src="https://user-images.githubusercontent.com/83376913/121413661-e6f0fc00-c933-11eb-8d2f-d8e47c8f5fed.png">

After: 
-------
<img width="379" alt="Screen Shot 2021-06-08 at 2 02 47 AM" src="https://user-images.githubusercontent.com/83376913/121413702-f5d7ae80-c933-11eb-92e8-27fe13fac557.png">

**Comment by lucaslcode** [comment]
This is already closed in #1332
