### ISSUE TITLE
Search is too broad

### ISSUE THREAD

**Issue by ShmuelTreiger** [Couchers-org/couchers#1409]
So I was playing around with the website and I searched for "john" because I wanted to see the map adjust to the global view (super cool feature). The third hit was a woman named "Cate". Long story short, in her "home" section, she lives with her partner "John". Seems like a bug to me, that searching for "john" gets me "cate".

Maybe the eventual solution is just more advanced search (i.e. name="john", location="USA", etc.) so that you don't pick up names from the profile content?

Still, thought I should document and see if anyone agrees or I'm all alone.

**Comment by lucaslcode** [comment]
This is intentional - I thought people are unlikely to search by name directly, so I included the whole profile by default. 

But you're right it's a bit confusing, someone else reported the same bug

**Comment by ShmuelTreiger** [comment]
I could see it being most relevant if you're looking for a friend. It doesn't really impact your search (hence low priority), but it def struck me as weird.

**Comment by ShmuelTreiger** [comment]
Continued Couchers-org/couchers#4208
