### ISSUE TITLE
CORS errors with accept-language header

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#1452]
To reproduce in Chrome
- Dev sidebar
- 3 dots menu
- More tools
- Sensors
- Location: Moscow

**Comment by lucaslcode** [comment]
Changed priority to low, i don't think it's a usual header

**Comment by aapeliv** [comment]
@lucaslcode: this might be as simple as adding `accept-language` into `envoy.yaml` in the `allow_headers` line. Are you able to try that out? It's a complicated bug to reproduce!

**Comment by darrenvong** [comment]
> @lucaslcode: this might be as simple as adding `accept-language` into `envoy.yaml` in the `allow_headers` line. Are you able to try that out? It's a complicated bug to reproduce!

Adding that has fixed it for me when testing the date picker timezone fix so maybe that's all it takes to fix this?

**Comment by aapeliv** [comment]
If this reoccurs, reopen.
