### ISSUE TITLE
Add Open Town Hall to dashboard

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1457]
The first one is in a week; so would be good to have it up by then.

I imagine it should either be a new section or change the "weekly online events" to accommodate this monthly one.

Details on forum: https://community.couchers.org/t/open-town-hall/1291

**Comment by dommers-ux** [comment]
i think a new one would suit better.
one for "Open Town Hall" and another for "Weekly Social Events"

**Comment by dommers-ux** [comment]
here is a suggestion for tags to make each drop-down more informative/descriptive, as well as make new things (such as Open Town Hall) or updates pop-out 

<img width="437" alt="Screen Shot 2021-06-20 at 11 54 04 PM" src="https://user-images.githubusercontent.com/83376913/123167401-162b6100-d43c-11eb-9ca9-1d79db2028ee.png">
