### ISSUE TITLE
Search queries stacked in the URL

### ISSUE THREAD

**Issue by ShmuelTreiger** [Couchers-org/couchers#1466]
I was playing around with the search function. I'm not entirely sure how (or how to reproduce), but I got my queries to stack somehow in the URL. Predictably, this lead to no results.

![Query stack](https://user-images.githubusercontent.com/14131043/122699524-6917d500-d1fe-11eb-976f-5c8cb1e2725d.png)

**Comment by lucaslcode** [comment]
This looks correct, one is location and one is query. Confusing UX is already tracked
