### ISSUE TITLE
The figure background is missing in `docs/architecture.md`

### ISSUE THREAD

**Issue by sadikekin** [Couchers-org/couchers#1477]
I am using Github in dark mode. So, for me understanding the figure was a bit hard. I think we can change the background of the image.

This is how I see the document.

<img width="1030" alt="Screenshot 2021-06-22 at 20 38 11" src="https://user-images.githubusercontent.com/25348720/122981638-43273780-d39a-11eb-999c-6e60a15cda28.png">

**Comment by aapeliv** [comment]
Can this be fixed with some HTML in the markdown doc? Or we could re-export the drawio diagram with a white background

**Comment by sadikekin** [comment]
I tried to solve this issue by simply editing the image. However, I think my photoshop knowledge is not sufficient enough. I don't know about the HTML. If you have the drawio base document, I think just simply re-exporting might be the easiest solution.

**Comment by aapeliv** [comment]
Could you do that and open a PR? The drawio source is in the same folder

**Comment by sadikekin** [comment]
I changed the file. However, I think I don't have push access. When I try to push the codebase to the new branch that I have created, I get the following error.

```
ERROR: Permission to Couchers-org/couchers.git denied to sadikekin.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by aapeliv** [comment]
You can fork the repo and make a PR from your fork into this repo!

**Comment by aapeliv** [comment]
Also, could you email me at aapeli @ our domain, please? It'd be good to have a quick chat and have you join the developer meeting tomorrow if you're keen to help out! Then we can give you write access to the repo.
