### ISSUE TITLE
The local development setup - Postgres Error - UndefinedObject

### ISSUE THREAD

**Issue by sadikekin** [Couchers-org/couchers#1478]
I am following the `app/readme.md` document to set up this application on my local computer to do some development on it. However, in the `Launch the backend with docker-compose` part, I got the following error. (I use Macbook)

`sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) type geometry`

I managed to solve the issue by applying the following steps.

1 - Manually get the CLI of the `app_postgres_1` from Docker.
2 - Run `psql postgres -c "CREATE EXTENSION postgis" -U postgres` command.

I think this `postgis` extension is missing initially.  This is a quick fix. I think this is not a good solution overall. The error shouldn't happen in the first place.

**Comment by aapeliv** [comment]
That container should include the postgis extension, it's the postgis container!

Are you sure you didn't wipe the database or something before this?

It might also be that we do something funky there. Worth double checking.

**Comment by sadikekin** [comment]
I can not reproduce the error after my fix. I just wanted to open this issue to help others if they get the same error.

**Comment by aapeliv** [comment]
Not reproducible and we always help fix local dev env issues bespoke
