### ISSUE TITLE
Message / Text Input Box Size 

### ISSUE THREAD

**Issue by dommers-ux** [Couchers-org/couchers#1481]
The message input box should be the same size as the button. 

Now: 
<img width="228" alt="Screen Shot 2021-06-22 at 5 11 20 PM" src="https://user-images.githubusercontent.com/83376913/123006526-6bed0400-d37d-11eb-8f60-ec7bdd3bed2e.png">

New: 
<img width="278" alt="Screen Shot 2021-06-22 at 5 13 23 PM" src="https://user-images.githubusercontent.com/83376913/123006561-7ad3b680-d37d-11eb-90f8-5de58ffe94ed.png">

**Comment by lucaslcode** [comment]
Doesn't this imply very short messages?

**Comment by dommers-ux** [comment]
Not necessarily. It's just general UX to have the input fields the same size as the button for optimal scanning and symmetry. 

For things like discussions, it's a little different (input fields may be larger but the action button is placed below the box, like GitHub). 

If you look at any platform with messaging, they're all consistently the same size. Otherwise, it looks a little wonky.

**Comment by jesseallhands** [comment]
@dommers-ux This probably works for short text entry like on profiles, but would be terrible ux for messaging/requests/large-field profile editing. Could we use single-line like you proposed for short-field text entry (eg: occupation, education, custom pronouns, etc on profile) and a bigger box for text entry on large-fields (about me/messaging/requests)?

Alternatively, we could have the text entry box expand when clicking on it so it gets bigger, and after you click "send" it reverts to the small size again. I suspect that might require a custom component and might be a little complex for now

**Comment by dommers-ux** [comment]
@AllhandsNofeet
I disagree. Single line entries are common for messaging everywhere (Slack, Facebook, AirBnB). It also works better for mobile messaging. 

I understand the need for large entry for requests, but for a quick chat asking a user for advice about traveling to a place (e.g. Hey! I'm heading to Madison, WI this weekend - How's the COVID situation?), it would be ideal to keep the single line entry. What do you think? I think it's dependent on the use case (Message vs. Request).

Platforms like Facebook and AirBnB allow for easy, quick communication (single line entry, pressing "Enter" or "Return" on your keyboard sends the message). Platforms like Vrbo treat messaging like a request (large entry fields and button placed below the field; pressing Enter or Return creates a new line).

**Comment by jesseallhands** [comment]
@dommers-ux I think we're actually in agreement. I just tested out the various platforms and they all start out one line but are responsive and expand as you type (for example if the message gets longer):
**Before:**
![image](https://user-images.githubusercontent.com/79384268/123011954-0140c600-d387-11eb-83c4-0e0da9a9e25e.png)
**After:**
![image](https://user-images.githubusercontent.com/79384268/123011671-7c55ac80-d386-11eb-9eb0-10f7a02227df.png)

@lucaslcode With the components we already have, are we able to do what Dom is saying and have text boxes start as a single line and have them expand responsively if the user types in text that exceeds the length of the text box (like in the example screenshots above)?

**Comment by lucaslcode** [comment]
Not trivial but doable

**Comment by jesseallhands** [comment]
Looks like the text fields are differentiated here if we're using material.ui :

https://material.io/components/text-fields#input-types

- **Single line text fields** display only one line of text
- **Multi-line text fields** grow to accommodate multiple lines of text
- **Text areas** are fixed-height fields

One scrolls horizontally (makes sense for the single-line inputs like education/occupation/custom pronouns/etc) and one expands vertically (About me/messaging/requests/etc)

I think right now in some cases we are using _Text areas_ instead of  _Single line text fields_ and _Multi-line text fields_

**Comment by lucaslcode** [comment]
Moved to Couchers-org/couchers#4196

**Comment by lucaslcode** [comment]
https://v4.mui.com/components/text-fields/#multiline

The above discussion TL;DR is we would indeed like to implement a single line field that grows to multiple lines for long messages (see above mui component). Although we want to encourage long host requests, they are written on the profile page, not here.

**Comment by tsuruby** [comment]
Sounds great, I would like to do this @lucaslcode

**Comment by tsuruby** [comment]
Hi @lucaslcode,  I was on vacation and will start this evening with this task.
