### ISSUE TITLE
The communities popup only shows onne page

### ISSUE THREAD

**Issue by sadikekin** [Couchers-org/couchers#1487]
When the user clicks the browse all communities section, the front end only displays one page of the communities if the pagination size is smaller than the total community size.

<img width="1255" alt="Screenshot 2021-06-23 at 21 48 54" src="https://user-images.githubusercontent.com/25348720/123165556-ae453c80-d474-11eb-9cbe-e60ab7d2cc16.png">

**Comment by lucaslcode** [comment]
I was wrong sorry - it is correctly paginated. I get a load more button if I set `pageSize` to a low number in the frontend request.
