### ISSUE TITLE
Breadcrumb Menu Navigation Clarification 

### ISSUE THREAD

**Issue by dommers-ux** [Couchers-org/couchers#1523]
The current design for the breadcrumb navigation shows each community and sub-community as one color (teal). 
To clarify which page the user is on, only the present community should be highlighted. For example...

Before: 
---------
<img width="412" alt="Screen Shot 2021-06-27 at 7 36 07 PM" src="https://user-images.githubusercontent.com/83376913/123564405-fd45e700-d77e-11eb-8156-ca9c3199d0b7.png">

After:
----------
<img width="448" alt="Screen Shot 2021-06-27 at 7 37 36 PM" src="https://user-images.githubusercontent.com/83376913/123564447-25cde100-d77f-11eb-8f3a-a9e0c2d6dc9b.png">

(Note: each "breadcrumb" (in this case, each community) should still act like a link)

**Comment by lucaslcode** [comment]
How about I make the last one bold instead? If the other breadcrumbs are black, they don't look clickable.

**Comment by dommers-ux** [comment]
That makes sense. I did some research and I like the way this looks: 
<img width="340" alt="Screen Shot 2021-06-30 at 10 47 27 AM" src="https://user-images.githubusercontent.com/83376913/123991839-aca5d800-d990-11eb-91d5-e73653a1a396.png">

That way it differentiates between the current page and the previous pages (and the current page is not clickable because the user is already on it). 

I think bold will work for now though if you've already worked on it.

**Comment by dommers-ux** [comment]
Here is a helpful article about breadcrumbs - https://www.nngroup.com/articles/breadcrumbs/
