### ISSUE TITLE
Reference Tag Colors [UX]

### ISSUE THREAD

**Issue by dommers-ux** [Couchers-org/couchers#1524]
On the users' references page, the tags should be a neutral color for optimal information hierarchy. The colored tag creates an unnecessary pop-out effect even though the tags naturally pop out. 

Before
-------
<img width="546" alt="Screen Shot 2021-06-27 at 9 34 08 PM" src="https://user-images.githubusercontent.com/83376913/123571258-74837700-d78f-11eb-90a0-690e3c793b63.png">

After
-----
<img width="545" alt="Screen Shot 2021-06-27 at 9 34 13 PM" src="https://user-images.githubusercontent.com/83376913/123571292-85cc8380-d78f-11eb-825d-544414ac720f.png">

_Corner Radius: 4px
Fill: Light Gray (E9E9E9)
Text: Ubuntu / Bold / 12
Text Color: Almost Black (27282C)_

**Comment by AlexVCS** [comment]
Hi, I'd like to work on this issue!

**Comment by lucaslcode** [comment]
Let me know here or via email if you have any questions!

**Comment by AlexVCS** [comment]
I was about to dive into working on this but am seeing it requires Docker. My machine (late 2009 iMac running macOS 10.11.6) is old and incapable of running Docker. Is there any workaround for this? I'm looking into it and hoping to find a way.

**Comment by aapeliv** [comment]
Yes, you can run the frontend locally without docker by pointing it to the test instance at https://next.couchershq.org/. Just install the dependencies (with `yarn`) then

```
REACT_APP_API_BASE_URL="https://dev-api.couchershq.org" yarn start
```

**Comment by AlexVCS** [comment]
thank you!

**Comment by AlexVCS** [comment]
Every time I try to install the dependencies I get this error: **Unexpected end of JSON input**. I navigated to the app and frontend subfolders. I tried removing the package.json in my home directory as I read that could be what's causing this to occur. Any ideas on how to get yarn working past this?

**Comment by aapeliv** [comment]
Could you post the full error message?

**Comment by AlexVCS** [comment]
error An unexpected error occurred: "/Users/alex/Desktop/Projects/package.json: Unexpected end of JSON input".
info If you think this is a bug, please open a bug report with the information provided in "/Users/alex/Desktop/Projects/couchers/app/frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by AlexVCS** [comment]
Ok maybe I need to delete the file in that directory that is a package.json!

**Comment by AlexVCS** [comment]
Fixed!

**Comment by AlexVCS** [comment]
Thanks

**Comment by AlexVCS** [comment]
When I ran the app with command you mentioned earlier I got this error:
Failed to compile.

./src/AppRoutes.tsx
Module not found: Can't resolve './proto/pages_pb' in '/Users/alex/Desktop/Projects/couchers/app/frontend/src'

**Comment by lucaslcode** [comment]
You need to generate the API code. The easiest way is to download the generated code from our CI pipelines. There are instructions here: https://github.com/Couchers-org/couchers/tree/develop/app/frontend#option-2-target-the-preview-api-and-backend

**Comment by AlexVCS** [comment]
I've looked at the codebase and some of the docs but am not totally sure where the changes need to be made. I found the right fill color already listed in theme.ts. I also see the ReferencesView.tsx file. How can I pull up a users' references page on a local copy of the project? I login with my account but it never works unless I use the actual site.

**Comment by AlexVCS** [comment]
Looking some more it seems like the changes need to happen in ReferenceListItem.tsx. Does anyone have any tips for me? Thanks in advance.

**Comment by lucaslcode** [comment]
Use react dev tools in the browser to find the exact component if you're having trouble, then go through the render function to see how it works and what determines the colour of the label. It might be a prop on a Material-UI component, or it might be some jss styling which is defined near the top of each file.

**Comment by AlexVCS** [comment]
Ok, I did that but only on the actual website, not in my local version of the app (each time I try to login it says couldn't find that user). Not sure if local or production version makes a difference, does it? I found the component and was able to change it from within dev tools, but not sure where to target that in the codebase. I couldn't find the render function, could you expand on what you mean by that? I included a screenshot of React dev tools for the component.

![Screen Shot 2021-08-29 at 9 53 36 PM](https://user-images.githubusercontent.com/49458917/131274705-3c2551a9-7edd-4625-81e4-efacee6a3587.png)

**Comment by lucaslcode** [comment]
If you're using the local version with docker, sign-up and login emails are
printed in the backend container logs. You can also use the user "aapeli"
with password "Aapeli's password"

**Comment by AlexVCS** [comment]
I cannot run Docker on my machine due to its age (maybe it could work through virtualization I'm not sure). I generated my API code to run the frontend. I tried the login you provided and no dice probably because it's not used with Docker. Is there a way to login without Docker?

**Comment by lucaslcode** [comment]
I see! In that case you can target the live development api server instead of the local server by running `REACT_APP_API_BASE_URL=https://dev-api.couchershq.org yarn start` instead of `yarn start`. You can sign up with an account and real emails will be sent - but the links in the emails will be something like https://next.couchershq.org/login/ABCDE123 which you obviously need to change to http://localhost:3000/login/ABCDE123

**Comment by AlexVCS** [comment]
Thanks, I've been using that command but didn't understand about changing the links when signing up. I'm on my account with the local server but can't find a user with references. I've sent friend requests in hopes of being able to leave references and get a better sense of where I need to make changes. Am I missing something here? I've looked at the docs to try and see if there's a way to remedy this but can't find a solution.

**Comment by lucaslcode** [comment]
Aapeli has some references: https://next.couchershq.org/user/aapeli/references

Or http://localhost:3000/user/aapeli/references

**Comment by AlexVCS** [comment]
I have made changes I'd like to push to my own branch. When I push in my terminal I get this message:
```
git push origin frontend/refactor/reference-tag-colors
remote: Permission to Couchers-org/couchers.git denied to AlexVCS.
fatal: unable to access 'https://github.com/Couchers-org/couchers.git/': The requested URL returned error: 403
```
If you know the way to get past this (I'm trying different ways) please let me know :)

**Comment by AlexVCS** [comment]
Pretty sure I figured this one out!

**Comment by AlexVCS** [comment]
I have been trying to clean up the merge conflict but am stuck. I tried to pull down changes, rebase and search for what could be a good step for solving the issues. Here's my repo if you've got any advice for how to remove the conflicts (see the screenshot for conflicted files). https://github.com/AlexVCS/couchers/tree/frontend/refactor/reference-tag-colors/app
![Screen Shot 2021-09-14 at 11 53 47 AM](https://user-images.githubusercontent.com/49458917/133295729-7c7d976b-910d-4bbe-9368-78b89614012f.png)

**Comment by lucaslcode** [comment]
Sorry! We just moved everything that was in `app/frontend` to `app/web`. Probably the easiest thing would be to apply your changes on a new branch.

Or if that part is fine, just delete the whole frontend folder.
