### ISSUE TITLE
Markdown/input sanitisation

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#153]
Need to investigate sanitisation of user inputs.

Markdown should be supported, but we should check which features we support. E.g. we shouldn't load external images put in markdown descriptions (people could do things like add a tracking pixel that points to their site and see who's looking at their profile).

Also, I'm not sure if we do any sanitisation for general XSS/HTML in other fields. SQLAlchemy does fix SQL injection though, I believe.

**Comment by lucaslcode** [comment]
Closing, react frontend uses markdown-it which sanitizes by default, and there are no uses of `dangerouslySetInnerHTML` except the markdown component.
