### ISSUE TITLE
List of friend requests should appear at top of screen on mobile

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1568]
You should immediately be able to see the list of pending friend requests at the top of the screen when you view the messages page.

Currently on the mobile version the list of friend requests is located below the list of current friends. This forces the user to scroll down all the way down through the list of existing friends before you can see who sent you a friend request. If you have a lot of friends, this requires a lot of scrolling and is not user-friendly. See example below:

![image](https://user-images.githubusercontent.com/79384268/124399030-865ca100-dcde-11eb-9948-b93809fd9ad0.png)

On mobile, the "Friend requests" container with pending friend requests should be moved to the top above the container with the list of existing friends. On desktop, the "Friend requests" container with pending friend requests should be moved to the left of the container with the list of existing friends.

**Comment by CamArturo** [comment]
@aapeliv @AllhandsNoFeet Can one of yall send me a friends request so that I can play with this? and Hi!

**Comment by lucaslcode** [comment]
@CamArturo you can use the staging server and make yourself some test accounts: next dot couchershq org
