### ISSUE TITLE
i18n/l10n: Evaluate tools and libraries

### ISSUE THREAD

**Issue by openscript** [Couchers-org/couchers#1577]
Localizing and translating a platform mostly involves its user interfaces, but we also need a tool, which helps us to do it together with the community. As the backend engages with the users too (emails), we also need to provide the users locale to the backend and have i18n/l10n functionality there. 

## Requirements

-  Free and opensource
-  Well-known, proved and stable
-  Handling different languages (RTL, UTF-8, ..)
-  Handling displaying time and date
-  Handling grammatical numbering (singular, plural, ...)
-  Handling meta and context information per translation (e.g. button to submit the registration form, ...)

## Proposal

The following is an opinionated list of candidates:

### i18next (react-i18next), Weblate

i18next hasn't been around as long as Format.JS, but cannot be called a new player either. It integrates well with Weblate, as it supports i18nexts specific translation format.

### Format.JS (react-intl), Weblate

Format.JS or react-intl has been around for a while. Also Weblate manifested as a standard for translation platforms.

### Fluent, Pontoon

Mozilla created a whole new solution for i18n/l10n called Fluent, which also integrates well with Pontoon a web platform for translating.

### UI libraries

![image](https://user-images.githubusercontent.com/1105080/124604168-f7c95a80-de6a-11eb-8891-4edef6793f4f.png)
https://www.npmtrends.com/fluent-react-vs-react-i18next-vs-react-intl-vs-@lingui/react

![image](https://user-images.githubusercontent.com/1105080/124604215-031c8600-de6b-11eb-83e2-0dd97481ac7a.png)
https://npmcompare.com/compare/@fluent/react,@lingui/react,react-i18next,react-intl

**Comment by ShmuelTreiger** [comment]
The Y column for the first image is downloads?

**Comment by openscript** [comment]
@ShmuelTreiger Yes

**Comment by alesdvorakcz** [comment]
I am using (react-)i18next with weblate and I am quite happy with it. I am happy to help with it if needed

**Comment by comradekingu** [comment]
@openscript I won't fill in the Google form, but I can help set up Weblate.
Pontoon unfortunately copied the design of Crowdin.
Also happy to provide a nb_NO translation.

**Comment by lucaslcode** [comment]
Couchers-org/couchers#4152
