### ISSUE TITLE
Cookie notice

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#1591]

**Comment by dommers-ux** [comment]
not sure if it's been mentioned but UX team has designs for a cookie notice

**Comment by dommers-ux** [comment]
here's an example of the app.couchers.org landing dashboard 

<img width="633" alt="Screen Shot 2021-07-25 at 5 20 11 PM" src="https://user-images.githubusercontent.com/83376913/126916575-2abb2dc3-ed89-4ce1-be60-00d7ad8a3731.png">

**Comment by lucaslcode** [comment]
Closed in #1808
