### ISSUE TITLE
Add form to report content next to bug reporting form

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1592]
Currently to report anything other than a person's profile (via their profile), you must click on "report a problem", click on "report inappropriate behavior or content" and then compose an e-mail manually, from scratch. See screenshot below:
![image](https://user-images.githubusercontent.com/79384268/124830673-e0a86c80-df3f-11eb-937e-46b7483624a8.png)

People are already hesitant and/or lazy to report things, so setting the bar that high to report things means that a lot will go unreported. To lessen the barrier, we should create a simple form that collects data to send to notify@couchers.org for review. 

So when a user clicks on "report inappropriate behavior or content" they will see a form similar to the one on the profile page. The form should contain 3 fields:

1. Person being reported (if applicable)
2. Reason
3. Description

When the form is sent to notify@couchers.org it should have the subject "Report sent by: [USERNAME]" and should also include the following metadata in the body of the e-mail:
1. Username of person reporting
2. E-mail of person reporting
3. The page where the report was sent from

The header above the field should say "Report inappropriate behavior or content"
The text above the field should say "Please provide us with detailed information about what you are reporting and why. This report will be kept private. Thank you for helping make the community a better place!"

Eventually we will want to make most content flag-able so that when the person clicks the flag this form will be displayed and our system can capture the specific content being reported (rather than rely on the user to provide a description of where the content was and what it is).

**Comment by ShmuelTreiger** [comment]
@Couchers-org/backend is there any backend work that needs doing here? Do we want to save all report data in the backend? On the one hand, seems like it could be a lot of data. On the other, might be worth keeping?

**Comment by jesseallhands** [comment]
Might be worth storing the number of times a user is reported in the DB so in the future we can use an algorithm to easily identify bad actors. But that might be out of the scope of this issue.  Bear in mind that all the info is currently being sent to notify@couchers.org and the resulting ticket is stored in otobo with all the data.

**Comment by ShmuelTreiger** [comment]
Yup. That's why I'm thinking this might be frontend only.

Poking around more, we have a report API, this might just need to make use of it.

**Comment by aapeliv** [comment]
> Poking around more, we have a report API, this might just need to make use of it.

It should have its own API, but very similar to reporting. I think @AllhandsNoFeet wanted it in a different email address so he can do queues easier.

Do we currently save the reports in the DB @ShmuelTreiger ?

**Comment by ShmuelTreiger** [comment]
>queues easier

What do you mean by this?

Also, we can always just have reports send to one address and forward to another if we need.

>Do we currently save the reports in the DB @ShmuelTreiger ?

We have a Complaint object in models and we have `Report` in api.py/proto. IDK if it's actually used. Seems to me this issue should really be implementing the frontend and then merging the actual use/implementation with the backend.

**Comment by aapeliv** [comment]
> > queues easier
> 
> What do you mean by this?

The support tickets in OTOBO are placed in queues.

> We have a Complaint object in models and we have `Report` in api.py/proto. IDK if it's actually used. Seems to me this issue should really be implementing the frontend and then merging the actual use/implementation with the backend.

Yeah we should similarly create a model to just store the info in there.

**Comment by jesseallhands** [comment]
I think we can send all of the reports to notify@couchers.org but the subject needs to be different depending on the type of the report, and the username of the person being reported should be appended to the subject as well.

For example, if you report someone using the button on a profile, the e-mail sent to notify@couchers.org just has the subject "User Report".

Instead, it should have "User Reported: [USERNAME]" (this is technically a different issue).

If someone submits a report via the "report a problem" method outlined in this issue, the subject should be "Report sent by: [USERNAME]"

I'll update this issue to reflect that.

**Comment by aapeliv** [comment]
Small thing: Notifications come from notify@, they're sent from another address

**Comment by jesseallhands** [comment]
Ah sorry, yeah. I mean we could send both user reports and "report a problem" reports to safety@couchers.org for now and just update the e-mail subject to differentiate between the two.

**Comment by aapeliv** [comment]
@AllhandsNoFeet: why'd you remove the backend label?

**Comment by jesseallhands** [comment]
Based on this comment: 

> Yup. That's why I'm thinking this might be frontend only.
> 
> Poking around more, we have a report API, this might just need to make use of it.
