### ISSUE TITLE
Users should be added to communities straight after signing up

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1606]
Currently it's every 15 min in a background thread.

I'm not sure how important this is, but I think it's quite important for the first "render" when they land on the dashboard. Opinions @ItsiW, @AllhandsNoFeet, @lucaslcode?

**Comment by jesseallhands** [comment]
We probably should show both the global community and the local community (if there is one) on the dashboard. We can discuss it a bit more at the design team meeting this Sunday.

**Comment by ItsiW** [comment]
I agree it's important for first view. With v2 signup could you compute it after geo information is given and before volunteer form? Or do we only collect info at the end of the whole process?

**Comment by aapeliv** [comment]
> I agree it's important for first view. With v2 signup could you compute it after geo information is given and before volunteer form? Or do we only collect info at the end of the whole process?

Only after the user is actually created (transferred from a signup flow to a user).

**Comment by ItsiW** [comment]
Yes so when does that happen? After email confirmation?

**Comment by aapeliv** [comment]
After email confirmation. The PR does this synchronously when the user is created.
