### ISSUE TITLE
Add a "Save" button and text to the top of the profile editing page

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1611]
Users are overlooking the save button at the bottom of the profile editing page. This is causing confusion and frustration (people think it auto-saves but doesn't and they lose all the text they just typed up because they didn't click save!) The same happens with the profile photo.

**Solution:**
Keep the Save button at the bottom of the page, but also add a "Save" button at the top of the page next to the header "Edit Profile". To the right of the button (on desktop) or below the button (on mobile) there should also be a warning text:
"Click save after making any changes or uploading a photo!"

![image](https://user-images.githubusercontent.com/79384268/125209231-11004b80-e25d-11eb-8a99-72432e2938b5.png)
![Screenshot_20210711-154729_Firefox](https://user-images.githubusercontent.com/79384268/125209661-f8456500-e25f-11eb-9a89-57ece951692b.jpg)

**Comment by kerrylaval** [comment]
@lucaslcode @Couchers-org/frontend this is a bit more complicated than copy and paste! If we really want the save button to be next to "Edit Profile" heading then there needs to be some rearranging done. `<EditProfilePage />` is currently rendering `<EditProfile />` where the save button and all the form functionality lives. If we want to put the save button in `<EditProfilePage />` we'll need to lift the state up. Unless it would just be easier to put the button as far to the top of the form as possible. What do you think?

**Comment by darrenvong** [comment]
How about if we display an "all your progress will be lost" dialog instead before the user switches page? That seems like another common and well known pattern other sites use for warning the users they have unsaved changes before they go off the site/another page of the site.

I'm not a fan of having to lift state up for this - considering there is also another form for the page, it's a technical nightmare to have to switch between the save action depending on which form is active and I think it adds unnecessary technical complexity if the dialog solution will suffice.

**Comment by jesseallhands** [comment]
>How about if we display an "all your progress will be lost" dialog instead before the user switches page?

I think this could work, but because of how long some of these profiles are, it's not a good UX to have the person scroll all the way to the bottom of a super long page just to click "save". Another option would be a floating "save" button, but I'm not sure how much trouble it would be to implement that. No matter which solution we go with, we should have the "Any changes would be lost" warning.

**Comment by kerrylaval** [comment]
@AllhandsNoFeet not sure what you mean by a floating save button but I can start by adding the warning

**Comment by jesseallhands** [comment]
@kerryja I mean something like what we have in the bottom right of the dev-preview website:

![Screenshot_20210713-101746_Firefox](https://user-images.githubusercontent.com/79384268/125478441-7e8109f5-dd3f-4b0b-8521-d5bb7143024d.jpg)

I think I still like putting the save button at the top better, but the "floating" button might work.

**Comment by darrenvong** [comment]
> it's not a good UX to have the person scroll all the way to the bottom of a super long page just to click "save".

Seems like the longer term solution would be to break up the form and make each section editable like in the design rather than hacking a button near the top. So the warning could be a good stopgap solution to reduce the confusion for now? Considering all other forms have the button near the bottom, it seems inconsistent and a little out of place to me to suddenly have this appearing next to the title.

Having a sticky bottom button will likely be much easier to implement and not introduce unnecessary tech debt and potentially hurt page performance with the state lift move... which I think it's a reasonable compromise here if we were to do this until we re-work the form/edit flow on the frontend.

**Comment by jesseallhands** [comment]
>Having a sticky bottom button will likely be much easier to implement and not introduce unnecessary tech debt and potentially hurt page performance with the state lift move... which I think it's a reasonable compromise here if we were to do this until we re-work the form/edit flow on the frontend.

Sounds like a good compromise to me!

**Comment by kerrylaval** [comment]
looking into warning message/dirty form here #1635

**Comment by darrenvong** [comment]
Closed by #2007
