### ISSUE TITLE
Friends list looks busy

### ISSUE THREAD

**Issue by ShmuelTreiger** [Couchers-org/couchers#1626]
Looking at #1568, the friends list looks very busy. Maybe best to just have "city, country"?

**Comment by dommers-ux** [comment]
how does this look? a little bit better hierarchy and use of colors 
<img width="474" alt="Screen Shot 2021-07-12 at 11 03 59 PM" src="https://user-images.githubusercontent.com/83376913/125393775-c8808500-e365-11eb-9627-8d89d385b998.png">

**Comment by dommers-ux** [comment]
a preview if a friend request was involved 
<img width="487" alt="Screen Shot 2021-07-12 at 11 08 20 PM" src="https://user-images.githubusercontent.com/83376913/125393967-20b78700-e366-11eb-8fee-522bae64947b.png">

**Comment by ShmuelTreiger** [comment]
Way better. Is that a mockup or real? Wondering what it would look like for say, someone like Jakub in the original screenshot

![image](https://user-images.githubusercontent.com/14131043/125393947-b7337a80-e35d-11eb-8fe6-008ecdc94700.png)

Edit: I see you included him. I feel like that's too little though? There should at least be city IMO, if at all possible

Edit 2: I'm also wondering if age is necessary for your friends list? Though that's perhaps beyond the scope of this issue

**Comment by dommers-ux** [comment]
i just created a quick and dirty mock up after seeing this issue. i can create a legitimate design for you though

as for jakub's case... its very unique. typically, users either create their own display location or use the default location based on user location tracking. but if the location was that long, it would/should still be consistent with the rest of the users

**Comment by dommers-ux** [comment]
i actually noticed some users also have pretty long locations (like Jesse)...it still looks solid even with long display locations 

<img width="611" alt="Screen Shot 2021-07-12 at 11 31 35 PM" src="https://user-images.githubusercontent.com/83376913/125396092-4db96900-e369-11eb-964a-967700ad1219.png">

**Comment by ShmuelTreiger** [comment]
Definitely an improvement! I think it's maybe confusing if I'm a user trying to quickly grasp where my friends are, but it's def way better than before!

>i just created a quick and dirty mock up after seeing this issue. i can create a legitimate design for you though

I'm backend. IDK what frontend actually needs

**Comment by kerrylaval** [comment]
> Definitely an improvement! I think it's maybe confusing if I'm a user trying to quickly grasp where my friends are, but it's def way better than before!
> 
> > i just created a quick and dirty mock up after seeing this issue. i can create a legitimate design for you though
> 
> I'm backend. IDK what frontend actually needs

I'm frontend. I will do it!

**Comment by ItsiW** [comment]
Hey everyone would you mind keeping these kind of design and ideation discussions to slack

**Comment by lucaslcode** [comment]
This is a component which appears in many places. It supports not including the place name at all (so @kerryja you can make that change if you like) but further changes should probably go through the design team keeping in mind how it will affect other parts of the app
