### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1627]
For better or for worse, one of the main reasons people contact support is to ask for their account to be deleted. Most of these requests are due to duplicate accounts. We should add a "delete account" option under account settings so people can request a deletion instead of e-mailing us (which takes up a lot of support's time).

On the account settings page below the password change section, there should be the following text:

`If you would like to delete you account click **here**.`

When you click on "here" then there should be a dialog box that appears with the following:

Delete account?

Are you sure you want to delete your account? This cannot be undone.

Reason (optional):
[ Free text input box where user can input reason for cancelling] 

[Delete account forever]    [Cancel]

Text input into the box for the reason should be sent to notify@couchers.org so we can gather data on why users are deleting their account.

**Comment by ShmuelTreiger** [comment]
I prefer typing a confirmation text message instead of a button (i.e. please type 'allhandsnofeet', case insensitive)

**Comment by dommers-ux** [comment]
design idea to spark more ideas 

a **Delete Account** section at the bottom of account settings 
<img width="313" alt="Screen Shot 2021-07-25 at 6 39 43 PM" src="https://user-images.githubusercontent.com/83376913/126918995-ddb96883-5446-40ab-ab09-ae324b6ef0fa.png">


followed by a modal pop up 
<img width="387" alt="Screen Shot 2021-07-25 at 6 39 57 PM" src="https://user-images.githubusercontent.com/83376913/126919001-27f4a8eb-ad49-4440-8b24-cf0c5d60206d.png">

**Comment by dommers-ux** [comment]
followed by 
<img width="484" alt="Screen Shot 2021-07-25 at 7 07 47 PM" src="https://user-images.githubusercontent.com/83376913/126920173-908e0a87-a8fa-47e8-8910-b5469b8cd37e.png">

**Comment by lucaslcode** [comment]
Please keep GitHub issues for bugs and features which are requested/ready for devs to implement. I have added the "awaiting design" label for now and when we have a finalized design let's remove it and add a link to a finalized mock-up.

**Comment by aapeliv** [comment]
Also have a look at what the procedure will be, as discussed in last backend meeting:

https://github.com/Couchers-org/couchers/blob/develop/docs/meetings/backend/Meeting%20028.md

**Comment by aapeliv** [comment]
Closed in #1630
