### ISSUE TITLE
Alert should go away or only show up periodically

### ISSUE THREAD

**Issue by ShmuelTreiger** [Couchers-org/couchers#1629]
I get this alert every time I login. Seems redundant

![image](https://user-images.githubusercontent.com/14131043/125361892-d7921380-e322-11eb-8b6c-6c8e37761c82.png)

**Comment by jesseallhands** [comment]
Can we make this a snackbar with a long timeout (5 - 10 sec) that only displays when you first login?

**Comment by ShmuelTreiger** [comment]
Timeout is fine. Or add an x. I would also make it like once a month if possible*. Don't want the reminder every time, but occasionally would be nice.

*First log in where it's been a month since it was last shown

**Comment by aapeliv** [comment]
It's a lot of effort to remember this, which should be done in the backend.

It's not worth it at the moment since we'll be phasing out magic links soon.
