### ISSUE TITLE
Reporting a profile does not send a report to support

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1650]
On desktop, I reported 2 different accounts via the report button on each of the 2 profile pages. Both times I got the notification snackbar saying the report was successfully sent, but no email was received by safety@couchers.org from notify@couchers.org

I confirmed that this was not an otobo issue because I was able to email safety@couchers.org from my personal Gmail account and that email went through to otobo just fine.

It may be a coincidence, but we haven't received many volunteer signups via forms recently either in otobo.

In any case, users are not currently able to report any profiles via the app, so there is no way to report anything right now other than via email.

**Comment by aapeliv** [comment]
Caught up in spam filter. Solved.
