### ISSUE TITLE
Fix frontend tests

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1656]

**Comment by lucaslcode** [comment]
" a4a7463564336db35c4a0f4ea597ab499fe42064 is the first bad commit"

**Comment by aapeliv** [comment]
Oop... It is my fault :S

**Comment by lucaslcode** [comment]
Didn't mean to close

**Comment by lucaslcode** [comment]
I have narrowed it down to the implementation of `toggleCheckbox` (pasted below). There's nothing obviously wrong with it, but I'll refactor it to be more idiosyncratic.

```

  const toggleCheckbox = (
    option: string,
    value: string,
    onChange: (s: string) => void
  ) => {
    const currentChoices = value.split(",").filter((v) => !!v);
    if (currentChoices.includes(option)) {
      onChange(currentChoices.filter((opt) => opt !== option).join(","));
    } else {
      onChange(currentChoices.concat(option).join(","));
    }
  };
```

**Comment by lucaslcode** [comment]
Checkboxes cause it to be flakey, don't know why
https://github.com/react-hook-form/react-hook-form/issues/532#issuecomment-791793977
