### ISSUE TITLE
Signup form lowercasing

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1657]
Right now it doesn't accept mixed-case when it requires lowercase. E.g. typing in `Aapeli28` (as one does automatically on iPhone), it's not accepted.

This should lowercase as one is typing.

**Comment by darrenvong** [comment]
Are usernames case sensitive on the backend?

**Comment by aapeliv** [comment]
Yes, the frontend should lowercase them. Non-lowercase characters are not supported for usernames.
