### ISSUE TITLE
Add link to write reference in emails when other person writes a reference

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1671]
When a host or surfer writes a reference, the other party gets an email. If that other party hasn't yet written a reference, we should include a direct link to write one.

**Comment by ghost** [comment]
I would be willing to investigate this!

**Comment by aapeliv** [comment]
> I would be willing to investigate this!

Awesome! Give it a shot, and if you need any help, write here or feel free to email me at "aapeli" at our domain.

**Comment by ghost** [comment]
I have the environment set up now, what are the files of focus for this issue? (I am thinking the fix is in references.py but I am unsure and would like clarity)

**Comment by aapeliv** [comment]
Hey!

You'll need to inject the URL into the template in `//app/backend/src/couchers/tasks.py`. For that, have a look at `send_reference_reminder_email` in that same file. I think the function you should edit is `send_host_reference_email`. Look around for where that function is called, it seems to be a bit poorly documented (feel free to add more comments!).

Then you'll want to update the template in `//app/backend/templates/host_reference.md` to use that URL.
