### ISSUE TITLE
Reimplement contributor form & emails

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1673]
* Need to reimplement a contributor form that can be filled out after signup
* We used to have a lambda handler that would send an email to open a ticket when a user filled in the contributor form. Need to reimplement those too.
* Import past forms (that can be matched to a user)

@ItsiW: when do you want signup emails? Always? Only when they fill in some of the feedback? Only when they say they'd like to contribute?

**Comment by ItsiW** [comment]
For now, always. Then we can decide once we've sifted through some

**Comment by aapeliv** [comment]
Even when they fill none of the feedback form? What info do you want sent in that case?

**Comment by ItsiW** [comment]
If they fill nothing then no. But I guess if they still say they want to contribute then send it through and we can google them
