### ISSUE TITLE
Jail page keeps reloading

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1713]
Reported and recorded by Lukas: https://1drv.ms/v/s!Ajo4-4qFAquUgagRP3RS4uwakiBh5Q?e=BidB2W

**Comment by lucaslcode** [comment]
This is easy to fix, change the route type to the one without navigation. It happens because the navigation makes a query every 5 seconds for notification badges, but it gets an UNAUTHORIZED response so redirects to jail.
