### ISSUE TITLE
Comprehensive email testing

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1714]
We've had a few bugs slip through which cause serious issues in prod. It would be good to test emails comprehensively: test all of them, and test all parts in them. We should probably build a bit of infrastructure around it to help do this easily.

Maybe we should just verify that all emails match to a pre-rendered version?

Might instead be good to wait until we get the new email templates, etc.

**Comment by openscript** [comment]
We usually use https://mailcatcher.me/ for this. At one hand it has a nice simple ui, at the other hand you can fetch the emails via a simple rest API.

**Comment by aapeliv** [comment]
This is basically done now with the new email templates.
