### ISSUE TITLE
Text wrap on profiles is not working properly

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1716]
The current  text wrapping on profiles results in words getting cut off and makes it very difficult to read the profile. See screenshot below:

![image](https://user-images.githubusercontent.com/79384268/126915347-323880f0-d88b-460c-a3e1-d7071ad89108.png)

Words should not be cut off like that at the end of a line.

**Comment by lucaslcode** [comment]
This is fixed on next

**Comment by lucaslcode** [comment]
Actually it is supposed to be fixed but still seems dodgy for me

**Comment by lucaslcode** [comment]
Nevermind
