### ISSUE TITLE
Add Skip on Contributor Form on Sign Up 

### ISSUE THREAD

**Issue by dommers-ux** [Couchers-org/couchers#1718]
We should add a **skip** option on the contributor / feedback form on the sign up flow. 

It currently looks like this -
<img width="529" alt="Screen Shot 2021-07-25 at 6 11 58 PM" src="https://user-images.githubusercontent.com/83376913/126918064-c3f644cb-4c07-48b3-9afe-9da5636545e5.png">

It is important for users to finish the sign up process as fast as possible. The more steps required --> the higher likelihood of quitting during registration. Maybe something like this - 
<img width="368" alt="Screen Shot 2021-07-25 at 6 14 38 PM" src="https://user-images.githubusercontent.com/83376913/126918163-de360561-dae2-415d-833c-488d3c24c288.png">

**Comment by confused-cabbage** [comment]
Hey! I'd be willing to take this issue on!

**Comment by alceil** [comment]
Can I take up this issue? @dommers-ux

**Comment by lucaslcode** [comment]
Sure! @alceil

**Comment by lucaslcode** [comment]
Maybe reduce some of the other text as suitable if you add that

**Comment by alceil** [comment]
I have linked  a pr. Can you review it? @lucaslcode

**Comment by Tay0108** [comment]
Should this issue be closed?
