### ISSUE TITLE
Signup page considers emails with periods in the username as invalid.

### ISSUE THREAD

**Issue by confused-cabbage** [Couchers-org/couchers#1728]
The signup page will not let you create accounts using emails with periods in the name.
Here is an example of me trying to enter in an email (granted, it's not my real email address) with a period in it. If you remove the period, the registration process can successfully go to the next stage.
![invalid email](https://user-images.githubusercontent.com/65237366/127055979-0ea2d9d0-fed3-442b-b1f4-9f08b09c7884.png)
This is a problem, because some folks have emails with periods in them, and they wouldn't be able to sign up with them in this current state.

**Comment by lucaslcode** [comment]
Actually it seems to be the capital letters. The error message should be better, or it should automatically lower-case

**Comment by confused-cabbage** [comment]
Would this be a change to the regex expression in frontend/src/utils/validation.ts ? 
`// taken from backend
export const nameValidationPattern = /\S+/;
export const usernameValidationPattern = /^[a-z][0-9a-z_]*[a-z0-9]$/;
export const emailValidationPattern =
  /^[0-9a-z][0-9a-z\-_+.]*@([0-9a-z-]+\.)*[0-9a-z-]+\.[a-z]{2,}$/;`

Or part of the textfield in frontend/src/features/auth/signup/BasicForm.tsx ?
`<TextField
          id="email"
          fullWidth
          className={authClasses.formField}
          name="email"
          variant="standard"
          inputRef={register({
            pattern: {
              message: EMAIL_EMPTY,
              value: emailValidationPattern,
            },
            required: EMAIL_REQUIRED,
          })}
          helperText={errors?.email?.message ?? " "}
          error={!!errors?.email?.message}
        />`

It seems like there shouldn't be an error thrown when you put caps, because email addresses are not case sensitive. The organization I work for typically capitalizes email usernames for readability, so I sometimes find myself entering the caps out of habit. Seems like the system should just accommodate the all caps and perhaps change the emails to lowercase.

**Comment by lucaslcode** [comment]
Fixed in #1709
