### ISSUE TITLE
Long display name on profile overflows container

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1730]
![image](https://user-images.githubusercontent.com/79384268/127077809-020efbdd-97b2-4663-96cb-91982cb2e510.png)

![image](https://user-images.githubusercontent.com/79384268/127078564-a405e6c2-ce6b-455b-a90e-e47145df3d02.png)

For long display names, can we scale down the font size to fit within the container bounds?

**Comment by SCD346** [comment]
I'd like to take this on if it is not assigned to anyone.

**Comment by aapeliv** [comment]
Great, I'll assign it to you then!
