### ISSUE TITLE
When editing communities, hyperlinks do not display on edited page

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1732]
For example, if I edit the markdown or WYSIWYG:
![image](https://user-images.githubusercontent.com/79384268/127248673-4e55e492-f9cc-495e-901f-1cd0e046e03f.png)

This is what is displayed after submitting the changes/edits:
![image](https://user-images.githubusercontent.com/79384268/127248811-02209d35-9fb6-475d-a43f-174e8aa297db.png)

As you can see, the link is not displayed. If you click on the word nothing happens, so it's not just a display issue either.

**Comment by lucaslcode** [comment]
How was this link inserted? We don't support html links, it should be a markdown link. But if the editor does that for you, it is indeed a bug

**Comment by jesseallhands** [comment]
I was using the WYSIWYG editor, but the problem seems to be fixed now!
