### ISSUE TITLE
Email alerts for messages

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#175]
Putting this in alpha milestone but that is probably optimistic!

**Comment by aapeliv** [comment]
Done for host requests & friend requests.

For message emails, we require #282

**Comment by lucaslcode** [comment]
@aapeliv  is this closed?

**Comment by aapeliv** [comment]
No, not yet. We send notifications for a lot of other things, but not for messages. (This is because we want to wait a bit before sending out notifications in case the user is on the app, so we don't send extra emails.)

**Comment by aapeliv** [comment]
* Add `last_notified_message_id = Column(BigInteger, nullable=False, default=0)` to `GroupChatSubscription`.
* A RepeatedJob background job that runs every 5 minutes and checks each `GroupChatSubscription`, for any messages that are older than 30 minutes that have message id greater than `last_notified_message_id`. Sends an email, and updates `last_notified_message_id`.
* (Maybe, add a `mute_emails` in `User`, to turn off all non-essential emails, then requires also an RPC and tests)
