### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1760]
Some things that we'd want to do, and why we care, in order of importance:

1. Pre-rendering a list of static pages (e.g. /about, /blog/..., etc; list known at build time), so we could do the landing site in react and burn the vue shitshow
2. Nice link previews for profiles (or TBA invitation links)
3. Incrementally adding rendering to a set of other classes of pages, e.g. events, profiles, etc. This would hugely help SEO with crawlers being able to read some real site content.
4. Rendering everything server side to make the experience faster for users

1 is pretty high priority, but seems it might be possible with CRA much easier: https://create-react-app.dev/docs/pre-rendering-into-static-html-files. We will want 2 at some point too, but it might be able possible to do some server-side tweakery that just replaces/adds meta tags/etc. It would be great to do 3 sometime too, especially once we start having more organic content. I'm not sure if we'll ever care about doing 4: it's probably expensive and quite complicated.

**Comment by lucaslcode** [comment]
I am against *real* server side rendering for a site like this, it will make server responses slow and hosting expensive. 

However we can definitely do static site generation using react snapshot (or whatever the latest one is) and hydrate, which I'm assuming it does. 

I'd be a bit concerned about our time to interactive since we're such a chunky site, we'd need to test it out.

**Comment by lucaslcode** [comment]
> do some server-side tweakery that just replaces/adds meta tags/etc

No need for that, we can use `react-helmet` (actually I was going to open an issue about that to fix our page titles, I must have forgotten)

**Comment by lucaslcode** [comment]
I'm not sure off the top of my head how to manage this statically for pages which are different when logged in without having a "flash" of the non-logged in version

**Comment by aapeliv** [comment]
> > do some server-side tweakery that just replaces/adds meta tags/etc
> 
> No need for that, we can use `react-helmet` (actually I was going to open an issue about that to fix our page titles, I must have forgotten)

That's sill on the client side javascript, right? Won't be picked up by non-JS clients.

> I'm not sure off the top of my head how to manage this statically for pages which are different when logged in without having a "flash" of the non-logged in version

We can just have the middleware/renderer/proxy never return any pre-rendered stuff if the `couchers-sesh` cookie is present.

**Comment by lucaslcode** [comment]
> Won't be picked up by non-JS clients.

It will if we use `react-snap`!

**Comment by aapeliv** [comment]
> I am against _real_ server side rendering for a site like this, it will make server responses slow and hosting expensive.

I agree mostly. But I think once we start having content that's viewable by non-logged in users, and that we want indexed by search engines and found by other crawlers/link preview generators. In that case it would be nice to generate the page and cache it on the server side; it would probably make the site pretty snappy if we can pre-generate all of the page since it's all the same.

**Comment by aapeliv** [comment]
I think we should first start with react-helmet + react-snap (or whatever is the modern one): that ought to get us to merging the landing page with the app, also so we can move away from the `app.` domain. It sounds like that would be fairly straightforward and not add too much headaches or changes to the codebase. That should take us pretty far.

Eventually though, it would be great to get proper link previews for invites. So that if I share an invite link on a social media site, it would come up with "Aapeli invited you to join Couchers.org! Join 3.1k+ other couch surfers blah blah blah blah", and the link image would be some nice arrangement with my profile picture and name or something (of course needs permission from user to make that public). That we could either do with SSR (if someone wants to waste another day on this), or with meta tag trickery in python + an image renderer. Either way, that would require a backend call to retrieve the info to display.

**Comment by darrenvong** [comment]
`react-snap` looks like a good option for plugging the SEO gap for the time being, and likely improve performance on the first load time.

But if we were to go all the way with all four points you mentioned here, I think we'll have to re-invent the wheel a lot and fine tune things in the build process to get all of that incremental render stuff working to the point that it might just be easier to use a SSR framework at that point.

**Comment by aapeliv** [comment]
Actually, I remember now, I did the prerending + meta stuff ~3 years ago with react-helmet and [react-static](https://github.com/react-static/react-static) here: https://github.com/yoninazarathy/epsilon-stream-web. If I recall correctly, that worked OK too.

> But if we were to go all the way with all four points you mentioned here, I think we'll have to re-invent the wheel a lot and fine tune things in the build process to get all of that incremental render stuff working to the point that it might just be easier to use a SSR framework at that point.

Yeah I don't really think we should do point 4. I think it'd be good at most to basically have (in the long term) the logged in version (no SSR), and then a logged out/crawler version which could really just be fully static.

**Comment by aapeliv** [comment]
Wooooo!!!
