### ISSUE TITLE
All page titles are the same

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#1762]
We should use React Helmet to change the title based on the page.

**Comment by thdk** [comment]
Do we need React Helmet for this? Seems there have been no commits to the React Helmet project in over a year and there might be alternatives available by now.

See also this article: https://dev.to/luispa/how-to-add-a-dynamic-title-on-your-react-app-1l7k

**Comment by lucaslcode** [comment]
Yes you're quite right. We will want to do dynamic meta tags but we can do that later and looks like `react-head` would be a better option.

**Comment by thdk** [comment]
@lucaslcode or we set the title with a custom hook from either the AppRoute component or the PageTitle component.

Would something like that be ok?

PageTitle:
This would mean that only pages that have this PageTitle component somewhere in the render tree will override the default page title that is used now. If a page for some reason has to PageTitle components, only the latest renderend page title will be used.

AppRoute:
Maybe a little to high level to set the page title in AppRoute?

**Comment by lucaslcode** [comment]
Yes, AppRoute is too inflexible as we sometimes define further route switches in the component.

I think PageTitle would be good, but many pages don't use it, so we'd need a custom hook too.

**Comment by alesdvorakcz** [comment]
Do we want to include into html titles some prefix/suffix?

For example: 
Profile | Couchers.org Beta
Couchers | Profile

**Comment by lucaslcode** [comment]
Yes the first one
