### ISSUE TITLE
Contributor Form emails sending when fields are empty

### ISSUE THREAD

**Issue by ItsiW** [Couchers-org/couchers#1770]
from models.ContributorForm

```py3
    def should_notify(self):
        """
        If this evaluates to true, we send an email to the recruitment team.
        """
        return (
            (self.ideas != None)
            | (self.features != None)
            | (self.experience != None)
            | (self.contribute_ways != None)
            | (self.expertise != None)
        )
```

however emails are being sent when all should be None

**Comment by faizjamil** [comment]
I'mma take a look at this and see what I can do.

**Comment by aapeliv** [comment]
Sounds good!

**Comment by ItsiW** [comment]
Hey @faizjamil are you still working on this? This is becoming a higher priority issue for us receiving the empty emails

**Comment by faizjamil** [comment]
Yes, I need to do a quick look through of SQLAlchemy today and see where to
go from there.

**Comment by faizjamil** [comment]
Hmm, well I just got around to starting debugging. I swapped those `|` operators for `and` in that return statement. That did nothing so I'm going to study the documentation in the repo to see how the contributor form submission works.

**Comment by lucaslcode** [comment]
gRPC messages default to an empty string (not `None`), maybe that's why?

**Comment by aapeliv** [comment]
Hey; sorry. I'm going to grab this and fix it up quick. The support team is getting frustrated with the bombardment of emails, and I think debugging this requires having a look at the existing rows in the DB!

**Comment by faizjamil** [comment]
Go for it.
