### ISSUE TITLE
Only include cities in location search

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#1776]
Add an option in the geocode hook to only include cities/towns in results. 

This is because our location search currently does radius around a point, so using a country result just gives you an X km circle in the middle of the country.

**Comment by Arnab1181412** [comment]
Hey can I work on this issue

**Comment by lucaslcode** [comment]
Great, email me if you have any issues!

**Comment by Arnab1181412** [comment]
Yes sir can you give me a bit more explanation/context regarding the issue and it would be great if you could attach some files related to it.

**Comment by lucaslcode** [comment]
In `app/frontend/src/utils/hooks.ts` there is the geocoding query logic in `useGeocodeQuery`. I would add a parameter `isPoint` which defaults to false, and if it is true, it filters the results of the query to exclude the results which only have address parts bigger than city. (like "Victoria, Australia" would be excluded because all the address parts are larger than "city" but "Melbourne, Victoria, Australia" is included). 

It may require some reading of the Nominatim and react query documentation.

**Comment by Arnab1181412** [comment]
Yes sir I have to read Nominatim and react query docs .

**Comment by aapeliv** [comment]
Hi @Arnab1181412; how're you doing on this issue? Do you need any help to keep going?

**Comment by alesdvorakcz** [comment]
I am thinking about use cases for this. I can imagine two situations:
1. I am setting a specific location (for example for an event). Then anything bigger than city is not specific enough. We can filter it out.
2. I am setting my location and I don't want to provide anything specific. In this case I don't mind to see less specific results like countries, counties, etc. But does it make sense? Why not to filter them out as well?

am I missing some other use case when it is usefull to see unspecific results in location search?

**Comment by lucaslcode** [comment]
Some of this is workarounds for using Nominatum because it's free (and results are not as good). Thinking about it more, I don't think we should filter anything out - it will be confusing if users type "Australia" and none of the results are in Australia (I just tried it). Maybe instead, we should still display them, but not allow it in the form validation with an error "Please select a more specific location, such as a city."

**Comment by lucaslcode** [comment]
Re use cases, I think you're right but we might want it in the future. I know it's not good to write code for future use cases, but in this case I think it's as much "more robust" rather than imagining future uses (plus it's just a prop and a condition).

**Comment by alesdvorakcz** [comment]
then the prop will not be for `useGeocodeQuery` hook but for MapSearch and/or LocationAutocomplete components. `useGeocodeQuery` should probably just return a `type` for each result so the validation is possible.

Should I implement the validation into both MapSearch and LocationAutocomplete?

**Comment by lucaslcode** [comment]
Maybe not map search. (And maybe optional for LocationAutocomplete? I can't recall off the top of my head if it is used in several places.)
