### ISSUE TITLE
New developer intro doc

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1787]
That we can send to good devs and have on the site so that people can easily get started through good first issues, etc.

**Comment by faizjamil** [comment]
What do you think should be added that isn't covered by existing docs in the repo?

To start I would consider giving an example of what your container logs will look like when the backend is working properly, based on the fact that you had to tell me that there was no problem in that other issue.

**Comment by aapeliv** [comment]
This document is separate to the developer docs. The idea is to have a nice page to describe the process of joining the team, before devs join github and get started.



> To start I would consider giving an example of what your container logs will look like when the backend is working properly, based on the fact that you had to tell me that there was no problem in that other issue.

Yes, that's missing from the docs (but it's separate from this issue). Would you like to make a PR with a comment about the continuous sql logs when it's working correctly?

**Comment by faizjamil** [comment]
> This document is separate to the developer docs. The idea is to have a nice page to describe the process of joining the team, before devs join github and get started.

I see, well what is the process of joining the team?

> Yes, that's missing from the docs (but it's separate from this issue). Would you like to make a PR with a comment about the continuous sql logs when it's working correctly?

Yeah sure I'll whip up a PR sometime today or tomorrow.

**Comment by aapeliv** [comment]
> I see, well what is the process of joining the team?

Finding a good first issue, coming to a team meeting, etc.

**Comment by aapeliv** [comment]
Closed in 750b58d621934b5e5e8aac5d0317f2d4d7b933df
