### ISSUE TITLE
How to debug backend in VS Code

### ISSUE THREAD

**Issue by faizjamil** [Couchers-org/couchers#1838]
I wasn't able to find great documentation on how to debug **just the backend** in VS Code since I have to use a Docker Compose file. I go the /app directory, open VS Code, aand I can't find any info on how to use an existing docker-compose file with VS Code. What development environment is recommended to be used here and if it involves VS Code can you tell me how to set it up?

**Comment by aapeliv** [comment]
What kind of debugging ability are you looking for?

**Comment by faizjamil** [comment]
I want to step through the backend to work on that issue I've been assigned to. Debug the Python code which makes up the backend.

**Comment by aapeliv** [comment]
I don't know if anyone currently has VS Code step-through set up like that, so I'm not sure what it requires to set up. I'm not familiar with it.

However, it is possible to run the backend locally and everything else in a docker container. That might be the way to set this up?

**Comment by faizjamil** [comment]
Ok, well how do I make sure that the backend can communicate with the other containers? What ports do they use?

**Comment by faizjamil** [comment]
If no one uses VS Code to debug, how do they debug the backend?

**Comment by aapeliv** [comment]
The main thing is that the proxy (envoy) will be sending stuff to the backend. You might have to change the references in `//app/proxy/envoy.yaml` from `backend` to `host.docker.internal`.

The backend also needs some configuration, namely from `backend.dev.env`. You can read it into your env with something like `env $(cat ../backend.dev.env | rg -v '^#' | xargs)` followed by the command.

I used to run the backend like this, but now find the docker container more convenient.

**Comment by aapeliv** [comment]
> If no one uses VS Code to debug, how do they debug the backend?

I can't speak for others; but I personally don't find myself stepping through the code that often. We write regression tests for bugs, and I personally find that the tracebacks provide all the info I need. On the odd occasion that this doesn't suffice, I just run it locally and that's enoug.

It's worth adding that the dev environment is set up so that the backend restarts on code change.

All that said: we'd be very glad to add docs on how to do proper debugging if you'd like to contribute that!

**Comment by faizjamil** [comment]
Soo the tests that are for the backend give tracebacks to a bug you are encountering?

**Comment by aapeliv** [comment]
> Soo the tests that are for the backend give tracebacks to a bug you are encountering?

Yes, that's how it goes generally.

Also; just emailed you about our backend meeting starting in 2min!

**Comment by aapeliv** [comment]
Did you get it working @faizjamil?

**Comment by faizjamil** [comment]
I appear to have gotten it working. Won't be able to use a computer until
tomorrow.

**Comment by aapeliv** [comment]
Okay, great! Could you please write a doc with instructions on how to do it in `//docs` when you have a chance?

**Comment by faizjamil** [comment]
Right, I'll do it tomorrow once I can remember exactly how to do it again.
Keep in mind the thing is I have **appeared** to gotten it working. I need
to make sure tomorrow that I can run without debugging and step through the
code with no issues.
