### ISSUE TITLE
Add links to message/discussion body

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1851]
When you send a message to a user using the messaging system, if you include a hyperlink in the message, it is not clickable (see below). This forces the user to have to copy and paste the hyperlink into their browser, which is tedious when using mobile (and annoying when using desktop). 

Hyperlinks in messages should automatically be clickable when the message is sent.

However, we shouldn't allow the hyperlink to be editable (which would allow people to "fake" URLs to display one thing but link to a different website, which could be used for malicious purposes). 

This seems related to  Couchers-org/couchers#4196 

![image](https://user-images.githubusercontent.com/79384268/130342934-179fdc49-90f0-4b91-a0e0-ea49418bd247.png)

**Comment by aapeliv** [comment]
This is because messages are plaintext; as opposed to other things. We probably need to create a "lite markdown" version for messages.

**Comment by lucaslcode** [comment]
I don't think we want anything other than links, so maybe we need a component that auto-creates links
