### ISSUE TITLE
Editing event with similar time gives "overlapping occurances not allowed" error

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#1869]
Title. Blocking #1862

**Comment by darrenvong** [comment]
I'm not sure I fully understand how to reproduce this... I managed to edit an event without changing the time and just update the title and it works fine? 🤔

**Comment by darrenvong** [comment]
Might be good for @aapeliv to look at this if he understands what you're on about, otherwise can't do much on the frontend about this :p

**Comment by lucaslcode** [comment]
I can no longer reproduce this either 🤷🏻
