### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by ItsiW** [Couchers-org/couchers#1882]
Create an events page and topbar link.

On the events page we want to show all events in chronological order, and a past events tab showing events in reverse-chronological order

**Comment by lucaslcode** [comment]
Of which communities? All?

**Comment by ItsiW** [comment]
Yep the feedback is that we want a place with all events across all communities

**Comment by lucaslcode** [comment]
I'm not sure there is currently a way to get all event, but it is a very simple backend change if not.

**Comment by darrenvong** [comment]
Where would this appear? A standalone events page like when you go to `/events`?

**Comment by dommers-ux** [comment]
should we design a mock up?

**Comment by ItsiW** [comment]
Yeah standalone page

**Comment by aapeliv** [comment]
There is an API call to get all future or all past events:

https://github.com/Couchers-org/couchers/blob/43c6f39a4c635d1e43f69c878ecaca75b3838cb2/app/proto/events.proto#L71-L73
