### ISSUE TITLE
Label does not hide when start entering Location on a signup page 

### ISSUE THREAD

**Issue by goskan93** [Couchers-org/couchers#1884]
![image](https://user-images.githubusercontent.com/39600021/131211492-46bf25ea-15ff-45f1-8002-8de7be60d3ef.png)

**Comment by goskan93** [comment]
No I noticed that when I write text in the input that appears on a map, this text will appear below. What should be the correct  behavior here? Maybe the input below should not be editable, it shouldn't even be an input field?

**Comment by lucaslcode** [comment]
What browser and device is this on?

The red error also appears a bit too eagerly imo

**Comment by lucaslcode** [comment]
But the behaviour you are talking about is correct - it populates automatically, but you can change it to whatever you want to display on your profile

**Comment by goskan93** [comment]
chrome 92.0.4515.159

**Comment by goskan93** [comment]
Imo, the input below is more visible than search bar on the map - so maybe it should be disabled till the location from map is not chosen?

**Comment by lucaslcode** [comment]
That's a good idea.

**Comment by goskan93** [comment]
I can try to do that

**Comment by darrenvong** [comment]
I wonder if I broke something here by accident by making the `LocationAutocomplete` more re-usable so it can be shared in the create/edit event page 😅  please check this form (by creating/editing an event) in say, the global community as well when you get around to make the fix
