### ISSUE TITLE
Validate length of text inputs 

### ISSUE THREAD

**Issue by goskan93** [Couchers-org/couchers#1886]

**Comment by lucaslcode** [comment]
Which inputs? How long should they be?

**Comment by goskan93** [comment]
For example, on sign up page, where are questions about contributing - but I don't know if there are more text inputs like these. 
Hmm I don't know 1k, 4k should be enough for people to write about themselves? For sure the 64k I entered is way too much ;d

**Comment by lucaslcode** [comment]
Why? I don't think there's a technical reason to introduce a limit - unless it didn't work when you tried to submit

**Comment by goskan93** [comment]
Hmmm the only pros I can think about now, is to prevent from polluting database, but maybe it is not as big problem as I thought at first place.
