### ISSUE TITLE
Links too large

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1914]
<img width="1278" alt="Screen Shot 2021-09-05 at 5 42 47 pm" src="https://user-images.githubusercontent.com/2975660/132142242-3f7752bc-36a7-4739-92f1-fa330388f220.png">

**Comment by ItsiW** [comment]
They should probably both be buttons. The whole of the password section could be replaced with one "Set a password" button

**Comment by dommers-ux** [comment]
<img width="157" alt="Screen Shot 2021-09-09 at 4 52 36 PM" src="https://user-images.githubusercontent.com/83376913/132777119-c66fa164-8728-4127-b628-63b0ffaa69eb.png">

if buttons are used in this case, use secondary style if possible. thought id mention! 
(light gray fill, dark text)

**Comment by wbruntra** [comment]
Greetings! I'd like to work on this issue
