### ISSUE TITLE
Text spacing on sidebar is wonky when on the "leave a reference" page

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1939]
See spacing issue below:
![image](https://user-images.githubusercontent.com/79384268/132597160-128bab6e-adff-4e0d-8a26-19381da57443.png)

**Comment by 404-P4rziv4L** [comment]
Hey @AllhandsNoFeet I would like to fix this. Could I be assigned?

**Comment by 404-P4rziv4L** [comment]
Could you help me out with recreating the issue @AllhandsNoFeet

**Comment by lucaslcode** [comment]
@Abhijnan-Bajpai from the screenshot, this occurs when leaving a reference. Follow the instructions in our readmes to get a Dev environment set up and leave a reference for a friend (you could make two accounts since you need to accept the friend request to leave a reference).

**Comment by Akshansh99** [comment]
if @Abhijnan-Bajpai is not working on this issue, may I look into it? @AllhandsNoFeet

**Comment by 404-P4rziv4L** [comment]
> if @Abhijnan-Bajpai is not working on this issue, may I look into it? @AllhandsNoFeet

Go ahead, I'm really caught up with work

**Comment by Akshansh99** [comment]
@lucaslcode I checked for this issue and it seems to be resolved.

**Comment by lucaslcode** [comment]
@AllhandsNoFeet can you confirm this is resolved?

**Comment by jesseallhands** [comment]
Looks good now! Thanks!!!
