### ISSUE TITLE
Users land on bottom of the event page when clicking on an event from the communities page

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1940]
This problem is most obvious on mobile:

When you visit a community page (eg: Global Community) and click on an event, it takes you to the event page but you land on the bottom of the page rather than the top.

This is very confusing and forces the user to scroll to the top of the page to see the event details.

The user should automatically land at the top of the event page.

**Comment by thdk** [comment]
Same issue as #1887
