### ISSUE TITLE
Error when clicking on link to expired event

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1945]
When I click on the following link (to a valid, but expired event) I get a backend error:

https://app.couchers.org/event/138/couch-surfing-happy-hour

![image](https://user-images.githubusercontent.com/79384268/132925867-6d98bd98-d1f6-4dd9-9765-7f4ec826c77a.png)

When I click on the link of an expired event, I should be able to view it even though it's expired.

**Comment by darrenvong** [comment]
This is now also blocking #1882 ...
