### ISSUE TITLE
Misleading error message when user not found

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1950]
When trying to log in with a bogus username, the error message is cryptic.

<img width="523" alt="Screen Shot 2021-09-11 at 3 28 08 pm" src="https://user-images.githubusercontent.com/2975660/132959301-0badd005-6aa9-4cfb-b6f9-c8ba1988a10c.png">

I've checked the inspector, the returned error is "Couldn't find that user.", but instead the UI displays this: "This shouldn't have happened. Please contact us and tell us what you were doing to help us prevent this error in the future."

**Comment by lucaslcode** [comment]
This seems to have been introduced in #1893
