### ISSUE TITLE
"Regions I've Visited" and "Regions I've Lived In" menus have transparent background

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#1952]
See screenshots below:
![image](https://user-images.githubusercontent.com/79384268/132971964-4ebe6820-c99e-48a2-b8d9-2311721cbe0a.png)
![image](https://user-images.githubusercontent.com/79384268/132971968-d495c97b-1efe-4e50-9a32-9c1f66901e2e.png)

Browser is Firefox 91.0.2 (64-bit) on Windows

**Comment by lucaslcode** [comment]
I can't reproduce this on Firefox :'(
We have a `zIndex: "unset"` on the contents of the markdown box to prevent it jumping above the country popup. Seems like this is related, but it's working on my end. 🤔

**Comment by AllhandsNoFeet** [comment]
I just tried again on Firefox mobile and was able to replicate: 

![Uploading Screenshot_20210913-165846_Firefox.jpg…]()

**Comment by jesseallhands** [comment]
I just tried again on Firefox mobile and was able to replicate:

![Screenshot_20210913-165846_Firefox](https://user-images.githubusercontent.com/79384268/133162277-adcffe3c-4520-4f4f-819f-f4a97df7b3dc.jpg)

I tried the other menu first and it worked fine, then tried the above menu in the screenshot and got the wonky transparent background.

**Comment by jesseallhands** [comment]
I was able to replicate in chrome mobile as well:

![Screenshot_20210913-170427_Chrome](https://user-images.githubusercontent.com/79384268/133162645-b4134b6b-1a22-419e-8c27-401d9cd4d1db.jpg)

**Comment by lucaslcode** [comment]
I was trying on next where it doesn't appear. Maybe it was solved in an update?

**Comment by lucaslcode** [comment]
Please re-open if this persists after next is released to production.
