### ISSUE TITLE
No ability to sign up with a password

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#198]

**Comment by aapeliv** [comment]
@lucaslcode: do you think this should be an option on the signup screen, or only through settings?

If the former, then this issue ought to track that, and the backend potentially needs some functionality to do that (unless the signup flow presents a screen after verifying your email). The account management APIs are not jail-accessible.

If setting a password happens only after having signed up, then this functionality is done and the issue can be closed.

**Comment by lucaslcode** [comment]
Let's close it and re-open when enough people request/complain 😁
