### ISSUE TITLE
I can't sign up

### ISSUE THREAD

**Issue by philippedev101** [Couchers-org/couchers#1983]
Getting a red bar with the message

> An unknown backend error occurred. Please consider filing a bug!

**Comment by aapeliv** [comment]
@philippedev101: please email us at support@ our domain with the email you tried to use logging in, so I can debug this!

**Comment by philippedev101** [comment]
I don't get this error anymore and i don't know what has changed. Though would be good to change message from

> An unknown backend error occurred. Please consider filing a bug!

to

> Something went wrong on the website. Please email us at support@couchers.org and explain what you were doing and what you filled in. Attached any relevant screenshots. We will look into it as soon as possible. Thank you for your understanding.
