### ISSUE TITLE
Remove "close button" and add X to the top left (community nav)

### ISSUE THREAD

**Issue by dommers-ux** [Couchers-org/couchers#2014]
In the current model, the close action button is a motivator to close the pop up window instead of interact with it. If possible, let's try to remove it and add an X component in the top left instead. This encourages the user to interact and it scales better as communities are added to the list. Example below: 

<img width="268" alt="Screen Shot 2021-09-24 at 6 18 39 PM" src="https://user-images.githubusercontent.com/83376913/134753036-635783c6-7c38-4829-988a-e24b72baaf3b.png">

User interaction can also be boosted by adding arrow indicators to convey the displayed options can be expanded into more sub-communities. As such: 

<img width="374" alt="Screen Shot 2021-09-24 at 6 23 57 PM" src="https://user-images.githubusercontent.com/83376913/134753283-8510087d-10d1-4b73-862c-169a33058749.png">

**Comment by lucaslcode** [comment]
I think top right is more typical
