### ISSUE TITLE
Backend doesn't check for unique username before trying to create a user

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#204]
And it seems frontend isn't always catching it

https://community.couchers.org/t/couchers-org-platform-alpha/254/9

**Comment by kalvdans** [comment]
> Of course the easiest way would be just do lowercase in the frontend and have the backend reject upper case.

I agree, that would be slightly better than lowercasing it on the backend side. The user then have a chance to see how their username really looks before creating an account.

**Comment by aapeliv** [comment]
Yeah, the frontend should lowercase the username while you type it in. I don't think it's worth implementing in the old vue frontend, but should definitely be done in the react frontend.

**Comment by kalvdans** [comment]
We already reject uppercase in the backend :) case closed. https://github.com/Couchers-org/couchers/blob/develop/app/backend/src/couchers/db.py#L44-L49

[EDIT]. No, that is after the `lower()`ing. Case opened.
