### ISSUE TITLE
press enter to send chat

### ISSUE THREAD

**Issue by wbruntra** [Couchers-org/couchers#2049]
In online chats, users will generally expect to be able to use the `enter` key to send messages (e.g. WhatsApp, Facebook Messenger). The chat function on couchers should allow this behavior.

I have created a pull request here: https://github.com/Couchers-org/couchers/pull/2048

**Comment by lucaslcode** [comment]
This needs input from the design team (I will ask). We want to encourage long-form messages (though I agree the current "bubble" design doesn't lend itself to that) so I'm not sure we should do this.

**Comment by wbruntra** [comment]
That makes sense, yes, hence the use of `textarea` instead of `input`. I agree that whether this is a good idea depends on how the chat is intended to be used. I got to the chat feature just by playing around, presumably users would have another purpose in mind.

**Comment by lucaslcode** [comment]
Further comment on the PR

**Comment by alesdvorakcz** [comment]
I am not sure if this was good idea. I was just replying to a hosting request and I accidentally send message incomplete when I just wanted to do line break. It does not feel intuitive to submit the message in textarea by hitting enter

**Comment by alesdvorakcz** [comment]
and I am not the only one
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/1890782/136792021-98f58c99-dc7b-454e-8a5f-c07a7d84584e.png">
