### ISSUE TITLE
Cut off text on profile cards on map search on mobile

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#2100]
When doing a map search on the mobile version and click on a pin, the profile preview card has text that is cut off. See below:

![Screenshot_20211017-005430_Firefox](https://user-images.githubusercontent.com/79384268/137613810-f9e2ec6c-f0aa-4ff8-bf21-59c704dd3403.jpg)

**Comment by tsuruby** [comment]
Hi @lucaslcode, may I fix this bug?

**Comment by lucaslcode** [comment]
As far as I can tell, this is actually not an issue anymore

**Comment by tsuruby** [comment]
I see, is there anything that should be prioritized that I could do?
