### ISSUE TITLE
Forgot username

### ISSUE THREAD

**Issue by ShmuelTreiger** [Couchers-org/couchers#211]
I forgot what I used to sign up, so I just signed up again. Seems a useful feature

**Comment by amdwit** [comment]
I do not understand this. So someone is at the login screen and has forgotten his username. What now?

**Comment by aapeliv** [comment]
This functionality exists in the backend as of #356 through the `ResetPassword` RPC that can be fed a username or email.

https://github.com/Couchers-org/couchers/blob/05105ac1706586d29a3bd014f02e1d21cb40b9f4/app/pb/auth.proto#L68-L70

**Comment by lucaslcode** [comment]
Closing in favour of #368
