### ISSUE TITLE
yarn install -> No such file or directory: 'install'

### ISSUE THREAD

**Issue by ohonigx** [Couchers-org/couchers#2137]
I have a fresh installation from documentation (https://github.com/Couchers-org/couchers/tree/site/app) but "yarn
install" does not work.

docker run & compose works but the last step with yarn is broken, got the source from

git clone https://github.com/Couchers-org/couchers.git

:~/couchers/app/web# yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

hope you can help, did't find any in google also find nothing here

kind Regards

**Comment by aapeliv** [comment]
Hi! Thanks for joining us and opening an issue.

To get started debuggin this, would you mind pasting the output of the following commands here:

```
node --version
yarn --version
```

Also, you can use backticks (`) for code so it's nicer to read :)

**Comment by ohonigx** [comment]
`root@couchers:~/couchers/app# node --version`

Command 'node' not found, but can be installed with:
apt install nodejs

`root@couchers:~/couchers/app# yarn --version`
0.32+git

`root@couchers:~/couchers/app# apt install nodejs`

`root@couchers:~/couchers/app# node --version`
v12.21.0
`root@couchers:~/couchers/app# yarn install`

00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

**Comment by aapeliv** [comment]
It seems you have a very old version of `yarn`, try removing that and updating to a newer one:

https://classic.yarnpkg.com/lang/en/docs/install/

**Comment by ohonigx** [comment]
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install yarn

root@couchers:~/couchers/app# yarn install
yarn install v1.22.15
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
