### ISSUE TITLE
yarn start -> Couldn't find a package.json file in "/root/couchers/app"

### ISSUE THREAD

**Issue by ohonigx** [Couchers-org/couchers#2138]
Please :-)

`root@couchers:~/couchers/app# yarn start`
yarn run v1.22.15
error Couldn't find a package.json file in "/root/couchers/app"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

`root@couchers:~/couchers/app# uname -a`
Linux couchers 5.11.0-38-generic #42-Ubuntu SMP Fri Sep 24 14:03:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aapeliv** [comment]
You need to run the `yarn` commands in `app/web`
