### ISSUE TITLE
Add profile + dropdown menu on navigation bar 

### ISSUE THREAD

**Issue by dommers-ux** [Couchers-org/couchers#2183]
Add a profile avatar + drop-down menu navigation bar. 

For example (for features live on the beta)  - 

<img width="765" alt="Screen Shot 2021-11-14 at 8 15 34 PM" src="https://user-images.githubusercontent.com/83376913/141714261-ac15239e-46c1-44eb-8cc2-e7ec1a3fcd5a.png">

This would obviously change accordingly as more features are developed.

**Comment by vrouilhac** [comment]
Hi @lucaslcode @aapeliv, i can see on the screen that the report button styles changed. Is it part of this issue, or should i leave it the same styles as it currently is ?

**Comment by vrouilhac** [comment]
![01](https://user-images.githubusercontent.com/62873665/144743469-b4d7bc2f-fca9-43e1-98e3-a898f35ebc83.png)

~~I added a condition if the user doesn't have uploaded a profile image yet, does this seems good ?~~ 

Edit: I changed and reused the one from profile page ^^'

**Comment by lucaslcode** [comment]
The report button change is something for a different PR/issue

**Comment by vrouilhac** [comment]
Hi @dommers-ux, I followed your design and i was wondering what does mean the 'Upcoming' part ? Shouldn't i rename it ? Or will this section hold future events ?

**Comment by dommers-ux** [comment]
Upcoming hasn’t been implemented yet, so I guess we can hold off on it
until then. Thanks!
