### ISSUE TITLE
Message screen: selecting name on the message header directs viewer to user profile 

### ISSUE THREAD

**Issue by dommers-ux** [Couchers-org/couchers#2187]
<img width="593" alt="Screen Shot 2021-11-17 at 8 15 03 PM" src="https://user-images.githubusercontent.com/83376913/142339017-20eb6763-7494-459d-8eab-b489aebb0127.png">

Discussed in: https://community.couchers.org/t/unable-to-click-on-profile-in-messages-please-fix-this/1605

**Comment by aapeliv** [comment]
On purpose, #1908
