### ISSUE TITLE
Fix the margins on the account settings page

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#2239]
It's embarrassing

**Comment by tsuruby** [comment]
Hi @lucaslcode may I fix that ?

**Comment by lucaslcode** [comment]
Yes please!

**Comment by dieterpankratz** [comment]
I've set up the project with option 2 (Target the preview api and backend) and now I am wondering how to authenticate locally. Can you help me out? @lucaslcode

**Comment by dieterpankratz** [comment]
Hi @lucaslcode, could you give me access rights so I can push my changes?
I get a ```ERROR: Permission to Couchers-org/couchers.git denied to dieterpankratz.
fatal: Could not read from remote repository.
```

**Comment by lucaslcode** [comment]
@dieterpankratz  Re deleted questions (sorry I don't know where else to contact you) [see here about logging in](https://github.com/Couchers-org/couchers/tree/develop/app#how-do-i-log-in-or-sign-up-when-developing) and to make a PR you can fork the repo instead of cloning

**Comment by tsuruby** [comment]
@lucaslcode thanks, will do :)

**Comment by tsuruby** [comment]
I've just opened the PR. I am not sure how to link this issue to the PR and how to request a review 😅

PR: https://github.com/Couchers-org/couchers/pull/2241

**Comment by lucaslcode** [comment]
closed in #2241
