### ISSUE TITLE
[Feature] Reconnect to your friends from CouchSurfing

### ISSUE THREAD

**Issue by svoop** [Couchers-org/couchers#2240]
In order to reconnect with friends from the ole CouchSurfing days, maybe the following could be helpful:

Even without paying, you can click on "manage your account" on couchsurfing.com and then export your data. Uploading the exported JSON could prefill the profile to some extent, but more importantly, it contains two useful pieces of information.

At the very top your numeric CouchSurfing user ID:

```json
{
  "user_data": {
    "id": 123456,
```

Further down is the list of your confirmed friends' user IDs (as last part of their profile URL):

```json
"friends": {
    "friends": [
      {
        "profile": "https://www.couchsurfing.com/users/1111"
      },
      {
        "profile": "https://www.couchsurfing.com/users/2222"
      },
```

Stored as meta data on the Coucher user, it is possible to suggest reconnect to your old friends once one of them has created an account and uploaded his CouchSurfing data dump.

**Comment by aapeliv** [comment]
Related to Couchers-org/couchers#4207.

Is it possible now to download this data without having to email CS directly? If so, we should prioritize Couchers-org/couchers#4207 as it's actually usable with little effort by normal users!

**Comment by svoop** [comment]
At least for profiles behind the paywall, it's possible to download the dump right after login and without the need to ask for it by email.

Indeed, this is a dupe of Couchers-org/couchers#4207, closing.
