### ISSUE TITLE
Red "report a problem" bug button is missing from mobile site

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#2299]
The desktop site still has the red button for reporting bugs, but for some reason it is missing from the mobile site:

![image](https://user-images.githubusercontent.com/79384268/147997869-a408bfd4-513e-4bbc-8c39-30d491bc76bf.png)

The bug reporting button should be added back since most users use our mobile site.

**Comment by nishit-g** [comment]
Hey @AllhandsNoFeet can I take this up ?

**Comment by nishit-g** [comment]
Hey @AllhandsNoFeet  will this work ? 
Do I need to keep just the bug button ?

<img width="562" alt="Screenshot 2022-01-04 at 11 54 47 AM" src="https://user-images.githubusercontent.com/32142878/148018013-beadda48-7978-49f9-a874-94529e3d483b.png">

**Comment by jesseallhands** [comment]
Thanks @nishit-g ! I'll let @lucaslcode respond as he is the frontend lead.

**Comment by lucaslcode** [comment]
That looks right, both should be there
