### ISSUE TITLE
Cicking "submit" without selecting yes/no/maybe on signup flow is possible

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#2323]
When signing up, you can click "submit" on the "have your say" page without selecting yes/no/maybe. This should not be possible. While users should be able to skip providing feedback, they should at least be forced to select yes/no/maybe (and if they select yes or maybe, provide additional information as a requirement).

This will prevent users who are frustrated when they click the button prematurely and, more importantly, will help provide the recruiting team with more relevant information (and hopefully more volunteers!)

![image](https://user-images.githubusercontent.com/79384268/148679044-3ec861cd-f7ac-47b1-9150-5a7fa632b605.png)

**Comment by aapeliv** [comment]
This is as intended, all questions should be optional. We need this to be a very low-friction flow, and can't expect everyone to answer that question.

We need to keep the signup flow as straightforward as possible so those who want to just click through are able to. It will cause friction and frustration if they click submit and then it throws them back and they have to read the question and think about it.

If we made it compulsory, we'd have to put it first and highlight it somehow, then show the other optional questions later. But the point of putting that question after the others is to allow people to first open up and think about what they care about and then hopefully after they've written something in the feedback form and though about how much couch surfing matters to them personally, they will be more open to helping out on the project itself.
