### ISSUE TITLE
"Privacy policy" is not listed in footer 

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#2399]
Although we do have the link "Terms" in our footer (see below), "Terms" is NOT synonymous with "privacy policy". To meet GDPR and CCPA requirements, we should have a conspicuous link to our privacy policy in the footer of our website (so users can find it on every page). 

![image](https://user-images.githubusercontent.com/79384268/150069017-869cc356-a862-44b6-b831-f389b39c9a98.png)

We can create a named anchor on /terms for the "Data privacy and security" section, and the "Privacy policy" link we add to the footer can point directly to the named anchor on the terms page.

**Comment by aapeliv** [comment]
Not ready yet
