### ISSUE TITLE
Remove Home tab on profile from those who are not hosting 

### ISSUE THREAD

**Issue by dommers-ux** [Couchers-org/couchers#2468]
The "Home" tab should be removed from the profiles of those who are not hosting. If it can't be removed, it should be inactive/not clickable.

The reasoning/goal is to remove irrelevant information from user profiles.

**Comment by dommers-ux** [comment]
Something should also be done to those that have "may host" or "can host", but have not completed their Hosting preferences or My home information (see default display below)...but I will open up another issue about this separately. There should be a difference between what the user has decided vs. the default display. 

<img width="736" alt="Screen Shot 2022-01-31 at 8 47 59 PM" src="https://user-images.githubusercontent.com/83376913/151906100-20c8b56e-17bd-4fe0-a11b-8745246c6755.png">
e

**Comment by aapeliv** [comment]
Folded into Couchers-org/couchers#4139
