### ISSUE TITLE
Some sites messed up while logged in

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#2485]
Blog page:
![Screenshot from 2022-02-03 14-42-32](https://user-images.githubusercontent.com/2975660/152417125-6faa4c64-1f6a-4bcf-ab55-c0c9f28788fc.png)

Footer on events:

![Screenshot from 2022-02-03 14-42-17](https://user-images.githubusercontent.com/2975660/152417148-48868633-8805-425f-a174-4dda6f4ba97f.png)

**Comment by aapeliv** [comment]
Also 404 not found:
![Screenshot from 2022-02-03 15-42-48](https://user-images.githubusercontent.com/2975660/152425532-502588c8-afe7-418c-9138-fb730ae825a4.png)

**Comment by jesseallhands** [comment]
Upon my first login after the merge, I wasn't taken to the dashboard but instead saw the signup screen:

![image](https://user-images.githubusercontent.com/79384268/152451930-2c512184-6edf-4053-b7b6-d7dd48f4c938.png)

Not sure if this is the same thing or if it should be a separate issue.
