### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by joshjm** [Couchers-org/couchers#249]
Lately trying to do a clean install of the backend is broken for me. 
logs can be seen here

https://gist.github.com/joshjm/6861c9d28779e171857cff1c59ce9db6

following the app readme.md's install instructions:
```
git clone git@github.com:Couchers-org/couchers.git
cd couchers/app
docker run --rm -w /app -v $(pwd):/app couchers/grpc ./generate_protos.sh
docker-compose up --build
```
seems to fail. 

key errors i think i am seeing are; `entr: broken inotify workaround enabled`
and `app_frontend_1 exited with code 127`

**Comment by aapeliv** [comment]
Fixed
