### ISSUE TITLE
error when running web project with old node version

### ISSUE THREAD

**Issue by wginsberg** [Couchers-org/couchers#2531]
When I tried to run the project for the first time with node 12 I got the following error

```
 1 of 1 unhandled error
Server Error
SyntaxError: Unexpected token '?'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Loader.moduleStrategy
internal/modules/esm/translators.js (140:18)
```

I solved it by running with node 16, but I think it would be nicer for the next person if we update the `package.json` with the node version required for this project.

If it sounds good I can open a PR for this, I think I just need repo permission to push my branch.

**Comment by aapeliv** [comment]
Hi @wginsberg, thanks for opening the issue. Please open a PR from a fork so I can ask the web frontend folks to review!
