### ISSUE TITLE
Web container build is slow

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#2548]
I've investigated this. It currently takes ~30 min to build the web containers which is causing an extra 20 min on the critical path.

The main reason is that we do `--cache-from` the release container, *but* we use layers which aren't actually stored in that container, so it can't cache from those.

I propose in the short term we just don't use layers.

Thoughts @lucaslcode @darrenvong?

**Comment by lucaslcode** [comment]
Do you mean remove the `FROM` bits?
I think anything is fine, I don't think we particularly have size pressure on container sizes

**Comment by aapeliv** [comment]
Yes, I think that will basically do it. Also then we can simplify the dockerfile and get rid of those bugs where the final container doesn't have all the files
