### ISSUE TITLE
Please choose a more specific place

### ISSUE THREAD

**Issue by verdie-g** [Couchers-org/couchers#2631]
https://github.com/Couchers-org/couchers/blob/f4b91b03df20e8d1cfded48ecf4f36dcc81d156a/app/web/features/search/FilterDialog.tsx#L163

It looks like regions are disabled when searching on the map. So assuming you want to go to Paris you'll get the error `Please choose a more specific place`. So I'm not sure what I'm supposed to type.
![image](https://user-images.githubusercontent.com/9092290/155847045-ca687a94-25a4-4e4a-9a7a-7d35ca08955f.png)

I've actually found a workaround:
1. Use the left search box instead of the filter dialog, the search by region works but the results are only displayed in the search result list but not on the map
2. Search for Paris, the results will appear in the list
3. Click on filter, the location is automatically input and for some reason the its `isRegion` field is `undefined` so it passes the checks
4. Add your filters such as the hosting status
5. Apply and you have the map results located to Paris

**Comment by lucaslcode** [comment]
Thanks, the real bug is that Paris is not a region and it should work, seems like only the non-dialog input is implemented correctly

**Comment by verdie-g** [comment]
I see, it's how `isRegion` is resolved that is broken
https://github.com/Couchers-org/couchers/blob/f4b91b03df20e8d1cfded48ecf4f36dcc81d156a/app/web/utils/hooks.ts#L96
the address of Paris is
```json
{
  "suburb": "Paris",
  "city_district": "Paris",
  "county": "Paris",
  "state": "Île-de-France",
  "region": "France métropolitaine",
  "country": "France",
  "country_code": "fr"
}
```
Saint-Ouen in the suburbs
```json
{
  "village": "Saint-Ouen",
  "municipality": "Amiens",
  "county": "Somme",
  "state": "Hauts-de-France",
  "region": "France métropolitaine",
  "postcode": "80610",
  "country": "France",
  "country_code": "fr"
}
```
Puteaux
```json
{
  "town": "Puteaux",
  "municipality": "Nanterre",
  "county": "Hauts-de-Seine",
  "state": "Île-de-France",
  "region": "France métropolitaine",
  "postcode": "92800",
  "country": "France",
  "country_code": "fr"
}
```
so they are all not considered cities.

We could try listing all possible keys for cities: village, town, city_district but that's not bullet proof. An alternative is to make Nominatim only return cities using the `city` parameter. E.g. https://nominatim.openstreetmap.org/search?format=json&city=Paris.

So I would replace the `disableRegions` boolean with a `onlyCities` boolean. What do you think?

Here is a draft: https://github.com/Couchers-org/couchers/pull/2634.

**Comment by lucaslcode** [comment]
Thanks for looking into this! Sorry I took so long to reply.

The problem is using city to search excludes non-cities which the user might enter, like "Euston station" or even "123 Fake Street, New York" might not work.

How about expanding this line: ` isRegion: !("city" in result.address), ` to include town, village, city_district and any others that exist (is there a list?)

**Comment by verdie-g** [comment]
Yes I was thinking if that made sense to search by street.

The list of possible keys return by nominatim can be found here https://nominatim.org/release-docs/latest/api/Output/#addressdetails. `municipality, city, town, village
` doesn't sound enough since Paris doesn't have any of these fields. Maybe we soulh also add `city_district, district, borough, suburb, subdivision`.
