### ISSUE TITLE
Smart link detection isn't aware of certain utf8 characters

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#2646]
Typing `Hello there！couchers.org` will give this: Hello [there！couchers.org](https://there！couchers.org)

This is because ！ is a full-width exclamation mark, a UTF-8 character which is common in some languages (ie. Chinese) to end sentences with no space. We need to detect these characters in our link-creation regex

**Comment by lucaslcode** [comment]
Current regex from `Linkify.tsx`

```
const urlRegex = () => {
  const protocol = `(?:https?://)?`;
  const auth = "(?:\\S+(?::\\S*)?@)?";
  const host = "(?:(?:[a-z\\u00a1-\\uffff0-9][-_]*)*[a-z\\u00a1-\\uffff0-9]+)";
  const domain =
    "(?:\\.(?:[a-z\\u00a1-\\uffff0-9]-*)*[a-z\\u00a1-\\uffff0-9]+)*";
  const tld = `(?:\\.)[a-z]{2,}`;
  const path = '(?:[/?#][^\\s"]*)?';
  const regex = `(?:${protocol}${auth}(?:${host}${domain}${tld})${path})`;
  const result = new RegExp(`(${regex})`, "ig");
  return result;
};
```

**Comment by HankAviator** [comment]
Two solutions:
1. Completely remove detection support for non-ASCII characters in the link. This will render IDN completely unusable but major browsers will encode non-ASCII characters before it's copied from address bar, and decode when copied to it. While the chance of manually typing the link in non-ASCII is low, this won't look as bad as it seems.
2. ~~Host must begin with an ASCII character. This will mitigate the shortcomings mentioned in solution 1, and as IDNs are rare, even rarer that the whole URL is in non-ASCII characters, this should be good enough. Besides, path will be able to contain non-ASCII characters - not quite a good practise.~~
    * current regex doesn't recognize IDN as TLDs. Let's go solution 1.

**Comment by HankAviator** [comment]
there is a relevant issue: say

`couchers.org/profile是你的档案` will take the Chinese words as a part of path. Should this be solved too?

**Comment by HankAviator** [comment]
The current commit already addresses with all non-ASCII characters and ready to be reviewed @lucaslcode
