### ISSUE TITLE
City discussion threads - backend

### ISSUE THREAD

**Issue by kalvdans** [Couchers-org/couchers#269]
As discussed on the development meeting 28 october, we need discussion threads tied to a location in the backend. The idea is to keep global discussions on https://community.couchers.org/ and local discussions in the app.

Requirements:
* A topic should be tied to a geographic location
* Replies to each topic should be threaded, so that you can reply to a reply etc.
* markdown without images should be allowed.

Here's a scetch on how it could look like in a mobile app:

![Screenshot_2020-10-28_22-52-05](https://user-images.githubusercontent.com/1099712/97501037-ea211400-1970-11eb-80ca-ce46dae724e8.png)

@aapeliv

**Comment by lucaslcode** [comment]
> - markdown without images should be allowed.

That should be done in frontend imo

**Comment by kalvdans** [comment]
> > * markdown without images should be allowed.
> 
> That should be done in frontend imo

We don't want some frontends to show images and some not. But a backend not touching the text and stating "no images" in the protocol definition probably works well to start with.

**Comment by kalvdans** [comment]
I need help to come up with a good pagination algorithm in the API. I gave it a thought but it came up super complicated 🤓 
I think I start off just sending all messages under a topic, where each messages have a parent pointer to form a Directed Acyclig Graph.

**Comment by lucaslcode** [comment]
What have you done so far?

I would have done the easy way, with a parent id self joining a set number of times. Then if you want to go deeper, the user would click a "continue this thread link" which does it again but from the deeper comment. 

But I just saw an [interesting method here](https://www.sqlteam.com/articles/more-trees-hierarchies-in-sql) that uses a second table to store the tree structure, it seems quite nice.

**Comment by kalvdans** [comment]
> What have you done so far?

Nothing, just thinking ;)

> I would have done the easy way, with a parent id self joining a set number of times. Then if you want to go deeper, the user would click a "continue this thread link" which does it again but from the deeper comment.

So the client asks, give me all messages rooted at root node _n_, with maximum depth _d_? Without any limit of the number of messages?

**Comment by lucaslcode** [comment]
Maybe the pagination could work the same as the messages/host requests, where it the client gives a *last_message_id* and the server returns the *x* messages after that. 

The depth might have to be hard coded unless you can do something really clever with the SQL orm and a loop!

**Comment by lucaslcode** [comment]
In that case, maybe the separate table for tree structure is a better approach...

**Comment by kalvdans** [comment]
> Maybe the pagination could work the same as the messages/host requests, where it the client gives a _last_message_id_ and the server returns the _x_ messages after that.

That would be a disaster, giving replies without the messages they reply to.

**Comment by lucaslcode** [comment]
> That would be a disaster, giving replies without the messages they reply to.

I see what you mean. On Reddit, there are separate "get more replies" links for each level of nesting.

![Screenshot](https://user-images.githubusercontent.com/32044095/98665019-05156000-2343-11eb-9793-f8a5948e677f.jpg)

If you're not keen on the separate tree table, maybe having a depth column with the comments could make it possible?

**Comment by kalvdans** [comment]
So require four API calls to show those 6 messages. That's good. I thought about designing the API first and then the storage model.

**Comment by lucaslcode** [comment]
I thought the messages in the screenshot could be one API call (the original one with no arguments except the topic id), and each of those "see more" links would be another.

**Comment by kalvdans** [comment]
Ok, so the API would be something like this:

```
/* Get the @n messages posted after the message in @anchor,
 searching recursively both in the children of @anchor and in
 continuation of the subthread in which @anchor is. For a tree

topic
+ a
| + c
| | ` e
| + d
| | + k
| | ` l
| ` f
|   + i
|   + j
+ b
| ` g
` h

the call get_messages_posted_after(d, 4) will return [ f, i, j, k ]
*/
get_messages_posted_after(message_id anchor, int n) -> (list of (message_id, message_text, posted_date, author, nr_immediate_children, parent_id))
```

**Comment by aapeliv** [comment]
Is it bad if we auto-collapse at the start and every time you want to go deeper in the tree, you haveato issue another API call? I.e. what if we start with just one call:

* `get_latest_messages_in_thread(topic, last_message, n)`: gets the last n children (and count of their immediate children) of given topic after `last_message`

e.g. on @kalvdans' example above: 

```
get_latest_messages_in_thread('topic', 0, 50)=[('a',3),('b',1),('h',0)]
get_latest_messages_in_thread('a', 0, 50)=[(c,1),(d,3),(f,2)]
```

Just a suggestion? I think this would be an easy starting point implementation-wise?

**Comment by lucaslcode** [comment]
Certainly would be easier but I think @kalvdans 's idea is nicer behaviour. Doing only one level at a time could end up with a lot of calls that rely on previous calls in the client.

**Comment by kalvdans** [comment]
In the latest discussion, we limit discussion to two levels, which will simplify the API. I will come up with a concrete API suggestion in the two following days and implementation in a week.

**Comment by kalvdans** [comment]
I will close the issue now since the PR is merged. Some more work is needed to stitch it together with the pages, but that could be done together with the frontend under https://github.com/Couchers-org/couchers/issues/543
