### ISSUE TITLE
Rename "Filters" to "Search" on mobile

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#2809]

**Comment by jesseallhands** [comment]
![Screenshot_20220425-153353_Firefox](https://user-images.githubusercontent.com/79384268/165100204-20cda1fd-2a6b-4b82-a121-883988ff3a40.jpg)

**Comment by guillermodlpa** [comment]
Hi folks! We spoke about this one some weeks ago, and since I see that @lucaslcode couldn't pick it up yet, I'll propose a pull request for this since it's quite a small change. Hope that's ok!
