### ISSUE TITLE
Link not being sent upon requesting password be reset

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#2857]
3 different users have reported that they are not receiving a link when they request their password be reset (they confirmed checking their spam folders). I tested it using https://couchers.org/password-reset and it worked for me, so perhaps this could be an intermittent issue?

**Comment by jesseallhands** [comment]
@aapeliv @AndrewFarley Can this be closed?

**Comment by AndrewFarley** [comment]
I think we've determined it is okay, re-open if needed
