### ISSUE TITLE
Update languages.json with missing languages

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#2873]
Let's use this issue to keep track of languages that need to be added to languages.json and bulk-process them once we have a longer list:

#### ISO 639-3 code | ISO Language name
bre | Breton
san | Sanskrit
gle | Irish
gla | Scottish Gaelic
glv | Manx
cor | Cornish
tet | Tetum
tok | Toki Pona

**Comment by aapeliv** [comment]
Was this done @jesseallhands ?

**Comment by jesseallhands** [comment]
@aapeliv , not that I'm aware of. This ticket is a running list of outstanding language additions

**Comment by jesseallhands** [comment]
I can confirm this has not been taken care of. Should be a quick fix so I updated as such.
