### ISSUE TITLE
merge with BEWELCOME

### ISSUE THREAD

**Issue by ghost** [Couchers-org/couchers#2874]
I don't understand why couchers exists, when BeWelcome.org was created due to couchsurfing.com commercialization and was an opensource replacement?

Why create Couchers when BeWelcome exists? Why not join your efforts together and make BeWelcome a better replacement rather than reinventing the wheel and taking "surfers" from the other site?

Work together, not separate.

**Comment by aapeliv** [comment]
Hi @dimensionc132, welcome to Couchers.

This topic is better suited for the community forum, and there are already some discussions on it there:

https://community.couchers.org/search?q=bewelcome
