### ISSUE TITLE
Feature: Send email upon Event activity

### ISSUE THREAD

**Issue by AndrewFarley** [Couchers-org/couchers#2878]
To help user-engagement we greatly need to increase the number of emails (notifications) we send to our users so they are included in the conversation and re-engaged to use the site.

This feature request would request the following...
• Upon an new event being created email all users that are in that community
• Upon an update to this event (sent max of once per-day) to all attendees of the event
• X hours before an event's start time, suggested 1 hour hardcoded for now, perhaps adjustable in the future

Ideally, this email will have an .ics attachment for ease of automated integrations with calendaring systems, google calendar, etc.

**Comment by ItsiW** [comment]
Would v1 include some sort of event reminder as well? Either an .ics email when hitting attending, or an email 24 hours before the start of event?

Or would we want to leave that for v2?

**Comment by AndrewFarley** [comment]
Note: Per feedback/discussion in Slack updated the feature request's specifications
See: https://couchersorg.slack.com/archives/C025XSM3NVB/p1651611905607559

**Comment by aapeliv** [comment]
This is done
