### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#289]
These are done by old-fashioned polling for now:

```
rpc Ping(PingReq) returns (PingRes) {
  // Pings the server for updates and basic user info
}

message PingReq {}

message PingRes {
  User user = 1;
  uint32 unseen_message_count = 2;
  uint32 unseen_host_request_count = 3;
  uint32 pending_friend_request_count = 4;
}
```

**Comment by darrenvong** [comment]
I can probably do this next. Not sure how this would look with our current design though - put it on the tabs of the message page maybe?

**Comment by lucaslcode** [comment]
Yeah and maybe a badge on the Nav bar link for messages/connections as relevant

**Comment by darrenvong** [comment]
Todo (so I don't forget): 
- [x] Use `MarkLastSeenGroupChat` so messages notification will go down
- [x] Use `MarkLastSeenHostRequest` so host requests notification will go down
