### ISSUE TITLE
Friends page

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#291]
Should be able to add friends from a user's profile, but the friends page is where you accept requests and see you friends list.

Relevant protobuf definitions from api.proto:

```
syntax = "proto3";

package org.couchers.api.core;

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";

service API {
  ...

  rpc SendFriendRequest(SendFriendRequestReq) returns (google.protobuf.Empty);

  rpc ListFriendRequests(google.protobuf.Empty) returns (ListFriendRequestsRes);

  rpc ListFriends(google.protobuf.Empty) returns (ListFriendsRes);

  rpc RespondFriendRequest(RespondFriendRequestReq) returns (google.protobuf.Empty);

  rpc CancelFriendRequest(CancelFriendRequestReq) returns (google.protobuf.Empty);

  ...
  }
}

...

message SendFriendRequestReq {
  uint64 user_id = 1;
}

message FriendRequest {
  uint64 friend_request_id = 1;

  enum FriendRequestStatus {
    // these are the only two states that a user will see
    PENDING = 0;
    ACCEPTED = 1;
  }

  FriendRequestStatus state = 2;

  uint64 user_id = 3;
}

message RespondFriendRequestReq {
  uint64 friend_request_id = 1;

  bool accept = 2;
}

message CancelFriendRequestReq {
  uint64 friend_request_id = 1;
}

message ListFriendRequestsRes {
  repeated FriendRequest sent = 1;
  repeated FriendRequest received = 2;
}

message ListFriendsRes {
  repeated uint64 user_ids = 1;
}

...
```

To-do:
- [ ] SendFriendRequest
  - [x] implementation
  - [x] tests
- [x] ListFriendRequests
- [x] ListFriends
- [x] RespondFriendRequest
- [x] CancelFriendRequest

**Comment by darrenvong** [comment]
@lucaslcode Does this overlap with the user page stuff you did already that could be re-used here? I might pick this next :D

**Comment by lucaslcode** [comment]
This is more a page for accepting/rejecting requests, but maybe it should include friend info and a "send friend request" link on the user page

**Comment by darrenvong** [comment]
I see, doesn't look like there's even a mid-fi design for this yet? Might have to roll along what it looks like on the alpha as a starting point

**Comment by lucaslcode** [comment]
Yes, the plan is to later refactor friends into "connections" which are partly automatically added (like when you accept a host request)

**Comment by amdwit** [comment]
Isn't this the design? https://couchers.invisionapp.com/console/share/2W1JUDHBZ7/483411816
