### ISSUE TITLE
Disallow emojis in display name

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#2912]
Some users like /user/superkers are using emojis in their display name which causes problems with search / recognition (eg: if someone only uses emojis for their display name) and further enables unwanted behavior (ideally all users would use their real name as their display name).

Emojis are already disallowed for username and should also be disallowed for display name.

**Comment by lucaslcode** [comment]
In what way does it cause problems? What if my name is 鄭潞凱?

**Comment by jesseallhands** [comment]
The problem is when someone uses only one or 3 emojis like "🤡🤡🤡"  as their display name.

**Comment by aapeliv** [comment]
I'm going to say we shouldn't implement this in the codebase.

1) It's elaborate whack-a-mole. We currently allow basically any non-empty unicode string which allows people to use a variety of character sets. The way emojis are defined is as some set of characters. We'd need to allowlist/blocklist characters which will get very complicated.

2) What's the impact of this? As Lucas points out: if we can't deal with emojis, we probably can't deal with non-latin alphabets either!


I think better to deal with this case by case. We could build a general purpose tool to force users to change different parts of their profile. I think the ROI isn't there to implement this right now.
