### ISSUE TITLE
message text in notification emails

### ISSUE THREAD

**Issue by wginsberg** [Couchers-org/couchers#2925]
Notification emails for chat messages sometimes includes the message text itself, but not always.

| email with message text | email without message text |
| --- | --- |
|  ![Screen Shot 2022-05-15 at 12 11 31 PM](https://user-images.githubusercontent.com/12486723/168482761-c3e27611-d208-4cc1-8ba9-f50b9b4553a8.png) | ![Screen Shot 2022-05-15 at 12 13 16 PM](https://user-images.githubusercontent.com/12486723/168482759-3be68501-942c-4c76-91ad-d9c7c9f8c3ec.png)

I think it would be nicer if you could always read the message in the email. Is there a reason why it's sometimes not included?

**Comment by jesseallhands** [comment]
this should be resolved now
