### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by jpmonette** [Couchers-org/couchers#296]
The basics of messages - displaying a list of chats and the latest messages/members involved, showing messages and control messages in a chat, updating the last seen message, scrolling to load more messages, message sending, creating new chats

Uses api calls in [conversations.proto](https://github.com/Couchers-org/couchers/blob/develop/app/pb/conversations.proto)

[Vue implementation here](https://github.com/Couchers-org/couchers/blob/develop/app/frontend/src/views/Messages.vue)

**Comment by darrenvong** [comment]
Is this pretty much done except for pagination?

**Comment by lucaslcode** [comment]
Think so! Do you want to do that?

**Comment by lucaslcode** [comment]
Saw you're doing bug reports, I'll work on pagination
