### ISSUE TITLE
Group Chat functions

### ISSUE THREAD

**Issue by jpmonette** [Couchers-org/couchers#297]
Depends on Couchers-org/couchers#296 

Group chats are treated the same as DMs when displaying, but have extra functions such as inviting/removing chat members, leaving, changing chat settings and adding/removing admins

**Comment by darrenvong** [comment]
@amdwit aren't you also working on this at the moment?

**Comment by amdwit** [comment]
Indeed.

**Comment by lucaslcode** [comment]
closed in #530
