### ISSUE TITLE
Make location suggestions available immediately [ Map search ]

### ISSUE THREAD

**Issue by dommers-ux** [Couchers-org/couchers#3018]
Right now, the user has to select the search icon or press enter to make the list available. 
If possible, the list should be available and change accordingly as the location is spelled out.

Current Model: 

<img width="529" alt="Screen Shot 2022-06-15 at 5 54 18 PM" src="https://user-images.githubusercontent.com/83376913/173961768-9bf9f390-6b0f-46b2-801d-fd3fdbdf0c03.png">

-----

<img width="638" alt="Screen Shot 2022-06-15 at 5 54 44 PM" src="https://user-images.githubusercontent.com/83376913/173961778-5cf72ddd-c794-45f1-8c13-40d0f8005cc7.png">

**Comment by aapeliv** [comment]
This is against the TOS of hosted Nominatim instance we're using, that's why we can't do it :/

https://operations.osmfoundation.org/policies/nominatim/

**Comment by dommers-ux** [comment]
:(
