### ISSUE TITLE
TS issues with AuthInterceptor

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#305]
See error message here: https://gitlab.com/couchers/couchers/-/jobs/860814434

This is because the TS declarations are wrong for `unaryInterceptors` (they're typed as `string: string` or whatever, which is wrong). In vue we got around this with a bunch of `@ts-ignore` (+ `prettier-ignore` because the lines got too long and it started wrapping them, breaking the `ts-ignore`... a royal mess):

https://github.com/Couchers-org/couchers/blob/7cf44ae274d8affe360a781e299ddaf33cc8af5a/app/vue/src/api.ts#L17-L21

This blocks the build from working

**Comment by lucaslcode** [comment]
Hey I seem to remember fixing this when I was experimenting with other
things by adding something like `format: "binary"` to the `opts`.

**Comment by aapeliv** [comment]
Actually this seems to have been fixed upstream https://github.com/grpc/grpc-web/issues/982

**Comment by aapeliv** [comment]
Trying a fix here: https://github.com/Couchers-org/grpc/pull/2
