### ISSUE TITLE
Organise storybook

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#308]

**Comment by amdwit** [comment]
Components like the Avatar, Textfield and others can be put into storybook one by one.

**Comment by lucaslcode** [comment]
@andreaowu has pointed out components are disorganised and there's risk of duplication of work / lack of clarity.

I am thinking to organize storybook like this:

# Components

## Small

- Button
- Textbox
- ScoreBar (?)
- Smaller components/our versions of Mui Components

## Large

- UserSummary
- Dialog
- Map
- Other "larger" pieces of UI than appear across different pages
- I realize the distinction may be a bit blurred

# 1. Public Profile

Components specific to that page

# 2. Messages

...

# 3-x. Other pages in the figma design

...
