### ISSUE TITLE
Possibility to import Couchsurfing exported data

### ISSUE THREAD

**Issue by Rohlik** [Couchers-org/couchers#3272]
Hey there 👋🏽,
I believe that most of Couchers users come from Couchsurfing and as you maybe know, you can export your data from Couchsurfing as a json.
To make registration process easier for newcomers it would be nice to have possibility to import that json 🗃️ into you profile (in profile settings or during registration process) and populate **some** its data like "Travelled to", "Occupation", "Education", etc..

What you think?

**Comment by aapeliv** [comment]
Yes, it'd be great. Tracked here: #4207
