### ISSUE TITLE
Using materialized views to cache results

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#3274]
@kalvdans: what do you think about using [postgres materialized views](https://www.postgresql.org/docs/current/rules-materializedviews.html) to cache some computations in the backend? We can then have a background job that refreshes the materialized view on a schedule, say every few minutes.

In particular, currently every time you load the front page, it does several full table scans through users in order to count the number of members per community! We could create the following materialized view:

```sql
CREATE MATERIALIZED VIEW cluster_subscription_counts AS
SELECT cluster_subscriptions.cluster_id, count(*)
FROM cluster_subscriptions
LEFT OUTER JOIN users
ON users.id = cluster_subscriptions.user_id
WHERE NOT (users.is_banned OR users.is_deleted)
GROUP BY cluster_subscriptions.cluster_id;
```

Then in a background thread run

```sql
REFRESH MATERIALIZED VIEW cluster_subscription_counts;
```

I know we agreed to avoid caching where possible, but we're getting to a point where we can't do multiple table scans all the time. I think using the postgres built-in functionality would be a great choice and avoid a lot of caching pitfalls!

**Comment by kalvdans** [comment]
Do you have enough many indices? It should be possible to extract statistics without linear searches.

**Comment by aapeliv** [comment]
How would that work? I am not sure, especially with a join across users.

**Comment by aapeliv** [comment]
Partly done
