### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#336]

**Comment by amdwit** [comment]
Is a design available? Maybe a picture of someone looking under the cushions of a couch?

**Comment by blackpandan** [comment]
can i be assigned to this issue?

**Comment by aapeliv** [comment]
Yes @blackpandan, please go ahead! Let me or @lucaslcode if you need anything to get started.

**Comment by blackpandan** [comment]
thanks am grateful

**Comment by blackpandan** [comment]
most of the feature pages are written in react, but i use vue?, how do i go about it

**Comment by lucaslcode** [comment]
It will have to be in react I'm afraid! If you feel up to it, there are [lots of similarities](https://sebastiandedeyne.com/react-for-vue-developers/) and [great resources to learn](https://reactjs.org/tutorial/tutorial.html).

**Comment by blackpandan** [comment]
alright guess I will have to learn react
