### ISSUE TITLE
I don't get confirmation mail

### ISSUE THREAD

**Issue by Nimetakasutaja** [Couchers-org/couchers#3427]
I tried several times to join Couchers, but I never get the confirmation mail. I don't filter anything on server's side, only locally, so it was not filtered as spam or anything similar, I just did not get anything from Couchers at all. I aksed about the issue via the "report a problem" form, but no answer, no mail... nothing.

**Comment by aapeliv** [comment]
What's your email address? Or if you don't feel comfortable writing it here, could you email it to me at `aapeli` at our domain, please?

**Comment by Nimetakasutaja** [comment]
Hei, Aapeli! Lähetin sulle meilin, mutten ole varmaa, saitko vai et. Eli I wrote you a mail, I am not sure if you got it or not.

**Comment by aapeliv** [comment]
Okay, I had a look. Looks like an email to that address bounced on 2023-01-07T19:02:49.490000-05:00; so it was automatically added to the SES suppression list.

I removed you off the list and tried resending the verification email. Check if you got it now.

**Comment by Nimetakasutaja** [comment]
Kiitos! Olen jo Coucherissa!
