### ISSUE TITLE
Not having an avatar should return an empty `avatar_url`

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#350]
Currently if a user does not have an avatar, we return an awful [`default.jpg`](https://user-media.coucher.org/media/img/avatar/default.jpg).

I believe the backend should return an empty string which is detected in the frontend and replaced with the user's initials or something else sensible. Is that right @lucaslcode?

**Comment by amdwit** [comment]
The frontend already shows the initials in case of no avatar. So the only thing that needs to be done is not sending the default anymore.
