### ISSUE TITLE
Implement style according to uiux minutes

### ISSUE THREAD

**Issue by amdwit** [Couchers-org/couchers#355]
The design team decided on the following:

https://docs.google.com/document/d/17xF1IFg9DijaoG7FqjECfsTLjVMV-SJhMlaT_77LV34/edit#heading=h.40n37oq105iv

We can implement this using theme/components and css.

**Comment by navandstokes** [comment]
- [x] 24px margins
- [x] 8px grid
- [x] no rounded tabs
- [x] buttons rounded 20
- [x] text field rounded 10
- [x] icon sizes 24x24 or 20x20
- [x] h1 24px b, h2 20px b, h3 16px b
- [x] body 14px
- [x] small elements 10px
- [x] buttons/CTA uppercase not b

Not sure about these. Some are not applicable yet. 
- names 14px b
- tags 14px
- links 14px underlined
- font divider 2x space / 2x space
