### ISSUE TITLE
Password requirements

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#377]
We need *some* kind of password requirements. At the moment you can actually just set an empty string as your password.

**Comment by Almenon** [comment]
Given that couchers does not store financial information i'm presuming we're aiming for MVP on this? Is checking if length >= 8 characters good enough for the first draft? It would also be easy to throw in a check for the top 2 [most common bad passwords ](https://nordpass.com/most-common-passwords-list/)cause why not (password != "password", and password != "12345678"). Should probably make "couchers" invalid too cause you know someone is going to use that 😂 

Eventually we would want to implement https://github.com/dropbox/zxcvbn in the frontend, as it would be easier and more secure than rolling our own strength checker.

Relevant: https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls

**Comment by kalvdans** [comment]
Sounds good to me to have a basic test in the backend and stricter tests in the frontend.

**Comment by aapeliv** [comment]
Yeah, I guess the minimum that's needed at the moment is a min and max length check. Something like 8 to 256 should be fine.

The other nice thing would be to try the password against the HIBP service as linked in OWASP. I looked around for a nice python package for doing this locally, but it seems the dataset is quite large and there's no good implementation.

**Comment by kalvdans** [comment]
> The other nice thing would be to try the password against the HIBP service as linked in OWASP. I looked around for a nice python package for doing this locally, but it seems the dataset is quite large and there's no good implementation.

11 GB yes, and counting. It's a bit more than 7 MB for good old [cracklib](https://github.com/cracklib/cracklib/tree/master/src) :) If we connect to an external service for password scoring, I think it is better that the frontend does that.

**Comment by Almenon** [comment]
Are we planning on having a option to create a password when you sign up? I'm wondering if the code to check the password security should be put in a function so it can be called by both the create and change password flow

**Comment by aapeliv** [comment]
Probably better if it’s a standalone utility function.
