### ISSUE TITLE
[bug] uppercase letter in the email make the email not findable

### ISSUE THREAD

**Issue by bakeiro** [Couchers-org/couchers#3934]
self describing issue (see picture attached)

![image](https://github.com/Couchers-org/couchers/assets/16777161/13d265b9-7132-4afc-b36d-cda8f92df447)

**me as a user:**
- I want that if the email/username field contains an email (field findable in the database) it shouldn't matter whether it has an uppercase letter or not.

**tasks to do:**
- Fix it :)

**Comment by developerHobday** [comment]
![image_2024-03-13_160452234](https://github.com/Couchers-org/couchers/assets/54797462/b559fce4-a46a-404e-8159-39d88a19f4d6)
This issue does not seem to exist anymore.  I triggered a reset password with my email capitalized, and I got the reset password email.

**Comment by bakeiro** [comment]
I think the same... I was a bit skeptical about this issue, but someone did [this PR](https://github.com/Couchers-org/web-frontend/pull/398).  
it's pending to be checked, I can double check this
