### ISSUE TITLE
[map] create a filter to return only users with a complete profile

### ISSUE THREAD

**Issue by bakeiro** [Couchers-org/couchers#3978]
When I search for a destination it is usually full of profiles that are empty, I as a user would like to be able to see only the profiles that have a photo/description.

I would like to make a toggle in the filter modal that makes the backend return only the profiles that have a complete profile.

### Where
![image](https://github.com/Couchers-org/couchers/assets/16777161/a586550b-1081-4ab4-8c8d-617824dbc43f)

### Reference
![image](https://github.com/Couchers-org/couchers/assets/16777161/b25d2cfc-5683-4e35-927e-9c948f357352)

### Task
Make the backend to return only complete profiles when the parameter `only_complete_profiles` was sent by the frontned

**Comment by Krishnag09** [comment]
@bakeiro - could you please assign this to me and also give me access to push?

**Comment by bakeiro** [comment]
Assigned :), for a PR you can fork the repo and do the PR to this PR, add me as reviewer if you needed it :)

**Comment by bakeiro** [comment]
btw, this is a backend issue, the pictures where for the frontend part

**Comment by Krishnag09** [comment]
> btw, this is a backend issue, the pictures where for the frontend part

- - Yes but do i also need to add the front end part since that option is not there to select?
- - also i am following the dev guideline which says to create branch off develop and name it as per issue, push it as PR.

**Comment by bakeiro** [comment]
sure, thing is, this is the backend repository, so it's a backend issue, I posted the pics as reference, but a separated frontend issue will be needed as well (it's just the backend issue goes first)

basically we need that when the user sends that parameter, backend sends only 'complete' profiles, by complete I mean that empty profiles display this message (I don't know the logic behind this message but it's in the code)
![image](https://github.com/Couchers-org/couchers/assets/16777161/615814e0-e133-4b01-bb42-c896ec203974)

and yeah about the dev guideline you are right (but for me more important it's the code ;) )

**Comment by Krishnag09** [comment]
got it, do you know how to get access to repo? I submitted the volunteer form on the website with git handle but is there any other way?

**Comment by Krishnag09** [comment]
@bakeiro @aapeliv @lucaslcode - could you please grant me the contributor access to make these changes?

**Comment by bakeiro** [comment]
I sent you an email :)

**Comment by bakeiro** [comment]
@Krishnag09 
you can still do the fork and the PRs you don't need to be a contributor to do the PRs :) [anyway I contact you ;)]

**Comment by Krishnag09** [comment]
@bakeiro - added new pr - https://github.com/Couchers-org/couchers/pull/3993
