### ISSUE TITLE
[events] create the API endpoints for the new events page

### ISSUE THREAD

**Issue by bakeiro** [Couchers-org/couchers#3989]
### Description.

I as a frontend developer:  
I am going to develop a brand new event page, for this I need several endpoints in order to display all the information. Some endpoints could exist, others would need to be created.

Endpoints needed:

- Events of the user's communities.
- Events in a specific location.
- All online events
- Events created by the current user
- Events joined by the current user
- Events created or participated in by the current user.

### Pending tasks:
Check which ones exist and which ones need to be created, then proceed to create the necessary endpoints (task can be split into smaller ones if needed).

Image as reference
![image](https://github.com/Couchers-org/couchers/assets/16777161/8af9497c-c6d1-4efc-bcda-7844b02da031)

**Comment by Krishnag09** [comment]
i can work with you on this. @bakeiro once @aapeliv adds me to the repo as contributor.  And yes we should break this into smaller tasks starting with event creation and event search.

**Comment by aapeliv** [comment]
Some of these exist already:



>  * Events of the user's communities.
> 
`ListMyEventsReq` with `my_communities`

>  * Events created by the current user
> 

`ListMyEventsReq` with `organizing`

>  * Events joined by the current user
> 
`ListMyEventsReq` with `attending`/`subscribed`

>  * Events created or participated in by the current user.
>
`ListMyEventsReq` with `attending`

**Comment by bakeiro** [comment]
@aapeliv do we have an endpoint for the events in a certain location?

**Comment by spreeni** [comment]
@bakeiro There currently is not an endpoint for this. Would you want this for the "Near you" tab? I mean it would be fairly easy to show events in a certain radius around a location, but this would not be very flexible against city size for example.

What exists are events on the community page, so I guess you could map a location to a community and then take these events. But communities are of course not exhaustive.

**Comment by bakeiro** [comment]
about taking events from communities and showing them as if they were from the location you are looking for, it seems confusing to me... I don't think the user understands that, besides, in theory it is possible to do events from one city (barcelona) but in another community (madrid).

**Comment by bakeiro** [comment]
I think the best is simply by location, for example, the user has a location, and it is searched in 50KM around (or 75km I do not know, I guess you can use a large number to avoid not showing events in cities with large areas?)

**Comment by bakeiro** [comment]
also, I was thinking about replacing 'near you' by 'location' so user can specify the location they want.

**Comment by spreeni** [comment]
@bakeiro I submitted a PR for event search by location (by circle, community area or viewport) similar to the user search. Maybe you can have a look if any filter flag is missing for what you had in mind.

https://github.com/Couchers-org/couchers/pull/4590

**Comment by aapeliv** [comment]
#4467

**Comment by spreeni** [comment]
Closing this as this should be resolved with https://github.com/Couchers-org/couchers/pull/4590 in the `EventSearch`

According filters to the above mentioned endpoints:
- Events of the user's communities.
  - via `my_communities` filter
- Events in a specific location
  - via `search_in` filter
- All online events
  - via `only_online` filter
- Events created by the current user
  - via `only_online` filter
- Events joined by the current user
  - via `attending` filter
- Events created or participated in by the current user.
  - via `organizing`/`attending`/ `subscribed` filters
