### ISSUE TITLE
[map] centralize the API calls in the backend

### ISSUE THREAD

**Issue by bakeiro** [Couchers-org/couchers#4012]
### WIP

call the nominatim API calls from the backend (so we can cache is later)

to be done after [this issue](https://github.com/Couchers-org/couchers/issues/4011)

**Comment by aapeliv** [comment]
We might get rate-limited if we do this. Why would you like to do it?

**Comment by bakeiro** [comment]
I though that... maybe just send to the server to cache in order to scale better in the future, this stills WIP
