### ISSUE TITLE
Fill database with dummy data

### ISSUE THREAD

**Issue by amdwit** [Couchers-org/couchers#406]
It is important to know what we want to use our dummy data for.

I need it for testing and demoing groupchats
So I need some users and a lot of very diverse groupchats filled with messages.
So for me it is better to generate most of it by hand. Maybe many messages could be generated.

For the maps it might be handy to create groups of users in different cities.

So what tools are good for generating texts/addresses/personal data ?
We could use:
https://www.generatedata.com/

**Comment by kalvdans** [comment]
It could also be used to check for performance issues as we scale up.

**Comment by aapeliv** [comment]
> It could also be used to check for performance issues as we scale up.

This is very useful. There's already some inefficient queries at the moment that ought to be fixed up. (Or require adding indexes, etc)

**Comment by aapeliv** [comment]
@amdwit: is resolved now with #424?
