### ISSUE TITLE
Filter for profile completeness

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#4080]
In Couchers-org/couchers#4002, @Krishnag09 introduced a switch to hide incomplete profiles in search. This needs a frontend switch/toggle/whatever to make it possible for users to tick it.

**Comment by bakeiro** [comment]
this was already done in the backend if I'm not wrong right? there is a pending frontend ticket for implementing the needed changes

**Comment by aapeliv** [comment]
Yes, this is the frontend ticket. Or is there another one?

**Comment by bakeiro** [comment]
I already have https://github.com/Couchers-org/couchers/issues/4090 :)
