### ISSUE TITLE
[map] search in map based on viewport

### ISSUE THREAD

**Issue by bakeiro** [Couchers-org/couchers#4081]
### WIP

Map should refresh it's content as the user moves, or having a 'search here' button

**Reason:**  
we need to limit the users showed on map, so, the more zoom the user does, the new users he discovers (to make a solution that scales)

**Comment by schradert** [comment]
Frontend implementation for #4513

**Comment by aapeliv** [comment]
Part of #4129

**Comment by bakeiro** [comment]
this button
![image](https://github.com/Couchers-org/couchers/assets/16777161/d065239b-8d3b-4ae5-ae32-c766aa68c9ff)
