### ISSUE TITLE
Languages and regions lived/visited

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#409]
We need a way to choose languages consistently to be able to filter well (rather than allowing freeform choice).

**Comment by Almenon** [comment]
Language datasets: 

https://en.wikipedia.org/wiki/List_of_language_names has language names in english and their own names
https://datahub.io/core/language-codes just english names

How were you thinking of implementing this on the frontend-side? That might influence how the backend works.

**Comment by kalvdans** [comment]
Storing a list of ISO 639-2 three-letter codes in the backend sounds good, then frontend can deal with language names and localization thereof.

**Comment by lucaslcode** [comment]
Agreed, one other thing though, we also need to save the fluency. Either A1-C2 and Mother Tongue or a list like Can say hello, Beginner, Intermediate, Advanced, Fluent, Mother tongue

**Comment by Almenon** [comment]
Just three letters sounds like it runs the risk of a code corresponding to more than one language but I checked and they're all unique, huh.  

![I guess that works](https://media.giphy.com/media/l41YkFEPPPorUbKsU/giphy.gif)

I suppose we could have a list of dicts like so:

```
user.languages = [{
  language: 'aar'
  fluency: 1
  },
  ... and so on
]
```

A error would be raised if a request was made with more than 547 languages, as that is more than the number of existing languages in the ISO dataset.

@lucaslcode can you describe the specs for what you need from the backend, please? (API endpoint name, request params, response)

**Comment by Almenon** [comment]
Actually maybe we should use [ISO639-3](https://en.wikipedia.org/wiki/ISO_639-3) instead of ISO639-2? Version 2 just has one code for "sign languages", but there are multiple types of sign languages. I've never used ISO639 before though so maybe there is some major advantage to v2 i'm missing. @kalvdans thoughts?

**Comment by kalvdans** [comment]
> Actually maybe we should use [ISO639-3](https://en.wikipedia.org/wiki/ISO_639-3) instead of ISO639-2? Version 2 just has one code for "sign languages", but there are multiple types of sign languages. I've never used ISO639 before though so maybe there is some major advantage to v2 i'm missing. @kalvdans thoughts?

You are right, ISO639-3 is better. It also only allow one mnemonic for each language, for example ISO639-2 can spell German `ger` or `deu`, while ISO639-3 only allow `deu`.

> fluency

For the sake of automatic host-guest matching based on languages, I think we should only put languages that we are comfortable to host/surf with in the list of languages. Further refinements such that fluency could be done in free text in the profile, not reachable of the search filter.

**Comment by lucaslcode** [comment]
I think it's nice to include if it's not too much trouble. Maybe I'm fluent in French and I want to surf with subscribe learning French because I have something to offer.

**Comment by Almenon** [comment]
@lucaslcode following up on this - just checking if you saw my comment asking for the specs. If yes no worries, take your time.

**Comment by lucaslcode** [comment]
@Almenon sorry I did miss it.

How about this, replace the existing `repeated string languages = 17;` in `api.proto` with

```
repeated LanguageAbility languages = 17;

...

message LanguageAbility {
  enum Fluency {
      FLUENCY_UNSPECIFIED= 0;
      FLUENCY_SAY_HELLO = 1;
      FLUENCY_BEGINNER = 2;
      FLUENCY_INTERMEDIATE = 3;
      FLUENCY_ADVANCED = 4;
      FLUENCY_FLUENT = 5;
      FLUENCY_NATIVE = 6;
  }
  string code = 1; //ISO639-3
  Fluency fluency = 2;
}
```

If it's a standard, we can just implement the code->language table on the frontend. No need to make an api call to get the list of languages. However I'm not convinced ISO639-3 is the right choice. [Do we really need all these?](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Languages/List_of_ISO_639-3_language_codes_(2019)) I guess maybe it's fine...

**Comment by Almenon** [comment]
I'd prefer ISO639-3 because it's more inclusive for mute people but it is 100KB larger (113KB vs 16KB). If the size is a concern I suppose we could use ISO639-2.

That format looks good - to confirm, when you call `UpdateProfileReq` you will be passing in that format for the `languages` param, right? That's the only API endpoint that needs updating?

**Comment by lucaslcode** [comment]
We could use ISO639-3 and then just support a subset of the most common ones in the frontend.

> That's the only API endpoint that needs updating?

Yes, `UpdateProfileReq` and `User`

**Comment by aapeliv** [comment]
I feel like embedding the whole ISO639-3 list is a bit overkill. Well, rather, I think it'll make something like an autocomplete box look a bit silly.

I'm thinking maybe we should just find some sensible subset of ISO639-3, and store that somewhere, then if there are languages we missed, I'm sure people will let us know and we can add them as we go. Using the ISO639-3 identifier looks like it would work very well though, I doubt we need to add languages outside it.

We can either store the subset as a JSON file, or create a fairly straightforward API call to retrieve the list (or even autocomplete results).

What do you think?

**Comment by kalvdans** [comment]
> I feel like embedding the whole ISO639-3 list is a bit overkill. Well, rather, I think it'll make something like an autocomplete box look a bit silly.

I'm thinking that a client should not include the whole list even if it was allowed. The primary language could be autofilled from the locale settings in the browser/OS.

**Comment by aapeliv** [comment]
Backend is now ready in #926 for frontend implementation, but we broke the API so the frontend broke too!

**Comment by aapeliv** [comment]
Done
