### ISSUE TITLE
Profile/user page design

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#410]
Users need the following additional simple fields implemented for the beta ui. More complex fields in seperate issues.

- pronouns
- Hometown
- meet up status (like hosting status)
- education

**Markdown fields** - the second level fields are pre-filled as markdown headings, there by default but can be deleted
- About me
  - current mission
  - what I do in my free time
- My travels
  - why I use Couchers,
  - my favourite travel story
- Things I like
  - Art
  - Books
  - Movies
  - Music
- Additional information

**Info for surfers**
- Camping requests ok?
- Pets ok?

**Info for hosts**
- Has pets (Yes/No and additional free text)
- Private/shared space
- I smoke at home (y/n)
- I drink at home (y/n)
- Has housemates (y/n/details if yes)
- Has children (y/n/details if yes)
- parking (y/n/free off-site/free on-site/paid off-site/paid on-site)
- other host info (markdown)
  - pre-filled heading: What I can share with guests

These fields need to be modified:

- hosting status get rid of 'difficult' (maybe it should just be removed from frontend initially?)
- Remove "color" 
- Remove "multiple groups OK?"
- area should be a markdown field with pre-filled headings:
  - Public transport
  - Parking
  - Accessibility

**Comment by aapeliv** [comment]
> * current mission*
> * Why i use couchers
> * What I do in free time
> * Favourite travel story
> * Favourite art, books, movies & music (one field or 4?)*
> * Additional info about me*
> * Favourite quote

Would it be possible to have these in one markdown field? I feel like people would like to customize this as well?

**Comment by lucaslcode** [comment]
It would certainly be easier

**Comment by lucaslcode** [comment]
Updated this issue to reflect slightly more generalized markdown fields with default, pre-filled headers

**Comment by ShmuelTreiger** [comment]
I began a fix in https://github.com/Couchers-org/couchers/tree/backend/feature/profile-fields-api

1) I couldn't figure out how to do the pre-filled headings in markdown

2) I couldn't find where the models are tested, so I didn't add any tests

3) Haven't migrated

Other than that, I've done the basic changes

**Comment by lucaslcode** [comment]
Great! Tests are in `https://github.com/Couchers-org/couchers/blob/develop/app/backend/src/tests/test_api.py` though there are probably some other broken ones too. Open a pull request for review and comments.

**Comment by ShmuelTreiger** [comment]
So a couple questions/issues I'm having:
1) I don't understand how "pb" works/what it is? I believe it's auto generated. Is that what happens when I migrate? I've only ever migrated a DB once before and it was years ago. Do I need to actively edit it, or will it edit itself?
2) To be able to use markdown in database fields, it looks like I need to add a new package to python. There are a few options, and I have no way to assess which might be best. Am I correct in my understanding? And if so, how should I proceed?

**Comment by lucaslcode** [comment]
1. Everything in pb is auto-generated. It's created from the *.proto files and turns those definitions into python and js code which we then use. Ie. it turns the protobuf "messages" into classes and the RPC calls into functions (which you then implement in the servicer).

If you change any *. proto file, you will have to regenerate the pb files, there are instructions in `app/readme.md`

Migration is different, that is about migrating the postgres database, like changing the columns in a table etc. Someone else will have to fill you in on that :p

2. You don't need to handle markdown in the backend, it's all done on the frontend. Backend just stores the source text like "# Heading\n\n\*Hello!\*"

**Comment by ShmuelTreiger** [comment]
Ready for an initial review, but definitely not ready to merge. Should I mark it [MRG}?

Some issues:

1) Needs to be migrated when everything's good and ready

2) I'm referencing things in the protobuf that don't exist. Unclear to me how I'm supposed to get them there.

3) For "test_update_profile", is there some reason why all fields aren't being tested after being updated?

4) I'm a little confused about "test_hosting_preferences". Seems to me we should generate a user, check the default values, add values, check again, and then remove them and check once more. Instead we have two users--not sure what second one is for--and we only change some values before re-checking all of them?

**Comment by lucaslcode** [comment]
Backend complete. This is ready for implementing the hifi. Related to #615
