### ISSUE TITLE
Show both login and password at login form

### ISSUE THREAD

**Issue by okainov** [Couchers-org/couchers#4106]
It's very-very annoying when I cannot use my auto-fill in browser because "password" field appears only after one click to "Continue". Thus it causes few extra clicks every time.

![image](https://user-images.githubusercontent.com/918446/190371069-070d5c28-590c-44d4-82fc-8a0b94345ffd.png)

Please show both textboxes at the same time. If there is any kind of SSO support, then better *hide* password textbox when one enters SSO-related email.

In combination with non-working "Remember me" (#210) it creates a lot of inconvenience

**Comment by bakeiro** [comment]
interesting... in my browser it autocompletes automatically the password box, (like with outlook web, does the same aswell) which browser are you using? also, phone or desktop? :)

**Comment by okainov** [comment]
@bakeiro Desktop Chrome. It auto-completes after the second click to "Continue", but that's the extra click which is absolutely inconvenient. I really expect the form to work in the following way:
1. Open the page
2. Click on "email textbox"
3. Click on the login from the suggested auto-completion list
4. Click "Login"
5. Enjoy the website for logged in users

Now I need to click "Continue" before step 4, which is extra click.

**Comment by aapeliv** [comment]
The reason why it has a two step process is that we used to not have passwords. There are still some users who haven't set a password, and there is different behavior for them.

We're phasing that out however, and probably we could soon switch to something else, like having those users who've yet to set a password just have to reset it using a reset password page or similar.

https://github.com/Couchers-org/couchers/blob/c6469b681aca7c355533fab9586a0b659783568e/app/backend/src/couchers/servicers/auth.py#L348

**Comment by jesseallhands** [comment]
Notes from duplicate #4116 :

> On top of this, there are a number of landing page improvements that should be addressed:
> 
>     The design for the guest landing page (aka sign up) vs. member landing page (aka log in) is different.
> 
>     Guest landing page says: The new alternative to couchsurfing. Member landing page says: Join and help us grow the new alternative to couchsurfing. The text should be the exact same (i.e. wording and position).
> 
>     The onboarding frame should remain the same size and structure between steps. (This will be mitigated anyways if email and password are integrated into one frame).
> 
>     Remove or change the red Report a bug button. Alternatively, it can be designed as a link in RED.
> 
>     It should not be a primary button. The only primary button should be the one inside the onboarding frame.
> 
>     Remove the sign-up button. For new users, the signup form is already accessible right away. This can create some confusion.

**Comment by aapeliv** [comment]
This is now done as of a long time ago.
