### ISSUE TITLE
Enable "Remember me" by default

### ISSUE THREAD

**Issue by okainov** [Couchers-org/couchers#4108]
I think it would be beneficial for all users to have "remember me" checkbox set to "Enabled" all the time, this should be the most used functionality.

Currently it requires extra click during every login which is inconvenient

**Comment by darrenvong** [comment]
Hmm not sure about this, as people on shared computers could be caught by this and not realised. @ItsiW what do you think?

This can probably be done together with Couchers-org/couchers#4107 if desired, given both are likely a small tweak to the existing frontend code.
