### ISSUE TITLE
Advanced photo uploads

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#412]
~For the beta,~ photos should be able to be uploaded for the following:

- Profile pic
- Me
- My home/couch
- Hosting/surfing photos
- Travel photos

Or alternatively, just my home/couch and custom albums. Photos should be able to be ordered, deleted, and have captions (associated text).

**Comment by aapeliv** [comment]
I think a profile avatar is a special case. But I think everything else should be doable as a general Album > Photos structure. We can for now limit the album type to an enum and make sure each user has at most one album of each type. But is there really any special treatment for the other photos except avatar/profile pic?

**Comment by lucaslcode** [comment]
Only my home/couch appears by itself on the "my home" tab, while all the others are just in a "photos" tab

**Comment by aapeliv** [comment]
* Communities
* Groups
* Events
* Places
* Guides
* Photos within pages
