### ISSUE TITLE
Hamburger menu on mobile is barely visible when using dark mode

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#4162]
A user reported that the hamburger menu on mobile is not visible when using the browser (brave) in dark mode. See below:

![image](https://user-images.githubusercontent.com/79384268/138785712-69883835-9e00-469e-b95c-8960ac07abb4.png)

**Comment by darrenvong** [comment]
Hmm I'm not really sure this is really a bug, as tech savvy users can technically change the stylesheet being used and it'd be impossible for us to control that and try to cater for everyone who does this. But it'd certainly be nice for this to work as dark mode seems like a common use case (or at least until we consider implementing our own dark mode).

**Comment by jesseallhands** [comment]
not a bug, extension issue
