### ISSUE TITLE
Swipe gallery component

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#419]
Component to display pictures on mobile, with optional captions

**Comment by navandstokes** [comment]
Should we use [this package](https://www.npmjs.com/package/react-material-ui-carousel)? What are the considerations before deciding to add a UI package?

**Comment by lucaslcode** [comment]
Considerations:

- Does it have the features we want
- Popularity (stars are a good indicator)
- How active is development
- Do they merge PRs from other people
- How many open issues are there (and how serious are they, how quickly are issues closed) (noting that popular packages get more issues)
- How much will it [add to the package size](https://bundlephobia.com/)  (not a massive deal as long as it's not crazy)

**Comment by lucaslcode** [comment]
react-material-ui-carousel doesn't appear to be swipeable, I think that's important for the mobile design

**Comment by lucaslcode** [comment]
What about [swiper.js](https://swiperjs.com/react/)? It's [a bit hefty](https://bundlephobia.com/result?p=swiper@6.4.1) though.

**Comment by lucaslcode** [comment]
On second thought, maybe we should just [start with a super simple one](https://mediatemple.net/blog/design-creative/carousels-dont-have-to-be-complicated/). It's only a couple of lines of css.

**Comment by navandstokes** [comment]
Interesting. I think that particular solution is [no longer supported](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-points-x). It seems like scroll snap in general is [available](https://caniuse.com/css-snappoints). Will play around with this. I don't know if IE11 is of concern though?

Otherwise, how about [react-multi-carousel](https://www.npmjs.com/package/react-multi-carousel)?

**Comment by lucaslcode** [comment]
If rolling our own is *very* easy, it's probably a better idea, if not, that does seem like a good library!

**Comment by lucaslcode** [comment]
And let's only worry about modern browsers until there's demand for supporting older ones.

**Comment by lucaslcode** [comment]
This is closed in #658 with `HorizontalScroller`. It works for mobile only. For now it is basic with no caption support or lightbox, etc.
