### ISSUE TITLE
User page references/reference list

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#420]
From beta ui, with tabs to sort from hosts/guests/etc

**Comment by darrenvong** [comment]
Looks like they are still moving stuff around the desktop version... but maybe I can make a start on this for the mobile version at least.

**Comment by lucaslcode** [comment]
@andreaowu was going to do user pages once desktop design is ready but there's some things to do here with writing the references so might be good to get done now

**Comment by darrenvong** [comment]
Yeah looks like the references APIs are all ready? Although from the last meeting note you still got a star on it, so maybe something is still missing?

**Comment by lucaslcode** [comment]
Being able to leave hosting/surfing references needs backend work but doing the rest doesn't seem like it would be wasted time

**Comment by lucaslcode** [comment]
Closed in #713
