### ISSUE TITLE
"Read more" text placement issue on landing page (unrelated to cookies banner issue)

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#4261]
The "Read more" text on the bottom of landing page is only partially visible on most mobile browsers (after closing cookies banner, which also covers the text, see #4128).  The text is cut off by the bottom of the browser window:

![Screenshot_20240428_232246_Firefox](https://github.com/Couchers-org/couchers/assets/79384268/c07e12fd-965b-4803-8e65-8dd04fa70548)

This is a confirmed issue on firefox, chrome, and safari - both on android and iphone. 

The text should be moved up and the font size should be increased to make it more prominent.

**Comment by marco-digennaro** [comment]
i'm working on this (can't see assign to me button ^_^)
