### ISSUE TITLE
Internal server error after strong  verification

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#4314]
Bug happened as follows:
1. Completed strong verification here: https://console.couchers.org/strong-verification (clicked button, completed verification in app).
2. Visited https://console.couchers.org/strong-verification again
3. Clicked on button "start strong verification"
4. Internal server error returned:
![image](https://github.com/Couchers-org/couchers/assets/79384268/39879120-265e-4fec-972a-cce52c62b63b)

**Comment by aapeliv** [comment]
Fixed now.
