### ISSUE TITLE
Page to list users with a given badge

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#4318]
This would be cute!

**Comment by schradert** [comment]
Lots of relevant code in #4246 and #4247

**Comment by schradert** [comment]
~@bakeiro Maybe there is something wrong with the way I'm using `react-query` but the `useBadges` hook seems to not run in the `BadgesPage` component when I first load the page `/badges`. In ReactQueryDevTools, I can run Refetch on the `"badges"` query, which does return the correct data. Why do you think it isn't running on page load? You should be able to reproduce this by:~

```bash
cd app
docker run --pull always --rm -w /app -v $(pwd):/app registry.gitlab.com/couchers/grpc ./generate_protos.sh
docker-compose up --build &
cd web
yarn start:localdev
```

~(FYI I made a separate script to actually use the docker database, which isn't used by `yarn start`)~

EDIT: Sorry I'm an idiot. I'm not sure why is it was able to work before, but I just had to check whether the value existed yet by changing `Object.values(badges)` to `badges && Object.values(badges)` ... Not sure why this escaped me earlier.

**Comment by nabramow** [comment]
@schradert Are you still working on this, or is it okay if someone else picks it up?

(I am going through the board to make sure things are active)

**Comment by nabramow** [comment]
Closing as #4389 is the source of truth for this feature.
