### ISSUE TITLE
zooming / panning the map should filter members accordingly (update bbox as visible section of the map changes)

### ISSUE THREAD

**Issue by ari-s** [Couchers-org/couchers#4328]
Reproduction:
1. Search for a place, like "Berlin"
2. change the visible part of the map, by zooming into the area around Alexanderplatz
3. The list of members doesn't change - it would be great if it would show exactly the members that are visible on the currently visible part of the map <- this is the part that would be great if it was improved

thanks for couchers.org!

**Comment by bakeiro** [comment]
done in my PR, (a bit in a different way)
