### ISSUE TITLE
Strong Verification

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#4349]
* ~I think it does not currently handle expiring passports, or there is some other issue with doubles for users.~
* ~Needs update for getting initiation state, not just "waiting for user"~
* ~FAQ~
* ~Privacy policy~
* Frontend part: #4413 
* Technical blog post: #4354 
* Instructional video
* Onboarding email

**Comment by nabramow** [comment]
@aapeliv what's up with this one? Does it go back to ideas?

**Comment by Krishnag09** [comment]
@nabramow - we and @bakeiro have separate tickets for this that are done.

**Comment by nabramow** [comment]
Closing as this is now happening in #4413 and #4354
