### ISSUE TITLE
Encourage Complete Profiles - Profile requirements to use certain features

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#4387]
To combat spam and encourage behavior that supports the core values of the platform, certain features should only be accessible to users with a "complete" profile. Users should be encouraged to complete their profile, instructed how to do it, and - if their profile is incomplete - warned when they try to use features that require a complete profile.

- [x] update definition of "complete profile" FROM "has picture" + "about me > 20 characters" TO "has picture" + "about me >150 characters"
- [x] Add reminder to dashboard and all other affected pages (messaging, search, communities, and events) that links to their profile page. Actual minimum character count should not be mentioned.
  - Too short AND missing photo: `Almost there! Before you can [send a request/send a message/create an event], you must write more about yourself in your profile and upload a profile photo. This helps build a trusted community and reduce spam. For more information click [here](link to help page). Thank you for your help!`
  - Too short: `Almost there! Before you can [send a request/send a message/create an event], you must write more about yourself in your profile. This helps build a trusted community and reduce spam. For more information click [here](link to help page). Thank you for your help!`
  - Missing photo: `Almost there! Before you can [send a request/send a message/create an event], you must upload a profile photo. This helps build a trusted community and reduce spam. For more information click [here](link to help page). Thank you for your help!`
- [x] Create help page which explains the following:
  - How it works and why its required
  - What to do if you're afraid of uploading a picture of yourself
  - How to write a good profile / what to write in your profile
- [x] require "complete" profile to use certain features, including:
  - creating requests (eg. clicking "request" button should display modal with warning about why they can't send a request)
  - creating messages (group or 1-on-1) via messages page or profile page
  - creating events
- [x] UI/UX tests with design team prior to going live

**Comment by aapeliv** [comment]
@Krishnag09 working on backend
@aapeliv working on frontend
@jesseallhands working on help page, hopefully :pray:

**Comment by jesseallhands** [comment]
@aapeliv can we also prevent people adding friends until their profile is complete? Support has received complaints of people with empty profiles sending friend requests.

**Comment by nabramow** [comment]
@aapeliv @jesseallhands @Krishnag09 what's up with this one? Should it still be in the "In Progress" column?

**Comment by aapeliv** [comment]
I believe this is done now!

@jesseallhands could you double check nothing's left?
