### ISSUE TITLE
Authentication logic is broken

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#439]
You can get stuck "phantom logged in" if the backend invalidates your session but the frontend doesn't. The frontend won't update the state to unauthenticated if it gets back an unauthenticated response from the server.

One way to reproduce:
1) Navigate to https://app.couchers.org and log in
2) Navigate to https://develop--frontend.preview.coucher.org and log in
3) Log out of https://app.couchers.org (this will remove the cookies)
4) Now https://develop--frontend.preview.coucher.org is phantom logged in

Possibly easier:
1) Go to https://develop--frontend.preview.coucher.org and log in
2) Remove cookies for domain api.couchers.org
3) You're now phantom logged in

**Comment by aapeliv** [comment]
You can get out of it by deleting local storage on the site the frontend is running on. (Delete local storage and then leave the site so it doesn't re-store the state).

**Comment by lucaslcode** [comment]
Related to #345

**Comment by lucaslcode** [comment]
Does both being jailed and not logged in return "unauthenticated" error? And these are the only situations?

**Comment by aapeliv** [comment]
Yes

>
