### ISSUE TITLE
Help page: how to/guide/tips on responding to a request

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#4393]
Part of #4392 

Things like
* You don't need to feel pressure to accept
* Examples of good, succinct rejections
* etc

@jesseallhands assigning you for now but maybe I/someone else can help

**Comment by jesseallhands** [comment]
Helper text:

> [Things to consider](https://help.couchers.org/hc/couchersorg-help-center/articles/1715125658-what-are-some-things-i-should-think-about-before-responding-to-a-request) before responding.

Put the helper text here above the accept or decline buttons with some kind of dividing line above the text (to separate it from the messages):

![image](https://github.com/user-attachments/assets/e3fd47d3-92d7-4095-a475-62ad94994b77)

**Comment by aapeliv** [comment]
The page itself is done.
