### ISSUE TITLE
require users with bogus ages to update their age

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#4429]
There have been numerous occasions of users with an age (eg. >100!) clearly much higher than their actual age. Age is an important factor for social interactions and it erodes trust of users when someone is using a fake age. 

Users with an age currently >90 should be prompted to update their age with their real age upon next login. We can use the jail to do this. It is theoretically possible for us to have some users with a real age over 90, so we will give them the option to contact support to update their age.

For new users, we should:
1. mention the importance of age in social contexts, which is why real birthday is required per the ToS, but also mention that birthday is not shown on the website.
2. Display age after birthday is entered and have user confirm it is accurate and real with checkmark.
3. Set an age limit of 18 to 90 (currently just 18 or older), where if the age is over 90 the account is flagged for moderator review (ages under 18 are not allowed at all per ToS).

**Comment by aapeliv** [comment]
I don't personally think this is so important, we write in the ToS:

> You may hide or obfuscate information on your public profile for your own privacy or security, but you may not do so in a way that would reasonably deceive other users.

I don't think someone with age 122 will deceive anyone, they are obfuscating their age and do not want to reveal it. I think it gives users who may potentially interact with them information.

I think a bigger problem is people truely misleading about their age, eg saying they are 27 when they are 37. But that we can't really catch, and the solution to the things are the verification pieces we are building.

Also this is a fair bit of work on the dev side.

**Comment by jesseallhands** [comment]
We can now do this via a moderator message, so this ticket is now moot.
