### ISSUE TITLE
Event community invite button

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#4449]
Button to invite a community to an event. This will allow event creators to create an event without navigating to the relevant community first. It will make sure that people in the community are notified.

**Comment by aapeliv** [comment]
* Should be visible to those that have "can edit" true:

https://github.com/Couchers-org/couchers/blob/87ba55e3ff199c495475db7e976ee5f2237fc24f/app/proto/events.proto#L159

API browser:

https://next-console.couchershq.org/api/org.couchers.api.events.Events#org.couchers.api.events.Events.RequestCommunityInvite

This is the API call to call:

https://github.com/Couchers-org/couchers/blob/87ba55e3ff199c495475db7e976ee5f2237fc24f/app/proto/events.proto#L35-L37

And body:

https://github.com/Couchers-org/couchers/blob/87ba55e3ff199c495475db7e976ee5f2237fc24f/app/proto/events.proto#L226-L228

**Comment by jesseallhands** [comment]
Wording of the button should be `Invite community` which opens a modal that says: `After moderator approval, this will send an invitation to everyone in the XXXX community. Are you sure you want to proceed?` [Yes] [Cancel]

**Comment by aapeliv** [comment]
We don’t have this info in the API call. We should for now instead link to a help page that explains what it does.Best,Aapelihttps://www.aapelivuorinen.comOn Jul 2, 2024, at 17:07, Jesse Allhands ***@***.***> wrote:﻿
Wording of the button should be Invite community which opens a modal that says: After moderator approval, this will send an invitation to everyone in the XXXX community. Are you sure you want to proceed? [Yes] [Cancel]

**Comment by jesseallhands** [comment]
I just realized this issue probably touches on two things:

1. The need to be able to assign an event to a community (so if someone creates an event from the general event page it isn't a global event unless they want it to be)
2. The need to be able to submit a request to send an invite to the community. 

My comment above (quoted below) is related to # 2

> Wording of the button should be Invite community which opens a modal that says: After moderator approval, this will send an invitation to everyone in the XXXX community. Are you sure you want to proceed? [Yes] [Cancel]
