### ISSUE TITLE
Filtering of events

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#4467]
There's been a request to add filtering functionality on the events page. Requested location filter or sort by distance.

**Comment by aapeliv** [comment]
I am making this "important" because I think it's been specifically requested by the Manchester community and it'd be great if we could act on their feedback!

**Comment by Krishnag09** [comment]
ok, i will take this up this week.

**Comment by spreeni** [comment]
Closing as this was implemented with [ !4590](https://github.com/Couchers-org/couchers/pull/4590)
