### ISSUE TITLE
API functions to be made

### ISSUE THREAD

**Issue by amdwit** [Couchers-org/couchers#455]
Ideas for rpc and implementations like : 
https://github.com/Couchers-org/couchers/pull/435#issuecomment-747107994
can be post here.

**Comment by lucaslcode** [comment]
Do you mean for communities?

Nodes, clusters, pages, events:
- Adding, editing, deleting each type (not sure how admin roles/permissions are supposed to work)
- VIewing details for a specific one

Clusters, pages, event:
- List all for a node (each type probably separate)
- List based on distance from user/point
- Search

**Comment by amdwit** [comment]
Yes, I am now talking about communities, but if you need api changes elsewhere, mention that too. I think it is best if the API is created based on wireframes and on advise of the frontend team as I find it hard to guess what an api entry should look like.

**Comment by lucaslcode** [comment]
There are a number of API implementation issues under the backend+feature tags

**Comment by amdwit** [comment]
I will take a look there. If some outstanding api work is blocking front end work please let me know.

**Comment by lucaslcode** [comment]
Closing in favour of other issues. Outsanding features can be checked with the "features" tag (optionally combined with "backend" or "frontend")
