### ISSUE TITLE
Map styling

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#466]
What kind of map style do we want? Vue currently uses the `light-v10` style, and React uses a `streets-v11` style.

React:

<img width="640" alt="Screen Shot 2020-12-23 at 3 26 42 pm" src="https://user-images.githubusercontent.com/2975660/103000278-68de9b80-4533-11eb-82a0-81c7d56a31b3.png">

Vue:

<img width="806" alt="Screen Shot 2020-12-23 at 3 26 54 pm" src="https://user-images.githubusercontent.com/2975660/103000285-6b40f580-4533-11eb-84da-f9011ba3187d.png">

I think the light one is better as a background when overlaying information on it.

These can also be designed/tweaked in mapbox studio if we want some custom styling. (Though this requires staying with mapbox tiles, which we will not stay locked into, so don't want to spend too much time on these).

**Comment by Almenon** [comment]
+1 for the light grey one, the blue stands out better in comparison

**Comment by lucaslcode** [comment]
Any other "Default styles" we can use without spending too much effort? I like the gray one at that zoom level, but I found it difficult to see streets and city layouts when zoomed in.

**Comment by lucaslcode** [comment]
Or we could make the circles "couchers orange" ;)

**Comment by lucaslcode** [comment]
![image](https://user-images.githubusercontent.com/32044095/103047649-17123180-4584-11eb-9677-1dad3a54a8c0.png)
![image](https://user-images.githubusercontent.com/32044095/103047669-23968a00-4584-11eb-9fb0-386e88404656.png)

**Comment by lucaslcode** [comment]
On second thoughts, maybe for our purposes the clarity of streets is not that important.

**Comment by aapeliv** [comment]
There's 5 main styles that they've done (again, everything's customizable in their editor), you can see them under the "Choose a map" heading here: https://www.mapbox.com/maps/

**Comment by aapeliv** [comment]
But these are the main two choices, I think. Other ones don't suit that well

**Comment by aapeliv** [comment]
We can create our own style: either with Mapbox's editor or with maputnik. However, if we do make our own style, we should do it with maputnik I believe as that stack is fully open source; mapbox won't let you use a style for their layers with your own layer. If we grow large enough, we will want to run our own tile servers, but for now mapbox or any other base tile provider will suffice. I would personally prefer for us to stay within the 100% open source ecosystem, using OpenMapTiles, e.g. through Stadia. (For now, if we go with something low effort, it doesn't matter though.)
