### ISSUE TITLE
Geo considerations

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#470]
The point of this issue is to collect some thoughts I have about geo stuff. It's mostly for me to keep track of what I've looked at and collect research. Feel free to comment and discuss.

By "geo" I mean stuff relating to real-world geography here, countries, areas, cities, etc. The main problem is that OSM data is very heavy and it's also not super well standardised and well curated. It's for instance hard to refer to a single object in their database because the object's ID is not guaranteed to be permanent, and things might change. We also can't directly rely on their APIs as they have limits and we'd like our platform to be spiffy with e.g. typeahead suggestions as people type.

# Countries

We need 4 kinds of country info on people's profiles: countries they've lived in (self reported), countries they've visited (self , reported), and countries they've visited through couchers (verified visited?), countries they've hosted people from.

We need some way of having user location history. So if someone moves e.g. to another country/community, then all those who surfed with them don't turn up as having been in a completely different place. For now we haven't done history of objects except for stuff that explicitly is versioned (e.g. page versions). The discussion on that is still open, but maybe we should just copy the relevant information from the user's profile, since it (information about where someone surfed) should never be updated, and it might be useful to have that for security/privacy reasons, etc.

Countries change, but they change rarely, and if someone visits a country now and that country stops existing, we should presumably not have the database shit itself. However, we should be aware of that.

There are 2 well-standardised, good ways of identifying countries (and a lot of other ones). There's the ISO 3166 alpha-2 and alpha-3 codes (it tells the number of characters in the identifier). E.g. Finland is `FI` and `FIN`, respectively. Both seem to be OK, but alpha-2 seems more common, and OSM seems to support this better.

**Comment by aapeliv** [comment]
# Getting country data out of OSM

It's a bit tricky. The data is not perfect, and we're not going to start taking sides on what's an official country and what's not. Here's a log of what I've been doing:

* Get all relations with ISO 3166-1 codes. This is problematic though, it returns these non-official areas: CP, XK, TA, AC, IC, DG.

```ql
rel[type=boundary]["ISO3166-1:alpha2"]; out count;
```

* Get all country boundaries?

```ql
rel[boundary=administrative][admin_level=2]
```

* The solution might be to get relations based on a list of country codes that have `admin_level=2` or `admin_level=3`, then label points with the smallest region containing that point.

**Comment by lucaslcode** [comment]
There may come a time when we DO have to take a side. I think OSM's "on the ground" policy is reasonable and very applicable to hospex.
