### ISSUE TITLE
Create new events page - Part I

### ISSUE THREAD

**Issue by nabramow** [Couchers-org/couchers#4784]
Use design mockup from #3989.

This is the first iteration of the new events page. It should replace the existing events page in the top main navigation bar.

This first iteration should include your events, create an event, filter canceled, etc. The discover section will be part II.

Create a feature branch for events and make smaller PRs off of it.

**Comment by bakeiro** [comment]
suggestion:
one iteration could be implementing this mockup without the pills (image attached)
[you can do it in any other way, this is just a suggestion]

![events_page_phase_1](https://github.com/user-attachments/assets/2f617319-c38b-4b35-9513-31b7b6396700)

**Comment by bakeiro** [comment]
also, behavior detail, add a "see all" button at the botton of  "Your events" list when this is list is longer than 10 events (to show the user that the list is longer)  
![309244499-8af9497c-c6d1-4efc-bcda-7844b02da031](https://github.com/user-attachments/assets/4542a773-79f7-46f2-8d65-8e226b89499e)

**Comment by bakeiro** [comment]
also, this is a mockup to show the page and the idea, don't copy the look & feel, we should use our components and our UI style (just in case U know)

**Comment by bakeiro** [comment]
how every event should look like

![events_page_phase_1 - copia - copia](https://github.com/user-attachments/assets/a6cc9220-b645-4630-8b96-aead9d4a78e5)

notes:
- this mockup it's only to show the logic, ignore the UI difference with our page, should be implemented using our components/UI style
- event date can be an interval
- title can be long & contain emojis

**Comment by bakeiro** [comment]
note about event image:
- when there is no event image we use this (image attached) we can keep doing this

![image](https://github.com/user-attachments/assets/3e967fc5-d41a-4a9f-a498-b2e6767c0ae5)

**Comment by bakeiro** [comment]
for the events in Discovery we can keep using the old component :)

![image](https://github.com/user-attachments/assets/cc0cb950-1b57-46a4-b8e0-c0f98e23e491)
