### ISSUE TITLE
Signup has unmounted state update warning

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#480]
When entering your email succesfully. Probably needs `useSafeState` and/or no conditional rendering.

**Comment by darrenvong** [comment]
Looks like the log in form still has the issue too. And I think I've finally find something that seems plausible and might explain why: https://stackoverflow.com/questions/62924933/how-to-handle-react-history-push-causing-undesired-component-remounts

Although `history` is meant to come from react-router which is mounted up way higher up the tree, so still 100% convinced the linked Stackoverflow fully matches what we're facing. Apart from re-writing it to not use the weird route switching, not sure what a good solution to this is tbh...

**Comment by lucaslcode** [comment]
I don't get this anymore. Not sure what changed 😕
