### ISSUE TITLE
Invalid tokens should not give UNAUTHENTICATED error

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#481]
Should be reserved for not logged-in users trying to do something that requires login. Perhaps NOT_FOUND is more appropriate.

**Comment by kalvdans** [comment]
I think the error message is deliberately the same for invalid user and invalid password, just to prevent attacks from getting more information. @aapeliv ?

But I think the gain by having a better error message for regular users overwins the 1 bit information gained by crackers. So I'm for this change.
