### ISSUE TITLE
Map style updates

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#4833]
* Vegetation color clashes with teal clusters

Aapeli will help Jesse set up maputnik, etc

**Comment by nabramow** [comment]
@aapeliv was this one completed by 34834? If so can we close this one?

**Comment by aapeliv** [comment]
It wasn't, but I'm not sure if this is a priority. Closing and @jesseallhands can reopen if he thinks it's important. Jesse I can show you how to edit the map layer!
