### ISSUE TITLE
Pin coloring based on completed profile

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#4846]
We discsussed coloring of the map pins based on things. The general consensus was:

* we will start with 2 colors, based on completed profile (teal) or not (gray);
* in the future: consider 3 colors: incomplete (gray), complete + inactive (light teal), complete + active (teal);
* we want to be careful about how activeness/completeness is defined: users who haven't logged in for 4 months can be great potential hosts;
* seems that making the map very busy is quite a big topic, we want it not to be too crazy.

**Comment by bakeiro** [comment]
we already have a color code based on what the user searchs on map... maybe this might be overloading for the map??

![image](https://github.com/user-attachments/assets/37fb43c7-e58f-496a-b294-0533709ea8ef)
