### ISSUE TITLE
Refactor service calls to use react-query

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#489]
Where appropriate

**Comment by darrenvong** [comment]
I was gonna say we've probably completed this... but maybe not after I skimmed over the communities code we just merged in 😂

**Comment by lucaslcode** [comment]
There are still a few stragglers around in older components too, but it's not urgent

**Comment by lucaslcode** [comment]
I'm just gonna close this, I think only the auth stuff is left and it's not a huge deal
