### ISSUE TITLE
[events] small CSS issue in events list page

### ISSUE THREAD

**Issue by bakeiro** [Couchers-org/couchers#4979]
![image](https://github.com/user-attachments/assets/d02f957a-8082-4797-92f7-7ddc18cda0bf)

**Comment by bakeiro** [comment]
[Just a suggestion, not part of the ticket] In case you feel it's worth doing :)

I was doing some tests and I created this [ignore the UI differences]
![image](https://github.com/user-attachments/assets/da32a8d5-0ec6-43c6-9f62-68450f6da12a)
![image](https://github.com/user-attachments/assets/26ea0a6e-5e1d-4f76-882c-774b6e655802)


when the autocomplete is like a pill feels more consistent, this is how looks now on the page
![image](https://github.com/user-attachments/assets/fe456e37-1ebd-4d19-8daf-f0db029e7801)
![image](https://github.com/user-attachments/assets/8d3ac731-39ff-4896-96bc-557be67dc8aa)

**Comment by nabramow** [comment]
Done in #4912 

Anything with `LocationAutocomplete` should be a separate ticket I think, since that component is used many other places.
