### ISSUE TITLE
Messaging on mobile is buggy

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#4995]
**Problem**
Currently if I send a message on mobile, the message thread does not always advance to display the message I just sent. See below:

![Screenshot_20241016_000443_Firefox](https://github.com/user-attachments/assets/0ec955bc-b08a-4155-95cf-c9a65e204dea)

**Desired behavior:**

The message thread should automatically advance to display the message I just sent. I shouldn't need to scroll to see the message I just sent.

**Comment by jesseallhands** [comment]
@nabramow fyi, this is still an issue. Was able to replicate on prod just now on a request from Aapeli

**Comment by aapeliv** [comment]
The PR wasn’t merged and deployed yet, right?

**Comment by nabramow** [comment]
No, I’m still waiting for review approval.On Nov 1, 2024, at 6:31 AM, Aapeli ***@***.***> wrote:﻿
The PR wasn’t merged and deployed yet, right?

**Comment by nabramow** [comment]
> The PR wasn’t merged and deployed yet, right?

@jesseallhands @aapeliv No the PR is still open, I’m still waiting for someone to do final review and approve as there’s been a lot of back-and-forth.
