### ISSUE TITLE
Bug: UI typo - Email us to add a "language" should perhaps be "entry" since these are regions.

### ISSUE THREAD

**Issue by mudnug** [Couchers-org/couchers#4998]
![image](https://github.com/user-attachments/assets/0558b972-69de-44b5-a002-9b2abb038555)
Email us to add a "language" should perhaps be "entry" since these are locations.

Would you like me to submit a PR?

**Comment by aapeliv** [comment]
Ah yes, good catch! If you could make a PR, that would be awesome.

**Comment by mudnug** [comment]
@aapeliv Could you review the PR or do I need to request review from couchers-org/web?

**Comment by mudnug** [comment]
Code has been reviewed and is pending a merge by someone with authority
