### ISSUE TITLE
Create a UI/UX designer volunteer recruiting page

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#5025]
On https://couchers.org/volunteer

**Comment by jesseallhands** [comment]
This is currently blocked until we resolve the figma account issue.

**Comment by jesseallhands** [comment]
No longer blocked:
The plan is to create this page (similar format as pages like [this](https://couchers.org/volunteer/technical-support-analyst)) and begin recruiting, then figure out how many figma seats we need.
