### ISSUE TITLE
Spinner placement

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#5026]
Lots of spinners in the top left corner instead of centered

**Comment by jesseallhands** [comment]
In particular on the map search page, the placement of the spinner on top of the button at the top of the map is a problem. The spinner should be in the center of the visible map area.

**Comment by nabramow** [comment]
Hey @maxjeon97 just checking in, are you still working on this? If so let us know if you need anything! If not let us know so we can open it to someone else.

**Comment by maxjeon97** [comment]
Hi, I'm so sorry I should've taken myself off of it earlier; please feel
free to assign it to someone else
