### ISSUE TITLE
Mobile: Messages need more space

### ISSUE THREAD

**Issue by spreeni** [Couchers-org/couchers#5028]
While using Couchers in my mobile Browser i realized it's almost impossible to read messages as there is lots of space occupied by other elements and very little space left for the chat view itself. This is on an Samsung S9, so not the largest phone.

I think we could leave out some elements or make them more compact to make the site more mobile-friendly.

![Screenshot_20241023-123957_Firefox.jpg](https://github.com/user-attachments/assets/77d3216a-f2ed-43a8-94e6-10cc2746e30b)

**Comment by bakeiro** [comment]
Quick improvement ideas

![111](https://github.com/user-attachments/assets/f69b5c61-c8b8-45e3-9b92-150603339988)
![2222](https://github.com/user-attachments/assets/c1bb221d-e02d-49ab-95c2-0f951d3e172b)

**Comment by bakeiro** [comment]
About date format:
`eee, dd mmm - eee, dd mmm yyyy`
example: `mon, 16 ago - thu 19 ago 2024`

About location format:
If its to long the trim it?, like `Madrid, Madrid, Spa...`

**Comment by spreeni** [comment]
I think a quick improvement would be as well to make the cancel button part of the scrollable chat view. Currently, it always takes space up. Alternatively, it could be moved somewhere else.

![Screenshot_20241023-130440_Chrome.jpg](https://github.com/user-attachments/assets/a2775253-284b-469d-9f72-0fa0a71a66a5)

**Comment by spreeni** [comment]
And i think while the above changes might make sense as well, it comes down to the chat view being a very small fixed size (on these screens). If this size would be increased, everything else could be scrolled away and would be manageable

**Comment by jesseallhands** [comment]
This is somewhat related to #4995
