### ISSUE TITLE
ios notifications

### ISSUE THREAD

**Issue by bakeiro** [Couchers-org/couchers#5032]
Seems that enabling push notifications on ios doesn't work as expected

ToDo:
- We need to test this
- Spot bugs
- Know how to reproduce them
- Write tickets & fix them afterwards

**Comment by aapeliv** [comment]
What’s needed is a manifest.json that allows pinning the app to the Home Screen. After that it’s possible to enable push notifications via the Home Screen link!

**Comment by bakeiro** [comment]
done
