### ISSUE TITLE
Add character count to user edit profile text input - solve user not knowing why profile incomplete warning

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#5050]
We now have a requirement of minimum 150 characters in "About Me" + a profile picture in order to do certain things. (See: https://help.couchers.org/hc/couchersorg-help-center/articles/1725919152-why-do-i-need-to-complete-my-profile-to-use-some-features)

However, we are receiving a bunch of bug reports of people not knowing what to fill in in their profile.

**We should add some kind of error message with a counter: "You need to write 136 more characters about yourself to be able to send requests, messages, or create events." (136 should of course change and count to 0, then this message should disappear.)**

**Comment by bakeiro** [comment]
yes, this actually have happened to me 😅

**Comment by bakeiro** [comment]
I was one of those users xd
