### ISSUE TITLE
[messges] expired request improvements

### ISSUE THREAD

**Issue by bakeiro** [Couchers-org/couchers#5127]
Context:
I receive a request, I open the chat, I see it's expired and see a few flaws

ToDo:
- If it's expired, don't show [accept] [decline] buttons ;)
- Change text to: `This request expired. To continue chatting, send the other person a normal message.
- Fix the `undefined` string...

![384617809-0170d3bd-2a71-43bc-a321-bda16571eff4](https://github.com/user-attachments/assets/48345c23-d0f0-4152-b3e3-8ef5a9152923)

**Comment by jesseallhands** [comment]
> * Change text to: `This request expired. To continue chatting, send the other person a normal message.`

Could we make the words "send the person a normal message" a link to a new chat with the person who sent the request? Or would that be too complicated? Can that be handled on this issue or a separate one?

**Comment by bakeiro** [comment]
> > * Change text to: `This request expired. To continue chatting, send the other person a normal message.`
> 
> Could we make the words "send the person a normal message" a link to a new chat with the person who sent the request? Or would that be too complicated? Can that be handled on this issue or a separate one?

That's a good idea, I think we need this before https://github.com/Couchers-org/couchers/issues/5148 :), but afterwards makes sense, I guess we can do it in other ticket, since we depend on issue 5148 (if I'm understanding correctly)

I say this because this becomes something very handy after the direct chat creation

**Comment by nabramow** [comment]
@aapeliv I think you did most of these things? Feel free to close if so.

**Comment by aapeliv** [comment]
Yes this is done, with some stuff left in #3526
