### ISSUE TITLE
Fix layout issue on reference flow pages

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#5172]
Problem:

The layout of the pages where you leave a reference for someone currently look wonky. Specifically, the profile div box on the left should be about 1/3 of the content div box with the reference div box being the other 2/3:

![image](https://github.com/user-attachments/assets/756bab7b-6e80-4eb8-a176-6ab7254a0ab3)

Here is what that page should look like on desktop (disregard the differences in navigation and texts):

![Image](https://github.com/user-attachments/assets/2bca9b63-2e6d-4d75-a553-b5bf4c990c29)

**Comment by bakeiro** [comment]
duplicated issue from https://github.com/Couchers-org/couchers/issues/4156, closing since the other one it's being worked already

**Comment by bakeiro** [comment]
@jesseallhands ping just to let U know
