### ISSUE TITLE
fake loader when the profile doesn't exist

### ISSUE THREAD

**Issue by bakeiro** [Couchers-org/couchers#5226]
# Context:
- Start a conversation
- Person closes/deletes its account
- Open chat page
- See weird 'fake loader' in the page
- Doesn't look great

# Pictures
![image](https://github.com/user-attachments/assets/2169557e-48c0-4d4d-bd3f-639ff4e90ee2)
![image](https://github.com/user-attachments/assets/a5d3d7bc-d075-4175-bc01-bcb8f371eb87)

**Comment by jesseallhands** [comment]
I think @aapeliv added this on purpose for deleted accounts, but I agree it can be confusing. At first I thought it was just content that still needed to load. 

I think instead we should have "deleted account" or some other kind of placeholder. We should probably look at how other platforms handle this (reddit just does [deleted]). In any case this needs discussion/design tho so I'm moving this to engineering backlog til we decide on something.

**Comment by aapeliv** [comment]
> I think @aapeliv added this on purpose for deleted accounts, but I agree it can be confusing. At first I thought it was just content that still needed to load.

It's not on purpose. There's another issue for this: https://github.com/Couchers-org/couchers/issues/4297

**Comment by bakeiro** [comment]
closing this one in favor of https://github.com/Couchers-org/couchers/issues/4297
