### ISSUE TITLE
Page scrolls halfway down on load

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#5257]
Video:

https://github.com/user-attachments/assets/7668a205-260b-49f3-891e-afcc2adc8d14

The culprit is this line:

https://github.com/Couchers-org/couchers/blob/1338c1c8df756237dc2eac18edf1ad09994feac2/app/web/pages/_app.tsx#L67

I don't entirely know what that code is doing, and maybe it will be sorted out with the Next.js upgrade. Maybe the `navigator.userAgent` should match something else?

**Comment by jesseallhands** [comment]
@aapeliv is this just a note to yourself? Or do you have more details to share so someone can pick this up? I put it on the backlog board with "needs research" for now, but depending on when/where this is happening it could be more critical.

**Comment by aapeliv** [comment]
@nabramow I'm going to assing this to you as you probably know best what's going on here.

Frankly (and as a lifelong firefox user, this hurts me), if it's something that will be fixed soon enough in the Next upgrade, then let's not worry about it if the fix is not easy.
