### ISSUE TITLE
Add "report a bug" feature to the navbar

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#5274]
### Problem
The bug reporting feature that previously existed on the website has disappeared. There used to be a button in the upper-right corner of the screen next to the hamburger-menu button.

Because of this, users cannot easily report bugs like they used to be able to. Users are only given the opportunity to report a bug if an error occurs and we have error handling for it. In all other situations the user only has the option to email support or open a ticket on github (if they event know how to do that). 

Here is what it looked like:
![image](https://github.com/user-attachments/assets/3c385430-7826-4018-9a06-853285eebfde)

### Solution
The quickest solution would be to restore the bug-reporting feature we used to have (red button next to the hamburger-menu button in the upper-right of screen). I'm not sure when this feature was removed, but it was fairly recently (within the past 6 months). We should be able to use the old code to bring it back quickly.

Related to #5266 

Edit: I am splitting the Sentry-based bug-reporting "upgrade" into a separate issue #5291

**Comment by bakeiro** [comment]
@jesseallhands 

why this closes https://github.com/Couchers-org/couchers/issues/5266?
also, doens't this goes agains the Doms Designs? seems intentional change [see https://github.com/Couchers-org/couchers/issues/4127]

**Comment by jesseallhands** [comment]
@bakeiro you're right, this shouldnt close that one. Technically #5291 closes #5266 so I'll update my note
