### ISSUE TITLE
Markdown visual editor

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#536]
We should use a nice visual editor for markdown fields. (Also, the markdown component should accept a "default" for blank fields)

A few possibilities:

- https://bevacqua.github.io/woofmark/
- https://easy-markdown-editor.tk/
- https://github.com/nhn/tui.editor - this one supports WYSIWYG - only

**Comment by aapeliv** [comment]
> https://github.com/nhn/tui.editor - this one supports WYSIWYG - only

This looks very good to me.

What's your opinion on these as a non-native markdowner, @ItsiW?

**Comment by aapeliv** [comment]
It has this kind of WYSIWYG/Markdown view: https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode

**Comment by ItsiW** [comment]
How dare you, I'm md born and bred.

That being said, pick the one that works nicest on mobile

**Comment by lucaslcode** [comment]
Component is done, default headings need to be done still

**Comment by lucaslcode** [comment]
Closed in favour of #1246
