### ISSUE TITLE
Events MVP

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#541]
To-do:
- [x] Create event form/page
  - [x] v1 - allows user to add title, time, date, event details, location, photo
- [x] Event section in community page
- [x] Events listing page for a community (under events tab)
- [x] Single event page
  - [x] v1 - Basic event details - title, time, date, attendees, organisers, photo
  - [x] v2 - event discussions, updating attendance state
- [x] Edit event page (should hopefully be more or less identical to create event)

**Comment by lucaslcode** [comment]
Needs field/filter for online

**Comment by kalvdans** [comment]
Backend part done in https://github.com/Couchers-org/couchers/pull/744, removing backend tag

**Comment by darrenvong** [comment]
Updated the issue description mainly as a check list for me to work through it based on looking at the designs. Have I missed any important pages @lucaslcode @aapeliv?

**Comment by lucaslcode** [comment]
Also editing

**Comment by darrenvong** [comment]
Wrapped up by Couchers-org/couchers#1862 and further non critical enhancements spun off to Couchers-org/couchers#4183
