### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#543]
This needs:

- [x] A (slight) redesign of the discussion cards in the communities page (Maybe just adding avatars)
- [x] A `Comment` component to display a comment with a reply button (and a text input that gets revealed?)
  - [x] Show replies
  - [x] Reply button reveals form that can be used to reply to that top level comment
- [x] ~~A `Reply` component, a reply to a comment that doesn't have a reply button (there is only 1 level of replies)~~
- [x] A `CommentTree` component that shows
  - [x] a list of comments
  - [x] all of the comments' replies
- [x] A page that lists all the discussions in a community
  - [x] ~~Refactor this later to share more markup with discussion section if it makes sense~~
  - [x] Tests
  - [x] Storybook
- [x] A page that shows the comments/replies for a single discussion
  - [x] Redo to match design
  - [x] Storybook
  - [x] Render single discussion with community markup - see [this PR discussion more details](https://github.com/Couchers-org/couchers/pull/1197#issuecomment-835881976)
- [x] A page for creating a new discussion in a community
  - [x] Functional form
  - [x] Styling
  - [x] Storybook
  - [x] Tests

These components should be in storybook

This will use #536 but can be done with normal text or the existing markdown editing component for now

**Comment by lucaslcode** [comment]
Frontend barebones are done in #578, however it needs to be refactored to use `react-query` and `react-hook-forms`
