### ISSUE TITLE
Search redesign

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#547]
~~Fuzzy on name, simple~~

Update: backend is in place, we just need to implement the design.

To start with, we don't need an omni-search, just select what you want to search for first.

Then, we should display everything (eg. all users) on the map like the soft beta map does (from a big geojson), and when a search is performed, pass the result ids to the layer as a filter.

Also, make the map use the light theme

**Comment by lucaslcode** [comment]
Also search for groups, discussions, places, etc?

**Comment by aapeliv** [comment]
Backend part now merged in #650 

> Also search for groups, discussions, places, etc?

Yes, name is ambiguous, I meant "communities features" search :).

**Comment by Tay0108** [comment]
I don't know how to filter features (markers) on clustered layer - do you have any ideas? Or maybe we should turn if off for search?

**Comment by aapeliv** [comment]
It seems difficult: https://stackoverflow.com/questions/36179464/mapbox-gl-js-filtering-marker-clusters.

Let's leave it out for now, I'm not sure what the prettiest way is, I guess just turn clustering off?

**Comment by Tay0108** [comment]
Yeah, I think this would be the best for now, because you would see a lot of clusters and no users after you zoom in.
