### ISSUE TITLE
Advanced push notifications

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#557]
@henrivuorinen and I spent a few hours today and part of it was a discussion on notifications. Here's some preliminary ideas on database models and interfaces for it. I didn't want to open a PR since I imagine this will be worked on a lot later, so I'll just drop the code here.

```py3

class NotificationDeviceType(enum.Enum):
    email = 1
    web = 2
    android = 3
    ios = 4


class NotificationDevice(Base):
    __tablename__ = "notification_devices"

    id = Column(BigInteger, primary_key=True)
    device_type = Column(Enum(NotificationDeviceType), nullable=False)
    user_id = Column(ForeignKey("users.id"), nullable=False)

    # other registration info, bookkeeping, etc, e.g.
    # device_name = Column(String, nullable=False)
    muted = Column(Boolean, nullable=False, default=False)

    user = relationship("User", backref="discussion_subscriptions")


class NotificationType(enum.Enum):
    friend_request = 1
    group_chat_message = 2
    # ...


class Notification(Base):
    __tablename__ = "notifications"

    id = Column(BigInteger, primary_key=True)
    recipient_user_id = Column(ForeignKey("users.id"), nullable=False)

    notification_type = Column(Enum(NotificationType), nullable=False)
    # used to deduplicate notifications and e.g. send only one email from multiple messages
    notification_key = Column(String, nullable=True)

    message = Column(String, nullable=False)

    sent = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    seen = Column(DateTime(timezone=True), nullable=True)

    user = relationship("User", backref="discussion_subscriptions")


class NotificationDelivery(Base):
    __tablename__ = "notification_deliveries"

    id = Column(BigInteger, primary_key=True)

    notification_id = Column(ForeignKey("notifications.id"), nullable=False)
    notification_device = Column(ForeignKey("notification_devices.id"), nullable=False)

    sent = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    seen = Column(DateTime(timezone=True), nullable=True)
    cancelled = Column(DateTime(timezone=True), nullable=True)

def send_notification(user, message, notification_key=None):
    pass
```

Each notification should be sent to all devices a user has. Then once the notification has been marked as read/interacted with on one device, the others should be sent some kind of "cancel" signal. Email could work on a "delay": it would only send an email after x minutes and collate any other messages into the same one.

**Comment by lucaslcode** [comment]
https://firebase.google.com/docs/cloud-messaging, has python bindings, support for iOS, android and web

**Comment by aapeliv** [comment]
This would build on top of FCM.

I had a look at these today, including FCM and APNS, and it seems that all they really do is just "dumb" message delivery to the client (which itself is super annoying due to battery life limitations, so it's good to share one connection with other FCM/APNS services). If we want smarter behavior, e.g. a notification being removed from other devices if it's seen on one, none of these seem to provide that functionality. They don't even provide a way to cancel a notification on the device itself, you have to implement that yourself.

It seems this might be a bit annoying to implement, I'd be happy to offload it to services like FCM or look into other open source components to take care of it. But having had a look, I haven't seen anything particularly promising, unfortunately.

**Comment by kalvdans** [comment]
One alternative would be to keep a TCP connection open to the clients and push data that way. I like it because it is decentralized.

**Comment by aapeliv** [comment]
> One alternative would be to keep a TCP connection open to the clients and push data that way. I like it because it is decentralized.

I would by far prefer this. It works fine when someone has the web app open, or when they have the mobile apps in the foreground, and we should definitely do that in that case. Unfortunately mobile OSs are super conservative with battery life and don't let you have persistent connections. The only way to wake them up when in the background and show a notification is to use one of these basically OS-provided push notification systems.

**Comment by ShmuelTreiger** [comment]
Most companies/services don't pull notifications once you've interacted somewhere else. I suppose that's a nice feature, but I don't think that's strictly necessary.

**Comment by kalvdans** [comment]
I don't know about IOS, but on android you can allow apps to stay alive in background. [This is how to configure Telegram app, for example.](https://telegra.ph/Notifications-FIX) TCP keepalive packets are handled in the OS and never need to wake up the app, so doesn't consume so much more than push services.

**Comment by aapeliv** [comment]
The Android ecosystem is quite fragmented, different flavors of Android behave differently. It's a common problem that a bunch of cheap phone manufacturers have very aggressive "battery saving" functionality to kill off background apps. As far as I'm aware, the only reliable way to wake up the app in the background is to send a push notification through one of the services that are on an allowlist. (It's a problem with e.g. smaller messaging apps like Signal that are not yet globally recognized and in allow lists in the same way facebook messenger is)

**Comment by kalvdans** [comment]
So don't buy such phones, that are not couchers approved&trade;

**Comment by Vinalti** [comment]
Has there been any progress on notifications?
That's a major and really important feature.
I thought implementing in-browser notifications could be possible.
