### ISSUE TITLE
Add location to signup

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#601]
Currently it is only a text field "city", which is ignored when the user sets their location from jail

**Comment by aapeliv** [comment]
What's needed from backend for this?

I'm not sure what the current design is like, but would it be okay to have two API calls: basic details, and then the other stuff? I'm thinking we'd want to put the higher effort stuff on a separate screen so if people think it's too much, we still get their details and can spam them to finish signing up 😈

**Comment by lucaslcode** [comment]
Don't know if we need two calls. Just need to add lat/lng and TOS agreement to the CompleteSignup call

**Comment by aapeliv** [comment]
OK, I can do that
