### ISSUE TITLE
Security things

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#613]
I've labelled beta, can be pushed to v1.

Documenting some security things that need to be sorted out eventually

* Content-Security-Policy (this is laborious but important)
* ~A variety of other HTTP headers: Strict-Transport-Security, Referrer-Policy, X-Content-Type-Options, X-Frame-Options, X-XSS-Protection~
* Restrict cookie settings

Need to make sure these work with maps and any other 3rd party deps.

These will break the localhost -> prod API development, so need to do something for that (e.g. run a dev API concurrently).

**Comment by kalvdans** [comment]
Sucks to have to implement even more frontend-specific stuff in the backend.

**Comment by aapeliv** [comment]
> Sucks to have to implement even more frontend-specific stuff in the backend.

Yeah, it's a bit like that, making web APIs :P. Most of this will actually not be done in the backend though (there's no particularly good label, maybe `devops`). Maybe they'll all be doable in envoy, and whatever is serving the actual static frontend content.

**Comment by aapeliv** [comment]
* There's a bunch of things that are not timing-attack resistant: reset password takes 10 ms (210 vs 200) longer when the account exists. I'm not really sure if username enumeration is really that bad: there's plenty of ways to do it anyway... Needs some thought.
* When one a token (login/password reset/etc) is used, should we delete all tokens of that type? Or is it enough for them to have short expiry times?

**Comment by lucaslcode** [comment]
> I'm not really sure if username enumeration is really that bad

Especially since we have an rpc call that literally tells you if a user exists, has a password, or doesn't exist! :D

**Comment by aapeliv** [comment]
Some nginx stuff:

```
        #add_header Content-Security-Policy-Report-Only "default-src 'self' *.coucher.org; script-src 'self' 'inline'; worker-src'self' blob: ; child-src 'self' blob: ; img-src 'self' data: blob: ; connect-src https://*.tiles.mapbox.com https://api.mapbox.com";
        add_header Strict-Transport-Security "max-age=15552000; includeSubdomains; preload";
        add_header Referrer-Policy "origin-when-cross-origin";
        add_header X-Content-Type-Options "nosniff";
        add_header X-Frame-Options "DENY";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Fact "Kilroy was here.";
```

**Comment by aapeliv** [comment]
Implement some for the API domain in #1343, but the main thing with CSP, etc is to get these on the static files.

**Comment by aapeliv** [comment]
Most of the important stuff has been implemented now.
