### ISSUE TITLE
Profile editing

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#615]

**Comment by lucaslcode** [comment]
Related to #410 

In the design, profile editing is basically just the user page with added edit buttons. To avoid duplication but not let a single file become too large, we should split each section into a component (and sub-components), perhaps with an `editing: boolean` prop, and share them between the user page and profile editing page.

**Comment by lucaslcode** [comment]
In the mockup designs, editing is more integrated into the normal profile view. But what we have now is sufficient for the moment, so I'm unassigning this and moving to v1.

**Comment by aapeliv** [comment]
Done @lucaslcode?
