### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by kalvdans** [Couchers-org/couchers#631]
Running a too old client needs to tell the user to upgrade the client. I suggest we do this by adding a `v1` part to the URL of the API endpoints. Backwards-compatible changes in the API could be made right away without bumping the API. Breaking changes will need to move to a `v2` URL and we need to keep supporting `v1` for a while until all users has upgraded.

Clients should detect if a rpc method doesn't exist and then tell the user to upgrade.

This scheme means we can never downgrade the server, and we should probably have a deprecation notice so that the clients still work despite showing a message to upgrade.

The beta milestone could be discussed; what do you think @aapeliv @ItsiW et.al.?

**Comment by aapeliv** [comment]
Do you mean this for our "official" clients or third-party clients?

I don't think there will be many 3rd party clients for now, but I don't see any reason to deny them as long as we can guarantee users' data is handled securely, the clients don't abuse the service, and users are clear about what is official and supported and what is 3rd party. We are not after all trying to keep users' data hostage, etc.

However, I would like us to not make guarantees/commit to any stability until we are well into v1+. Things are changing very rapidly and I don't want to introduce extra constraints that slow the pace of development. It can be a lot of overhead to guarantee things like supporting an API endpoint for a while, or even making sure the protocol stays binary compatible, etc. If there is interest in the community, and once things become more stable and the API surface changes slow down, I would be more than happy for us to provide some level of support for third party clients, including helping them stay up to date on API changes and maintaining stability. I'm not sure exactly what people will build, but I'm sure people will come up with cool things!

In terms of our official apps: while we still only have the web app, we can mostly do "atomic upgrades", so versioning for that is not a big issue. I'm not sure how it will work once we have mobile apps.

In terms of how to actually implement this, there is a kind of established versioning scheme that a lot of gRPC users use.

I'd be happy to start thinking about this and we could build some tooling or whatever is needed to make it happen.

**Comment by kalvdans** [comment]
The need might not be so imminent for the official web app, users can reload the javascript if the app behaves strangely. While it would be nice to have a working versioning scheme even if we break compatibility on every commit, I understand it not the highest prio. Removing beta milestone.

**Comment by aapeliv** [comment]
The plan now as discussed over time, is to keep our current v0 with no guarantees on compatibility. Then once we've done a bunch more refactoring, we'll freeze v1 and commit to some level of protobuf-level compatibility (not reusing tags, etc).

**Comment by aapeliv** [comment]
I don't think we need an issue/an issue adds anything for this
