### ISSUE TITLE
Error building backend

### ISSUE THREAD

**Issue by ShmuelTreiger** [Couchers-org/couchers#632]
When I try to build the backend via `docker-compose up --build`, I get an error 

> backend_1   | sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "parent_node_id" of relation "pages" contains null values

which I assume is related to #628

[Full Output.txt](https://github.com/Couchers-org/couchers/files/5977750/Full.Output.txt)

**Comment by Tay0108** [comment]
The quick fix is probably to delete data directory and run docker composer again but I think this should be handled by db migrations.

**Comment by aapeliv** [comment]
Yes, you need to nuke the database, e.g. `rm -rf data/postgres/pgdata`, then restart the database container.

**Comment by ShmuelTreiger** [comment]
I nuked it using the troubleshooter, destroyed all images and apps, rebuilt. Same result.

![image](https://user-images.githubusercontent.com/14131043/107886868-7111e200-6eb7-11eb-8cef-73ffecb5b6b7.png)

(couldn't get the rm command to work)

**Comment by aapeliv** [comment]
You need to remove the “data” folder inside “app”. That should do the trick.

Best,
Aapeli
