### ISSUE TITLE
username/email field in login is case sensitive

### ISSUE THREAD

**Issue by cmtcosta** [Couchers-org/couchers#669]
Expected: the field IS NOT case sensitive (e.g. "user01" and "User01" are the same)
Actual: the field IS case sensitive (e.g. "user01" and "User01" are NOT the same)

**Comment by cmtcosta** [comment]
Possible duplicate of #258

**Comment by Tay0108** [comment]
This was resolved in https://github.com/Couchers-org/couchers/pull/739 

If it is still not working as expected or we want backend to treat user1 as UsEr1 then feel free to reopen.
