### ISSUE TITLE
Check emails are correct

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#688]
Check for each email:

* Sensible text
* Link is to correct/sensible page
* Link text corresponds to link target

**Comment by ShmuelTreiger** [comment]
Which notifications? Which button? (unless you plan on just taking care of it yourself)

**Comment by aapeliv** [comment]
It's the missed messages notification emails, they say "friend request" or something in the button, instead of taking you to "messages". I think there was some other small error in it too

**Comment by ShmuelTreiger** [comment]
Is this still an issue? If so, steps to reproduce? Because I ain't finding it.

**Comment by aapeliv** [comment]
As discussed in meeting 20, this is just a check to make sure all is sensible and we can push this out. Full pretty emails are Couchers-org/couchers#4203

**Comment by ShmuelTreiger** [comment]
I'll let someone else have a look at this. I did it myself last week, but didn't find any issues.
