### ISSUE TITLE
Generalize HostStatus Component

### ISSUE THREAD

**Issue by andreaowu** [Couchers-org/couchers#689]
The current implementation for [HostStatus](https://github.com/Couchers-org/couchers/blob/develop/app/frontend/src/components/HostStatus.tsx) is CouchIcon with a user prop.

Generalize this to be an icon with text because that will be used in many places - the props should be an icon, user, and class

This should get done before any implementation / usage of this prop, hence the high priority.

**Comment by lucaslcode** [comment]
We discussed this so my understanding is this should be split into two components:

1. A general Icon with Text component (what's a good name for this?)
2. A component specifically to display the user's host status, which has the user as a prop and uses the general component + some logic to display the right label

**Comment by andreaowu** [comment]
No, we shouldn't have two components. We should have one component that's the icon and the text, and this will be a common component that will be used anywhere we need such a thing. Attached is three instances in [which](url) this component would be used.

<img width="309" alt="Screen Shot 2021-02-24 at 7 51 48 PM" src="https://user-images.githubusercontent.com/1359259/109095963-ef515e00-76d9-11eb-9009-b53ed8ddc556.png">
<img width="350" alt="Screen Shot 2021-02-24 at 7 51 52 PM" src="https://user-images.githubusercontent.com/1359259/109095966-efe9f480-76d9-11eb-9bdb-2dd6109270be.png">
<img width="246" alt="Screen Shot 2021-02-24 at 7 52 32 PM" src="https://user-images.githubusercontent.com/1359259/109095967-f0828b00-76d9-11eb-8371-493c3b38547f.png">

All have icons on the left, text on the right.

After we build the component, wherever we need it, we pass in the icon name, text, and class as props.

**Comment by andreaowu** [comment]
No, we shouldn't make two components. We should make one common component, `IconText`, that has icon, text, and class as props. Here are three instances in which this component would be used. 
<img width="309" alt="Screen Shot 2021-02-24 at 7 51 48 PM" src="https://user-images.githubusercontent.com/1359259/109096183-5242f500-76da-11eb-9580-fd41c31c3abc.png">
<img width="350" alt="Screen Shot 2021-02-24 at 7 51 52 PM" src="https://user-images.githubusercontent.com/1359259/109096186-52db8b80-76da-11eb-91bf-31315648d6f0.png">
<img width="246" alt="Screen Shot 2021-02-24 at 7 52 32 PM" src="https://user-images.githubusercontent.com/1359259/109096187-52db8b80-76da-11eb-834c-8a3b759bab0f.png">

Whenever we need it, we use the `IconText` component; we don't need to make each instance above its own component as they'll all just end up being wrappers around `IconText`.

**Comment by andreaowu** [comment]
https://github.com/Couchers-org/couchers/pull/701
