### ISSUE TITLE
No way to unset/clear profile picture

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#731]
https://github.com/Couchers-org/couchers/blob/404cf8820d8afeb352838487f862d94fe7a9b711/app/backend/src/couchers/servicers/api.py#L212-L213

**Comment by aapeliv** [comment]
@dnalhg: could you take this next, please?

**Comment by dnalhg** [comment]
would doing this work: we make the avatar_key a NullableStringValue and then if it's null we can set user.avatar_key to None. Would I have to modify how this gets handled on the front end?

**Comment by aapeliv** [comment]
Yes, that would work too, and is probably cleaner given the rest of the API, or you can just use an empty string (but present) to denote null
