### ISSUE TITLE
Get a single friend request/relationship

### ISSUE THREAD

**Issue by ShmuelTreiger** [Couchers-org/couchers#738]
There's currently no way to get a single friend request/relationship. I'm thinking this would be useful, for example:

-Someone sends you a friend request
-You go to their page to see who it is
-Ideally, you can reply to the request right there on their page

-Someone sends you a friend request
-You get a notification
-You reply to friend request straight from the notification (i.e. how it is on FB)

It's entirely possible this can all be done with respondfriendrequest and I'm just out of the loop?

**Comment by lucaslcode** [comment]
On the `user` object, there is FriendStatus which can be pending, friend, not friend, etc. Is that enough?

**Comment by ShmuelTreiger** [comment]
FriendStatus is an enum for FriendRelationships (pending, accepted, rejected, cancelled)

**Comment by lucaslcode** [comment]
There's also one in the user message, index 20

**Comment by ShmuelTreiger** [comment]
OK, I see it now. That lead me down the rabbithole, and the answer is get_friend_status will get you a single friend_request. I still think we should have it as part of the API, even if it just calls get_friend_status (and maybe checks that it's a request).

**Comment by ShmuelTreiger** [comment]
I'm trying to get a friend request or a friend relationship, not a friendstatus. Currently, the only way to get a specific one is to query the database and filter for it.
