### ISSUE TITLE
Internal Page: Update gender without needing to hack the database

### ISSUE THREAD

**Issue by andreaowu** [Couchers-org/couchers#743]

**Comment by darrenvong** [comment]
I imagine we'll need a new rpc call for this too, as the current API only updates things for the current user of the API? @aapeliv  @lucaslcode

**Comment by aapeliv** [comment]
Sorry, I don't understand what required. The user can already update their name/gender with UpdateProfile. What's needed here?

**Comment by lucaslcode** [comment]
I changed it so the rpc call fails if the user tries to change gender, because of concerns about getting around profile visibility based on gender if we have that in the future. (Ie. X's profile is set to "show to women only", Y can change their gender, send X a message, change back, etc.)

**Comment by aapeliv** [comment]
Yeah, makes sense. I think that should be a permanent change: people can still email support to change it if they have a legitimate reason.

This should then probably be part of the admin API (see also #894)?

**Comment by darrenvong** [comment]
Sounds like you got this planned for the admin API, #894 wasn't there when I wrote that comment :p as there's only API for updating your own user and not for other users at the moment

**Comment by aapeliv** [comment]
Done in the admin api
