### ISSUE TITLE
Hide all community standing/verification bars (for now)

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#752]
These are not implemented yet.

Maybe we want to leave one grayed-out in a certain place (profile?) to show it is coming, but not in other places.

**Comment by ItsiW** [comment]
I reckon leave both greyed out on the profile and we can write some copy for the (?) next to them.

Draft:

Community Standing
"coming soon: a general score to indicate how other members of the community have trusted this person"

Verification
"coming soon: this person's documents have been verified, they are a real person"

**Comment by andreaowu** [comment]
Is there a way to differentiate between a "greyed out" look vs an actual grey bar (ie if our actual implementation _was_ a grey bar, how would that look different than the greyed out version)? There's no interaction for these so it's hard to differentiate, so I'm going to just delete it for now.
