### ISSUE TITLE
404 shouldn't change the url

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#753]
404 page currently redirects, but better behaviour would be keeping the incorrect URL, but showing the 404 page.

**Comment by vrouilhac** [comment]
Hello, I look at the code and I think I can solve this. In your routes files, you only need to remove the path props on the last route which is the 404 route

**Comment by lucaslcode** [comment]
Quite right! If you're keen, feel free to make a PR (:

**Comment by vrouilhac** [comment]
> Quite right! If you're keen, feel free to make a PR (:

Thank you :pray:

**Comment by darrenvong** [comment]
Closed by #765
