### ISSUE TITLE
Small messaging tweaks

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#757]
- [x] "Create a new group chat" -> "Create a new chat"
  - [x] Make sure dm also work from that dialog
- [ ] Change NavButtons to normal IconButtons
- [x] Chats with unread messages should be bold/have a badge
- [x] Don't let SendField grow (because it covers the message list)
- [x] Desktop tweaks?
- [x] Check all margins are appropriate
- [ ] New Request page - fix layout (all fields same size)

**Comment by andreaowu** [comment]
> Change NavButtons to normal IconButtons

There aren't any NavButtons on this page

> New Request page - fix layout (all fields same size)

Which page is this?

**Comment by lucaslcode** [comment]
Buttons on GroupChatView / HostRequestView. I think there is a component called HeaderNavButton

New request page is /messages/request/new/:userId but it will be fixed in #751
