### ISSUE TITLE
Profile action buttons

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#759]
Friend Request - should only be visible when appropriate (eg. send friend request button only if they aren't friends already).

**Comment by darrenvong** [comment]
This seems like a much better place than solving in #667. I will pursue with hiding the buttons instead in that!

**Comment by andreaowu** [comment]
Should this issue be actually 3 different issues (send a host request, message, friend request)? Seems like a lot to pack into 1.

**Comment by darrenvong** [comment]
Yeah or at least it'd make sense to split into at least 3 PRs - makes them more reviewable that way so more likely to be able to get it approved quicker if there are less things to check.

**Comment by andreaowu** [comment]
Split this out into multiple issues because they're pretty involved
