### ISSUE TITLE
Unable to send a friend request

### ISSUE THREAD

**Issue by darrenvong** [Couchers-org/couchers#763]
I think we removed the "add friend" button by accident during the profile page refactor in #712...

Use [this file](https://github.com/Couchers-org/couchers/blob/d325c6a005f7f0726ec3a5e57388f2bd0fbf294b/app/frontend/src/features/userPage/UserPage.tsx) as a reference to add it back in.

**Comment by andreaowu** [comment]
Overlap with #759, closing for duplicate.
