### ISSUE TITLE
Latest maplibre-gl has broken import

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#767]
It uses `maplibre-gl.css` instead of `mapbox-gl.css`. To fix this, update to the latest version in `package.json` and change the import

**Comment by vrouilhac** [comment]
Hey, can I fix this line in dependencies? :blush:

**Comment by lucaslcode** [comment]
Sure, I'm not 100% sure what I said will work though :D

**Comment by vrouilhac** [comment]
> Sure, I'm not 100% sure what I said will work though :D

I’ll make my research 👌

**Comment by vrouilhac** [comment]
@lucaslcode 

I checked the documentation and they seem new working on this. And support for Javascript frameworks seems to be in progress.
Though can you tell me where the breaks seem to appear? 
Also, I've struggled to understand the backend :sweat_smile: the data are stored locally? if I want to create a test account to check on the frontend?

**Comment by lucaslcode** [comment]
Someone got an error on the line `import "maplibre-js/dust/mapbox-gl.js";`. I believe it's because this file was renamed in the latest version. 

Re the backend, you can follow the instructions in `app/readme.md` to run it locally, but it needs docker (and WSL if you're on windows). 

Alternatively, you can use the live preview backend by using  `REACT_APP_API_BASE_URL="https://dev-api.coucher.org" yarn start` to run the project. However, you will need to download the `app/frontend/src/pb` folder, which is auto-generated. You can get it from the [Gitlab pipelines](https://gitlab.com/couchers/couchers/-/pipelines) (search for the latest develop branch, click the first tick which is the step that does the generation, and click "download" on the right)

**Comment by vrouilhac** [comment]
> Someone got an error on the line `import "maplibre-js/dust/mapbox-gl.js";`. I believe it's because this file was renamed in the latest version.
> 
> Re the backend, you can follow the instructions in `app/readme.md` to run it locally, but it needs docker (and WSL if you're on windows).
> 
> Alternatively, you can use the live preview backend by using `REACT_APP_API_BASE_URL="https://dev-api.coucher.org" yarn start` to run the project. However, you will need to download the `app/frontend/src/pb` folder, which is auto-generated. You can get it from the [Gitlab pipelines](https://gitlab.com/couchers/couchers/-/pipelines) (search for the latest develop branch, click the first tick which is the step that does the generation, and click "download" on the right)

I didn't have struggles to run it, it runs good and I already have docker as I use it. My question wasn't clear enough, is it running locally so I can create an account locally to test the website or not? Because I tried using fake email to test the frontend but couldn't do it with test@test.com

Edit: After making some research I found that the current version in package Is `"maplibre-gl": "^1.13.0-rc.4"` but reading through maplibre github repo it seems that the current version is `"maplibre-gl": "^1.13.0-rc.5"`. So i updated it in package.json

**Comment by lucaslcode** [comment]
If you check the docker logs for the backend container, it will tell you the generated links for sign-up/login since it doesn't send an email in dev

**Comment by lucaslcode** [comment]
Do you want to make a PR for the change?

**Comment by vrouilhac** [comment]
> Do you want to make a PR for the change?

Sorry I was busy yesterday, today I want to make more test and check if it seems good and I'll make a PR.

**Comment by lucaslcode** [comment]
closed in #777
