### ISSUE TITLE
Change login/signup picture

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#774]
It is time to source these @ItsiW

**Comment by andreaowu** [comment]
Have we decided on what we're doing for the photo? Happy to do the update it in code if we did!

**Comment by ItsiW** [comment]
Miuriel is gathering all the community photos in one place. We'll start getting photos via the forum too, and then we can decide based on what's available. The stock photo is fine for now

**Comment by andreaowu** [comment]
Which stock photo are you referring to?

**Comment by ItsiW** [comment]
Ah looks like the photo was removed

**Comment by andreaowu** [comment]
Login page has the right photo now, fixed by #794

**Comment by lucaslcode** [comment]
@ItsiW are you sure? Check on mobile - I thought we didn't want an undiverse photo (desktop is ok)

**Comment by ItsiW** [comment]
Good catch, I'll get Miuriel to pick one. Also is it easy to change it so the photo colours don't invert in dark mode? Or is that a my phone problem?

**Comment by lucaslcode** [comment]
Not too sure. Maybe it will be fixed when we have an actual defined dark mode?

**Comment by lucaslcode** [comment]
Moved to beta, see #911 for soft beta solution

**Comment by lucaslcode** [comment]
@ItsiW you can close this or leave open, up to you
