### ISSUE TITLE
EditUserLocationMap search with no results doesn't say "No results"

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#789]
Couldn't figure out why this happens, it should work by default. Setting the `noOptionsText` prop had no effect. I can see the popup being added to the end of the DOM body, but it doesn't contain any text.

![image](https://user-images.githubusercontent.com/32044095/111053613-19867800-845d-11eb-9c3b-fc18731f18a2.png)

**Comment by Tay0108** [comment]
I'll take it after weekend if nobody fixes it until then ;)

**Comment by Tay0108** [comment]
You cannot have `freeSolo` and `noOptionsText` at the same time. This PR (https://github.com/mui-org/material-ui/pull/19663/files) solves this issue by letting you add hint text with `freeSolo` option on, but do we want to have `freeSolo` here?

**Comment by lucaslcode** [comment]
This was closed at some point, it `getFilterOptions` (or something like that) needed to be set
