### ISSUE TITLE
Function to convert (lat, lng) into timezone

### ISSUE THREAD

**Issue by OmerBaddour** [Couchers-org/couchers#795]
Need a function to convert (longitude, latitude) into a timezone, so that when users input their address (which is used to derive (longitude, latitude)), we can infer their timezone. This timezone would then be used to view all time data through, such as the time of events.

**Comment by lennartvanlaake** [comment]
@aapeliv this issue has a merged PR linked to it. Can it be closed? 

I was looking for work to pick up, starting with highest priority, and found this one on top.

**Comment by aapeliv** [comment]
> @aapeliv this issue has a merged PR linked to it. Can it be closed?

Yeah. The tz stuff still needs more work but that's tracked elsewhere and this can be closed.
