### ISSUE TITLE
Host request view doesn't give request info

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#797]
Also there is an overflow menu that only says "placeholder" which can be removed.

Also there is no padding between the "accept/reject/etc" buttons and message box.

**Comment by andreaowu** [comment]
Don't need to do this, I'm going to make the actual request box.

**Comment by andreaowu** [comment]
Oh wait jk, this is for the message after making a request.

**Comment by justjooshing** [comment]
@andreaowu Am I confused? I thought I did this card?

> this is for the message after making a request.

Do i need to do something else for this? ^

**Comment by lucaslcode** [comment]
Andrea's comment was from before your PR

**Comment by justjooshing** [comment]
Ha ok, I was so confused :joy:
