### ISSUE TITLE
Accepting friend request works, but the request stays in the loading state...

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#798]
...in the "Friend Requests" section, until you reload. Maybe the query cache isn't invalidated on success?

**Comment by vrouilhac** [comment]
Hi, I'd like to see if I can understand what is going on here :D

**Comment by vrouilhac** [comment]
~~I'm not sure but in the file FriendRequestReveive.tsx you set the loading state when isLoading is true but also if isSuccess is true~~

~~in useFriendRequests isLoading is set to 0 ( which is PENDING ) but I'm not sure it updates after that assignment~~

**Comment by telalpal** [comment]
Hi @lucaslcode ,
it's my first try to contribute, so probably I am doing smth wrong.
I tried to pick up this issue or add labels/reviewers at PR but seems I don't have such rights. 
Please take a look if you will have time https://github.com/Couchers-org/couchers/pull/837.
Thanks!

**Comment by darrenvong** [comment]
Closed by #837
