### ISSUE TITLE
Put the logo in and update the palette

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#816]

**Comment by lucaslcode** [comment]
Color | Main | Shades
-- | -- | --
Orange | #E47701 | #FE762A #FE5E01 #FE982A
Green blue | #00A398 | #6BC4A6 #20686C
White backgound | #FCFCFC |  

I have requested an svg logo

**Comment by darrenvong** [comment]
Where is the logo gonna be made available? The wiki? Or do we have to export from Figma ourselves?

**Comment by lucaslcode** [comment]
It's in the design team Google drive linked on the wiki. SVG now available
