### ISSUE TITLE
Minimum user age

### ISSUE THREAD

**Issue by darrenvong** [Couchers-org/couchers#831]
When the user signs up, there aren't any checks on the date of birth they provide apart from it's in a valid date format that the backend can accept. This means it's possible to create a user that's just been born (since the date field defaults to today's date):

![A 0-years-old profile!](https://user-images.githubusercontent.com/13669362/111884202-ee99a800-89b7-11eb-98b2-8d9b8c9e2667.png)

I think it'd be good to add an additional check on this on the backend so we ensure the user signing up is at least 18?

**Comment by aapeliv** [comment]
There is a check, but the check just makes sure you were born in the past (inclusive of today). We will need to decide on the minimum age, and that will mostly depend on legal stuff.

**Comment by Tay0108** [comment]
So is it really frontend bug? I'd remove frontend label because when backend validation fails we will get error displayed on front, right?

**Comment by darrenvong** [comment]
Depends on if we view this to be completely the backend responsibility. It could be argued that the frontend could do a bit more on form validation to stop people submitting the form if their age is below a certain threshold too. And I thought since the line is bit blurry when I thought about it like that... I've just tagged both sides in 🤷

**Comment by aapeliv** [comment]
I think this is better kept solely in the backend: this (min age) is non-obvious business logic that we shouldn't be duplicating across multiple places.

**Comment by aapeliv** [comment]
This just requires deciding on an age, I'll update later when I've got an answer!

**Comment by aapeliv** [comment]
The minimum age should be 18 at least for now.
