### ISSUE TITLE
Update references to use the new API in references.proto

### ISSUE THREAD

**Issue by darrenvong** [Couchers-org/couchers#832]
This is a breaking API change so #812 can't be merged until the frontend has been updated to use the new references API too.

I'll also try to make this work with pagination too as the new API now supports this nicely with the different filters expected as in the [Figma design here](https://www.figma.com/file/z1aQUklCQewLsEFUo2HsLz/Desktop-Mockups?node-id=4661%3A19717)

**Comment by aapeliv** [comment]
Closed by #812
