### ISSUE TITLE
Coordinate wrapping

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#835]
Currently the database will accept coordinates with `lat` outside `[-180,180]`, which is problematic, this requires a bit of inverstigation.

The best would be to enforce this in the database somehow

**Comment by aapeliv** [comment]
Something like this fixes it in the db: `st_wrapx(st_wrapx(st_makepoint(200,30),-180,180),180,-180)`

See also discussion in #834

**Comment by aapeliv** [comment]
@spreeni: would you like to take this?

I think it requires two things:

1. Update `create_coordinate` to cast first to geography then back to geometry: that will make sure it's wrapped
2. Writing a migration to fix existing points (there are currently some in the database that aren't within bounds)

**Comment by spreeni** [comment]
Sure, I could take this. Would we really want to wrap the coordinates though? I think capping them at a min/max value makes more sense as `st_contains` does not support wrapping in the end. I think wrapping would make more sense if we worked with geography data.

**Comment by aapeliv** [comment]
Yeah, I think it's good to wrap, it's safer than clipping, which might cause weirdness if some unwrapped coordinates do slip through. The other option would be to be very strict about it and just fail if you get coordinates outside the bounds.

I mean that we should wrap before inserting into the db, so the db should never contain coords outside the bounds.
