### ISSUE TITLE
Tests pass even when there are TypeScript errors

### ISSUE THREAD

**Issue by darrenvong** [Couchers-org/couchers#851]
According to https://github.com/facebook/create-react-app/issues/5626, there's a limitation in how Create React App sets out jest, which means type checking isn't being done properly on test files. That means tests could still be passing even if they should break because of TS error.

The workaround seems to be adding `tsc` before running the tests so the test files goes through the TS type checker and only run the tests if succeeds. Will have to fix some broken test files as a result of this.

Also, linting also don't seem to be applied to test files which would normally fail the app build, so we may need to add a similar workaround to the above by running the `eslint` command against files ending in `test.ts[x]*`.

**Comment by lucaslcode** [comment]
Is this why tests are passing CI but failing locally?

**Comment by darrenvong** [comment]
No don't think so, that's a separate issue. I think the tests failing locally is something weird with the mocks not working again... not sure why CI likes the workaround but not our machine locally sometimes 🤷 

This is more to do with the fact if you add a new prop to a component and you don't update the tests, sometimes it stills passes (when it should fail like in the main app)

**Comment by thdk** [comment]
Hi everyone! I would love to pick up this issue (and join the development team if I may :) ).

**Comment by lucaslcode** [comment]
Assigned! Also send me an email (address on my profile)

**Comment by darrenvong** [comment]
One other thing I forgot to write in the first description, can you also look at linting the test files too while you are in the area please? I think these are all related enough issues that it'd be good to fix them together. Apologies if that might mean more files to fix 😬

**Comment by thdk** [comment]
No worries, I've jest setup my dev environment so I can start working.

Do you mean these two lint warnings?

![image](https://user-images.githubusercontent.com/4201102/114278239-174d1480-9a2f-11eb-97f9-b24417a2b53d.png)

**Comment by darrenvong** [comment]
> Do you mean these two lint warnings?
> 
> ![image](https://user-images.githubusercontent.com/4201102/114278239-174d1480-9a2f-11eb-97f9-b24417a2b53d.png)

Yup! Looks like there aren't too many then 😌
