### ISSUE TITLE
Refactor navigation bar components on unauthenticated pages

### ISSUE THREAD

**Issue by darrenvong** [Couchers-org/couchers#855]
These are duplicated in a few places, makes updating them a bit of a pain and I didn't want to do it in #852. Refactoring that into a shared component with the right hand side remain flexible will make maintaining/changing things in those unauthenticated pages there easier going forward.

**Comment by lucaslcode** [comment]
@darrenvong I don't totally understand this, is it still an issue?

**Comment by darrenvong** [comment]
Yes, there is some copy and pasted code if you look on the landing page, sign up and login page when they have the same mobile and desktop markup in some places. The styles are even shared that way with `authClasses` to allow copy/paste (to get something out quick I assume?) when that could be encapsulated into a single component.

I think we can refactor some of it into a common base and use props and `children` to make the bits that are different configurable, similar to what we're planning to do for the community base page

**Comment by aapeliv** [comment]
I think this is done
