### ISSUE TITLE
Login/signup tweaks

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#857]
- [ ] Padding between fields
- [ ] Move the left text on `CompleteSignup` up
- [ ] Signup map reloads page when pressing enter

Last one needs an ugly workaround - split the `<form>` into two, each side of the map (so the map isn't included). It will still function correctly because react-hook-form doesn't use this element, except for submitting on <Enter> presses.

**Comment by Tay0108** [comment]
Also underline under subtitle is missing: 
![image](https://user-images.githubusercontent.com/10603901/112450353-9d413e00-8d54-11eb-9796-4889c72aede7.png)
