### ISSUE TITLE
Auto-saving or caching profile/message information as it is typed

### ISSUE THREAD

**Issue by naspitha** [Couchers-org/couchers#861]
If I'm filling out my profile information and refresh the "Edit Profile" page, my changes, unsurprisingly, disappear. 

Can there be a mechanism to periodically "auto-save" information a user enters into their profile or into a message? I imagine that users will be writing long blocks of text on their profile (and long, thoughtful messages!), so it would be nice to have a safety net in case something happens to the user's browser (e.g. the accidentally close the app). 

The information could go into a temporary cache and re-populate the text boxes in question if the browser is reloaded. But the profile pages should not be updated until the "save" button is actually saved.

Feel free to close the issue if this is not a suitable idea.

**Comment by naspitha** [comment]
BTW I don't have permissions to add labels, so if someone can label this issue appropriately (frontend, priority: low?) it would be appreciated.

**Comment by ShmuelTreiger** [comment]
Similarly, if I'm refreshing the page or clicking away and have unsaved data, a warning popup would be great (potentially with three options: cancel, save, continue)

**Comment by aapeliv** [comment]
Current functionality is fine. Auto-saving is not universally superior, people don't always like their drafts being published.

**Comment by ShmuelTreiger** [comment]
Very strongly disagree. I hate websites that don't save your data or don't at least warn you before deleting it. Nothing worse than spending a half hour filling something out only for it to disappear.

**Comment by aapeliv** [comment]
This is for auto-saving, not warning

**Comment by naspitha** [comment]
Yes, but a warning before closing/refreshing a tab would help. (e.g. chrome sometimes has "Leave this page? Changes you made may not be saved")

**Comment by aapeliv** [comment]
Opened a new issue for that https://github.com/Couchers-org/couchers/issues/1635
