### ISSUE TITLE
Profile editing leakage when using multiple dev previews

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#872]
When logged in as different users on different previews, they seems to get mixed up.

Steps to reproduce:

- 1 is https://8b9b2a64--frontend.preview.coucher.org/
- 2 is https://develop--frontend.preview.coucher.org/
- log out both
- sign in as test on 1
- sign in as lucas on 2	
- Change name on 2 - it worked
- Set melbourne as location in 1
- (There is another issue where the circle sometimes doesn't move when selecting a location. It worked when I tried again.)
- Redirect to profile shows location hasn't changed on 1
- "lucas" in both 1 and 2 now have profile details that were from the change on 1, which was logged in as "test"

**Comment by lucaslcode** [comment]
Would it be because the api is the same address, https://dev-api.coucher.org, so it uses cookies from the most recent login? That would explain it.

**Comment by aapeliv** [comment]
Yes, cookies are completely decoupled from JS, and can't even be read there due to the `http-only`ness.

**Comment by aapeliv** [comment]
If you think this is a problem, we can do something like the frontend sending out the user id that it thinks it is in every request, and if that disagrees with the session cookie on the backend, the request will be rejected.

**Comment by lucaslcode** [comment]
I think it's fine, not worth the effort.
