### ISSUE TITLE
Edit Profile unexpected design behaviour ?

### ISSUE THREAD

**Issue by vrouilhac** [Couchers-org/couchers#884]
I tried to update the profile and I saw some behaviour in the design that I think may be unexpected.

When both "Countries I've visited" and "Countires I've lived in" are empty, they both appear one next the other.

First unexpected behaviour :
When I add a country to "Coutries I've visited", the second input ( "Countries I've lived in" ) comes below.
![03-min](https://user-images.githubusercontent.com/62873665/113074170-e0733500-91ca-11eb-8be8-0ec61fad6b2f.png)
![04-min](https://user-images.githubusercontent.com/62873665/113074177-e537e900-91ca-11eb-98b8-c75758cb8d55.png)
![05-min](https://user-images.githubusercontent.com/62873665/113074188-e832d980-91ca-11eb-88f9-2c0a7cca1bfe.png)

Second : 
When i add a country to '"Countries I'v lived in", the country is added below the first input ( "Countries I've visited" )
![01-min](https://user-images.githubusercontent.com/62873665/113074198-ee28ba80-91ca-11eb-8067-fed35a7726aa.png)
![02-min](https://user-images.githubusercontent.com/62873665/113074204-f1bc4180-91ca-11eb-9a70-bc0e93711052.png)

**Comment by lucaslcode** [comment]
This is fixed in #882
