### ISSUE TITLE
Search: events

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#891]
Events search, requires #541, obviously. This should be fairly easy.

Full event filtering is available through the search API. This just needs to be in the "omnibox" search.

**Comment by ceelo777** [comment]
I'd be interested in taking this issue! Any more details I should know before tackling it - references to code I could look at, general tips, etc. - this is my first time contributing.

**Comment by ShmuelTreiger** [comment]
@aapeliv might be able to give you better advice, but I'd take a look at search.py and search.proto. That being said, if you want to work on search, perhaps better to start with one of the other search issues (#888, #889, #890)? Since this one is still waiting on #541 .

**Comment by aapeliv** [comment]
@ceelo777: as @ShmuelTreiger pointed out, this is still waiting for the actual events feature to be built. That'll still take some time as the PR (#744) is still quite incomplete. Feel free to look through the other issues tagged as `good first issue`. I also sent you a quick email if you want to set up a time to chat and join our contributor Slack! We'd be very glad to have you join the team :)

**Comment by aapeliv** [comment]
Done in #1218
