### ISSUE TITLE
Lower unseen message email time

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#892]
Currently unseen messages trigger a notification email if unseen for 30 minutes. This should be lowered to 5 minutes due to user complaints, and the background job also needs to run more often.

**Comment by ShmuelTreiger** [comment]
Unrelated, but reading through the code, it seems that a user will keep receiving emails if they keep receiving messages. Do we want to tamper this somehow?

**Comment by aapeliv** [comment]
Yes, eventually. The current system is a quick solution for beta, but we'll need to rewrite the notification system entirely, #557
