### ISSUE TITLE
Email reminders to write a reference

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#893]
Emails to remind a host/surfer to write a reference about the experience.

**Comment by kalvdans** [comment]
Closed by https://github.com/Couchers-org/couchers/pull/1302 ?

**Comment by aapeliv** [comment]
> Closed by #1302 ?

No, that just sends emails when the state changes (e.g. when accepted). These should happen say, 3 days, 7 days, and 12 days after the end of hosting (if no review was written).
