### ISSUE TITLE
Minimal Admin API

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#894]
We need an admin (superuser) API. Users table needs a boolean "is_superuser" or similar. Admin APIs are things like creating a new community, etc.

Waiting for a list of minimal absolutely required API calls from @ItsiW.

**Comment by aapeliv** [comment]
Requires #1373

**Comment by lennartvanlaake** [comment]
Aapeli:

* Get a user's email address based on username or user id (for support/moderation stuff)
* Create a community (there's some code in the tests, create_community I think. I was thinking that the community's polygon would be supplied as a geojson object from something like https://geojson.io/)

**Comment by aapeliv** [comment]
* Ban a user
* Delete a user (policy team is still figuring out what else to do than set `is_banned`, but that's the first thing)
