### ISSUE TITLE
Phone verification

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#896]
Using Twilio or AWS SNS (this is probably preferred due to us already using AWS heavily)

**Comment by aapeliv** [comment]
This is a good first issue if someone has experience with AWS and their SDKs, otherwise probably not!

**Comment by aapeliv** [comment]
If someone wants to work on this but is not very familiar with the AWS SDKs, you can start by just creating a `send_sms` dummy function, and I can fill it in with the actual delivery code later. That's the easy bit. Other than that, what's needed is:

1. RPC definitions for functions to add a phone number and verify it subsequently
2. Database modifications to store the phone number and the verification information
3. Backend implementation
4. Tests for backend implementation

The user should only be able to update their phone number every X days, let's start off with 365. Phone numbers should probably be validated with something like [python-phonenumber](https://github.com/daviddrysdale/python-phonenumbers) before delivery to make sure they're correct.

**Comment by aapeliv** [comment]
For phone number verification and formatting, this should work:

```py
def validate_and_format_number(number)
  try:
    parsed = phonenumbers.parse(number)
    if not phonenumbers.is_valid_number(parsed):
      return None
    return phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.E164)
  except phonenumbers.phonenumberutil.NumberParseException:
    return None
```

**Comment by kalvdans** [comment]
How often should a user be able to request a validation code? I guess there's a cost associated with the sms and we don't to spam the wrong person too much in case someone enters wrong number.

**Comment by aapeliv** [comment]
Once a year or they can contact support to update it would be good

**Comment by kalvdans** [comment]
Work-in-progress posted to https://github.com/Couchers-org/couchers/pull/1250. Would be nice with comments on the API (i.e. at the .proto files) at this stage.
