### ISSUE TITLE
Geo-data/map tiling

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#897]
Currently when a user goes on the map, we basically go through the whole user table and just generate a GeoJSON with all data.

This needs to be broken up into tiles to be served using TileJSON or MVT. I think the latter directly from postgis.

Not super urgent, but will be fun!

**Comment by aapeliv** [comment]
This was discussed in the last frontend meeting. My current thinking after that + mulling it over a bit is this:

1. Have a global single tile that contains just the user count clusters; and display that up to zoom level ~9 (at which cities start to become visible).
2. Have a personalized (removed blocked users, etc) set of tiles, generated at about zoom level 3-5 (between 64 and 1024 tiles per user).

This system will load faster and take less bandwidth, and will allow us to scale fairly far with it.

**Comment by lucaslcode** [comment]
And cache the zoom levels between 3 and 5? Or just always generate? Won't the former use up loads of storage?

**Comment by aapeliv** [comment]
Thinking about it, I believe mapbox caches a bunch on the frontend; so it'll take off some load (and probably the data will be stale by the time that cache is gone).

(Also, we can show a given tileset at a given zoom, even though the tileset "is for a different zoom", e.g. we can generate personalized tiles at level 5, but only show them at level 9+: that way we have to generate a lot less than the "native" ~16 tiles per map load)

**Comment by aapeliv** [comment]
See Couchers-org/couchers#4129
