### ISSUE TITLE
Old email needs to be confirmed when changing emails

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#912]
If a user has no password, and they want to change their email address, currently they can just do that without any confirmation. In particular, if someone leaves their laptop unlocked with Couchers open, anybody can trivially hijack their account. We can't have that.

Either:

1. Require a user to have a password to change their email address
2. Require verification of both old and new email any time they want to change their email
3. Same as above but only if the user has no password

**Comment by ShmuelTreiger** [comment]
Currently, if a user has a password, do we ask them to put it in again when requesting an email change?

**Comment by aapeliv** [comment]
> Currently, if a user has a password, do we ask them to put it in again when requesting an email change?

Yes
