### ISSUE TITLE
formatDate: month is off by one

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#916]
`formatDate` in `date.ts` formats `2021-07-11` as `11 August`, etc.

**Comment by lucaslcode** [comment]
🤦‍♂️

**Comment by lucaslcode** [comment]
@aapeliv you can do this if you can't wait for me to do it in around 10-12 hours. I just did `monthNames[date.month()]` instead of `monthNames[date.month()-1]|.

**Comment by lucaslcode** [comment]
@aapeliv you can do this if you can't wait for me to do it in around 10-12 hours. I just did `monthNames[date.month()]` instead of `monthNames[date.month()-1]|.

**Comment by aapeliv** [comment]
Fixed in 8d40298d
