### ISSUE TITLE
Remove gender from UpdateProfile

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#918]
To reduce abuse of gender-based features.

Users can still contact support if there is a legitimate need to change their gender.

**Comment by ShmuelTreiger** [comment]
I think this is already done

https://github.com/Couchers-org/couchers/blob/3bb5ebac88aff7aec40f909fbbfc0fa796382c3b/app/backend/src/couchers/servicers/api.py#L178-L181

**Comment by aapeliv** [comment]
It needs to be removed from the RPC defs and that stuff needs to be removed as well

**Comment by jesseallhands** [comment]
If you choose "other" you shouldn't be able to enter "he/him" or "she/her" by themselves as those options are already available. With that said, we need to be careful as some people use multiple pronouns like he/him and they/them equally.

**Comment by lucaslcode** [comment]
@AllhandsNoFeet does it matter? If you type he/him in other and save, if you reload the page that option will be selected
