### ISSUE TITLE
Unread request messages are not bold

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#923]
Unread chats are bold, but not host requests

**Comment by trevvorko** [comment]
I will complete this task. Is there also a link to the Slack channel somewhere? I couldn't find it anywhere in the README

**Comment by lucaslcode** [comment]
Send me an email

**Comment by trevvorko** [comment]
This is what I see for an outstanding host request. Could I get a little bit more information about what exactly should be bold that isn't? Or am I looking at the wrong host request location.
<img width="952" alt="image" src="https://user-images.githubusercontent.com/70543001/113919777-faf07400-97b1-11eb-96bc-cd9cb56dbe1f.png">

**Comment by aapeliv** [comment]
When you have an unread message in the first tab (Chats), the message will be bolded, both message and author.

<img width="404" alt="Screen Shot 2021-04-07 at 3 08 05 pm" src="https://user-images.githubusercontent.com/2975660/113920673-16a84a00-97b3-11eb-938f-901bf397ec89.png">

When you have an unread message in a hosting/surfing request, this doesn't happen, there's no way to visually distinguish read vs urnead messages

**Comment by trevvorko** [comment]
Ah okay I see. I will make it so it is bolded when there is an unread message from the other party (Host/Requester).

**Comment by aapeliv** [comment]
Great, thanks!
