### ISSUE TITLE
Errors not visible in jail page when adding location

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#925]
If you don't have a location (due to not having put one in in alpha, and you try to log in, you're taken to the jail page to add a location. (This bug might also occur on other pages with a map component)

If you just click through "Save" (or whatever the button says), the coordinate will be (0,0) or something, and the backend will return an error, however, the frontend doesn't show anything, so there's no feedback on why nothing is happening.

This is pretty bad as it's the first screen the user is taken to after the alpha upgrade and can cause frustration!

**Comment by lucaslcode** [comment]
`LocationSection.tsx` just needs some error handling.

**Comment by trevvorko** [comment]
I am a first time contributor, I'd like to tackle this issue. Is there any tips or pointers about the issue I should know before adding more error handling?

**Comment by aapeliv** [comment]
Hi @trevvorko: we'd be super happy to have you help out and contribute. I think I've just fixed this issue in #985 though, I didn't remember we had an issue open so didn't link it.

I'll ping @lucaslcode to chime in and see if he could assign you another issue; he's the frontend lead.

**Comment by lucaslcode** [comment]
Hi @trevvorko ! How about #923?

**Comment by trevvorko** [comment]
Sounds good! I'll take some time to get my development environment setup and work on that issue.

**Comment by lucaslcode** [comment]
@trevvorko if you comment on it, I can assign you
