### ISSUE TITLE
Community info page

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#927]
Pages/guides are postponed for now, except for the main page of a community. It is basically a title, and edit button, and a big body of markdown content.

When approaching this, keep in mind we will want to re-use it to display any page (not just main community pages) in the future.

**Comment by darrenvong** [comment]
Hasn't this been done in #737 and refactored recently in my discussion PRs?

**Comment by lucaslcode** [comment]
No, this is the page with information about the community, the "local info" page
