### ISSUE TITLE
Giving references

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#929]
We don't have a way to leave references atm.

A "give reference page" should be made as per the mockup. Friend references should be possible from profiles of people you are friends with and have not given a reference to. Host/surf references should be possible, perhaps from confirmed host requests which are in the past.

Imo the reference type should be passed in the url, like "/leave-reference/surfed/:userId". Backend will give an error if that reference type isn't possible, but we should check first on page load anyway.

**Comment by darrenvong** [comment]
Going to leave a few notes on what needs to be fixed based on what I found so far.

### Needs fixing
- Leaving a host/surfer reference seems to be broken at the moment :/ I think this is the culprit:
https://github.com/Couchers-org/couchers/blob/b6450a6dcc0b4a3a7052ab713a423ba7ae18189c/app/frontend/src/features/profile/view/leaveReference/LeaveReferencePage.tsx#L40-L45
- The reference text is not being remembered when the user goes back from the summary page. Probably a bug but I didn't want to drag the other PR on for longer. It's not good UX as the user might forget something, go back and realise all of their reference text is gone! But at least it's useable

### To be polished up
(personal opinion, so feel free to disagree)

- When the user is in a step of the leaving reference wizard, there should be a back button on the UI itself for going back to the previous step, similar to the back button in messages and discussions
- When the user tries to go on the next step without typing anything (or some minimum character count, TBD), we should show an error prompt on why they can't proceed. Currently, it just looks like the form is stuck/broken when you click next as there aren't any visual feedback as to why you can't proceed
- More functional tests... merging in almost 2k lines of code changed without at least some basic functional tests aren't ideal as there are bound to be things we've still overlooked

**Comment by javiwq** [comment]
I agree with all the "to be polished up" points. I'm going to first address the fixes and UI improvements, and then do a follow-up PR with functional tests, since the fixes can be done quick.
