### ISSUE TITLE
Link to account settings

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#934]
I'm not finding any way to go to account settings at the moment: https://app.couchers.org/account-settings

**Comment by thdk** [comment]
There's a button on the top right of _edit profile_ page

![image](https://user-images.githubusercontent.com/4201102/116781933-77f7cc00-aa86-11eb-86c9-23f90d3c0543.png)
and mobile
![image](https://user-images.githubusercontent.com/4201102/116781942-8cd45f80-aa86-11eb-915b-08b99985dd2f.png)

I'll close this issue, feel free to reopen if that button is too much hidden for our users.
