### ISSUE TITLE
Last active should be different for <15 min

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#938]
Last active is rounded to 15 min or something, so for less than 15 min ago it should say "<15 min ago" or "just now", or similar?

**Comment by aapeliv** [comment]
The backend returns the time of the last API call from that user, rounded down to the nearest 15 min before. E.g. an API call at 16:46:42 is rounded down to 16:45:00. So it's always rounded down to :00:00, :15:00, :30:00, or :45:00.

This means that close to the next time, it's going to say "last active 13 min ago" even if you were just active. E.g. on your profile, it look silly!

This irks me, but if no one cares, then it's not a big deal :P

**Comment by lucaslcode** [comment]
It used to be like this, it must have got lost when we redid profiles. 
Our `timeago` (or whatever it is called) function in `utils/` has an optional second parameter which fuzzes the last 15 minutes if I recall correctly
