### ISSUE TITLE
Add website and forum to navbar

### ISSUE THREAD

**Issue by ItsiW** [Couchers-org/couchers#939]
Before logout on the right hand side we want About (https://couchers.org) and Forum (https://community.couchers.org)

**Comment by jiwon1219** [comment]
Hi! I'd like to work on this issue!

**Comment by ineswq** [comment]
See #1037 and #1054 - missed that the routes lead to `/url` rather than `url`.

**Comment by javiwq** [comment]
See #1037 and #1054 - Realized the links lead to `/url` instead of `url`.
