### ISSUE TITLE
Profile long form text formatting with CommonMark

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#940]
It has to be formatted *somehow*. At least newlines need to be included so it's not all just a big mess, look at Jesse's profile.

**Comment by jesseallhands** [comment]
Can confirm. My profile is indeed a mess!

**Comment by lucaslcode** [comment]
These can be replaced with our markdown rendering component even if #536 isn't done yet

**Comment by lucaslcode** [comment]
closed in #536
