### ISSUE TITLE
Location selection component

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#950]
Reported by Hjall on the forum and others. We're getting a lot of reports that the location selection component is confusing/unintuitive and difficult to use. Also related to #858, these should probably be merged.

* Currently it's centered in Sydney by default
* It's not clear that the text in the search box will become the display address
* Depending on the address, the auto-generated display address is still too verbose
* Coordinates clipping is still very screwed up: when trying to go around the antimeridian, you get snapped onto it (to replicate, search between Sydney/New York a few times and it'll be clipped)

This probably needs a proper design and then maybe just a full rewrite?

**Comment by lucaslcode** [comment]
I wasn't following the coordinate wrapping, but I saw it clips in the code in the `onMove` function. Can we not just wrap it with a modulus before sending to the backend?

**Comment by aapeliv** [comment]
> Can we not just wrap it with a modulus before sending to the backend?

We should do that, yes.
