### ISSUE TITLE
FriendshipStatus in user objects only returns pending status from GetUser API 

### ISSUE THREAD

**Issue by darrenvong** [Couchers-org/couchers#954]
Currently when there is a pending request, we can't tell easily if a pending request is sent by current user or received from the user they are looking at from the frontend without extra data wrangling by getting data from `ListFriendRequests` and figure out from that. This should be encoded in `FriendshipStatus` instead.

**Comment by darrenvong** [comment]
This will likely simplify #905 a lot if it is a quick thing to add. Otherwise we can return to it as a separate refactoring thing on the frontend.

**Comment by aapeliv** [comment]
OK, I'll look into this now
