### ISSUE TITLE
[Landing page] design discrepancies

### ISSUE THREAD

**Issue by cmtcosta** [Couchers-org/couchers#965]
### Environment
iPhone 8 / browser: Safari

### Steps to repro
1. Access  https://develop--frontend.preview.coucher.org/ 

### Expected results
![image](https://user-images.githubusercontent.com/6439724/113512110-14e44980-955b-11eb-8d36-0aa595e040d4.png)

### Actual results
![IMG_6877](https://user-images.githubusercontent.com/6439724/113512147-3ba28000-955b-11eb-99a4-82d39e853250.PNG)
- KO Different background image
- KO Wrong copy line break on header: “Connect with the world around” / “you”
- KO Wrong copy on sub-header “Built by the community and always free”
- KO horizontal rule is missing
- KO "About us" link is hidden (need to scroll)

**Comment by thdk** [comment]
Closing because its outdated and newer issues already exist for landing/login/signup page (#1706)
