### ISSUE TITLE
[signup/your basic details page] design descrepancies

### ISSUE THREAD

**Issue by cmtcosta** [Couchers-org/couchers#967]
### Environment
iPhone 8 / browser: Safari

### Steps to repro

1. Access  https://develop--frontend.preview.coucher.org/ 
2. Press “Sign up”
3. Enter valid email address
4. Press “Sign up”
5. On signup email, click the link

### Expected results
![image](https://user-images.githubusercontent.com/6439724/113512458-aa340d80-955c-11eb-90fd-2d6cf42f1dc1.png)

### Actual results
![gif](https://user-images.githubusercontent.com/6439724/113512790-2844e400-955e-11eb-9239-14ed0d344b53.gif)
- KO Field “username” is displayed
- KO “Hosting status” field is displayed
- KO “I identify as…” field is displayed as radio button (instead of image buttons)
- KO “Terms of Service” title and body is displayed (with dummy/lorem ipsum copy)
- KO “Accept” button is displayed

**Comment by cmtcosta** [comment]
once all data is filled correctly and the user presses "Sign up", they are taken to a scrolled-down by default home page
<img src="https://user-images.githubusercontent.com/6439724/113513201-55929180-9560-11eb-98bd-381a311e04a9.PNG" width="350"> <img src="https://user-images.githubusercontent.com/6439724/113513202-56c3be80-9560-11eb-92e7-1fe04caaea72.PNG" width="350">

**Comment by lucaslcode** [comment]
Stale
