### ISSUE TITLE
[signup] “Stick to our rules!” page missing

### ISSUE THREAD

**Issue by cmtcosta** [Couchers-org/couchers#968]
### Environment
iPhone 8 / browser: Safari

### Steps to repro

1. Access  https://develop--frontend.preview.coucher.org/ 
2. Press “Sign up”
3. Enter valid email address
4. Press “Sign up”
5. On signup email, click the link
6. Fill in all fields correctly
7. Press "Sign up" button

### Expected results
![image](https://user-images.githubusercontent.com/6439724/113513414-8921eb80-9561-11eb-899b-091a0b8f5264.png)

### Actual results
<img src="https://user-images.githubusercontent.com/6439724/113513201-55929180-9560-11eb-98bd-381a311e04a9.PNG" width="350"> <img src="https://user-images.githubusercontent.com/6439724/113513202-56c3be80-9560-11eb-92e7-1fe04caaea72.PNG" width="350">
- “Stick to our rules!” screen missing
- once all data is filled correctly and the user presses "Sign up", they are taken to a scrolled-down by default home page

**Comment by darrenvong** [comment]
We should probably add this as a requirement before the user gets out of jail? Does that require backend change @aapeliv?

**Comment by aapeliv** [comment]
Done now!
